package clIocApi;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClIocAddressT extends Union {
	/**
	 * Physical address.<br>
	 * C type : ClIocPhysicalAddressT
	 */
	public ClIocPhysicalAddressT iocPhyAddress;
	/**
	 * Logical address.<br>
	 * C type : ClIocLogicalAddressT
	 */
	public long iocLogicalAddress;
	/**
	 * Multicast address.<br>
	 * C type : ClIocMulticastAddressT
	 */
	public long iocMulticastAddress;
	public ClIocAddressT() {
		super();
	}
	/**
	 * @param iocPhyAddress Physical address.<br>
	 * C type : ClIocPhysicalAddressT
	 */
	/*public ClIocAddress(ClIocPhysicalAddress iocPhyAddress) {
		super();
		this.iocPhyAddress = iocPhyAddress;
		setType(ClIocPhysicalAddress.class);
	}*
	/**
	 * @param iocLogicalAddress Logical address.<br>
	 * C type : ClIocLogicalAddressT
	 */
	/*public ClIocAddress(long iocLogicalAddress) {
		super();
		this.iocLogicalAddress = iocLogicalAddress;
		setType(long.class);
	}*/
	/**
	 * @param iocMulticastAddress Multicast address.<br>
	 * C type : ClIocMulticastAddressT
	 */
	/*public ClIocAddress(long iocMulticastAddress) {
		super();
		this.iocMulticastAddress = iocMulticastAddress;
		setType(long.class);
	}*/
	public ClIocAddressT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClIocAddressT implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends ClIocAddressT implements com.sun.jna.Structure.ByValue {
		
	};
}
