package clTimerApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clTimerApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClTimerTimeOutT extends Structure {
	/** C type : ClUint32T */
	public int tsSec;
	/** C type : ClUint32T */
	public int tsMilliSec;
	public ClTimerTimeOutT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("tsSec", "tsMilliSec");
	}
	/**
	 * @param tsSec C type : ClUint32T<br>
	 * @param tsMilliSec C type : ClUint32T
	 */
	public ClTimerTimeOutT(int tsSec, int tsMilliSec) {
		super();
		this.tsSec = tsSec;
		this.tsMilliSec = tsMilliSec;
	}
	public ClTimerTimeOutT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClTimerTimeOutT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClTimerTimeOutT implements Structure.ByValue {
		
	};
}
