package clTimerApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clTimerApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClTimerConfigT extends Structure {
	/** C type : ClUint32T */
	public int timerResolution;
	/** C type : ClUint32T */
	public int timerTaskPriority;
	public ClTimerConfigT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("timerResolution", "timerTaskPriority");
	}
	/**
	 * @param timerResolution C type : ClUint32T<br>
	 * @param timerTaskPriority C type : ClUint32T
	 */
	public ClTimerConfigT(int timerResolution, int timerTaskPriority) {
		super();
		this.timerResolution = timerResolution;
		this.timerTaskPriority = timerTaskPriority;
	}
	public ClTimerConfigT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClTimerConfigT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClTimerConfigT implements Structure.ByValue {
		
	};
}
