package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsCSIAttributeListT extends Structure {
	/** C type : ClAmsCSIAttributeT* */
	public clAmfClient.ClAmsCSIAttributeT.ByReference attribute;
	/** C type : ClUint32T */
	public int numAttributes;
	public ClAmsCSIAttributeListT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("attribute", "numAttributes");
	}
	/**
	 * @param attribute C type : ClAmsCSIAttributeT*<br>
	 * @param numAttributes C type : ClUint32T
	 */
	public ClAmsCSIAttributeListT(clAmfClient.ClAmsCSIAttributeT.ByReference attribute, int numAttributes) {
		super();
		this.attribute = attribute;
		this.numAttributes = numAttributes;
	}
	public ClAmsCSIAttributeListT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsCSIAttributeListT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsCSIAttributeListT implements Structure.ByValue {
		
	};
}
