package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import clUtils.ClUtilsLibrary.*;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsCSITypeDescriptorT extends Structure {
	/** C type : ClAmsCSIDescriptorT */
	public ClAmsCSIDescriptorT csiDescriptor;
	public ClNameT csiType;
	public ClNameT compName;
	public ClAmsCSITypeDescriptorT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("csiDescriptor","csiType","compName");
	}
	/** @param csiDescriptor C type : ClAmsCSIDescriptorT */
	public ClAmsCSITypeDescriptorT(ClAmsCSIDescriptorT csiDescriptor, ClNameT csiType, ClNameT compName) {
		super();
		this.csiDescriptor = csiDescriptor;
		this.csiType = csiType;
		this.compName = compName;
	}
	public ClAmsCSITypeDescriptorT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsCSITypeDescriptorT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsCSITypeDescriptorT implements Structure.ByValue {
		
	};
}
