package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import clUtils.ClUtilsLibrary.*;

/**
 * <i>native declaration : clCpmExtApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClCorMOIdT extends Structure {
	
	public ClCorMOHandleT node[] = new ClCorMOHandleT[20]; // CL_COR_HANDLE_MAX_DEPTH = 20;
	
	public short svcId;
	
	public short depth;
	public int qualifier;
	public ClVersionT    version;
	
	public ClCorMOIdT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("node", "svcId", "depth","qualifier","version");
	}
	/**
	 * @param slotId C type : ClUint32T<br>
	 * @param nodeIocAddress C type : ClIocNodeAddressT<br>
	 * @param nodeMoId C type : ClCorMOIdT
	 */
	public ClCorMOIdT(ClCorMOHandleT[] node, short svcId, short depth, int qualifier,ClVersionT version) {
		super();
		this.node = node;
		this.svcId = svcId;
		this.depth = depth;
		this.qualifier = qualifier;
		this.version = version;
	}
	public ClCorMOIdT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClCorMOIdT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClCorMOIdT implements Structure.ByValue {
		
	};
}
