package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clCpmExtApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClCorMOHandleT extends Structure {
	/** C type : ClUint32T */
	public int type;	
	public int instance;
		
	public ClCorMOHandleT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "instance");
	}
	/**
	 * @param slotId C type : ClUint32T<br>
	 * @param nodeIocAddress C type : ClIocNodeAddressT<br>
	 * @param nodeMoId C type : ClCorMOIdT
	 */
	public ClCorMOHandleT(int type, int instance) {
		super();
		this.type = type;
		this.instance = instance;		
	}
	public ClCorMOHandleT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClCorMOHandleT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClCorMOHandleT implements Structure.ByValue {
		
	};
}
