package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import clUtils.ClUtilsLibrary.*;
/**
 * <i>native declaration : clCpmExtApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClCpmNodeConfigT extends Structure {
	/** C type : ClCharT[256] */
	public String nodeName;	
	public ClNameT nodeType;
	public ClNameT nodeIdentifier;
	public ClNameT nodeMoIdStr;	
	/** C type : ClCharT[256] */
	public String cpmType;
	public ClCpmNodeConfigT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("nodeName","nodeType","nodeIdentifier","nodeMoIdStr","cpmType");
	}
	/**
	 * @param nodeName C type : ClCharT[256]<br>
	 * @param cpmType C type : ClCharT[256]
	 */
	public ClCpmNodeConfigT(String nodeName, ClNameT nodeType, ClNameT nodeIdentifier, ClNameT nodeMoIdStr, String cpmType) {
		super();		
		this.nodeName = nodeName;
		this.nodeType = nodeType;
		this.nodeIdentifier = nodeIdentifier;
		this.nodeMoIdStr = nodeMoIdStr;
		this.cpmType = cpmType;
	}
	public ClCpmNodeConfigT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClCpmNodeConfigT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClCpmNodeConfigT implements Structure.ByValue {
		
	};
}
