package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clCpmApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClCpmCompCSI extends Structure {
	/**
	 * @see ClAmsHAStateT<br>
	 * C type : ClAmsHAStateT
	 */
	public int haState;
	/** C type : ClAmsCSIDescriptorT */
	public ClAmsCSIDescriptorT csiDescriptor;
	public ClCpmCompCSI() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("haState", "csiDescriptor");
	}
	/**
	 * @param haState @see ClAmsHAStateT<br>
	 * C type : ClAmsHAStateT<br>
	 * @param csiDescriptor C type : ClAmsCSIDescriptorT
	 */
	public ClCpmCompCSI(int haState, ClAmsCSIDescriptorT csiDescriptor) {
		super();
		this.haState = haState;
		this.csiDescriptor = csiDescriptor;
	}
	public ClCpmCompCSI(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClCpmCompCSI implements Structure.ByReference {
		
	};
	public static class ByValue extends ClCpmCompCSI implements Structure.ByValue {
		
	};
}
