package clAmfClient;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import clUtils.ClUtilsLibrary.*;
/**
 * <i>native declaration : clCpmApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClCpmEventNodePayLoadT extends Structure {
	public ClNameT nodeName;
	/** C type : ClIocNodeAddressT */
	public int nodeIocAddress;
	/**
	 * @see ClCpmNodeEventT<br>
	 * C type : ClCpmNodeEventT
	 */
	public int operation;
	public ClCpmEventNodePayLoadT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("nodeName","nodeIocAddress", "operation");
	}
	/**
	 * @param nodeIocAddress C type : ClIocNodeAddressT<br>
	 * @param operation @see ClCpmNodeEventT<br>
	 * C type : ClCpmNodeEventT
	 */
	public ClCpmEventNodePayLoadT(ClNameT nodeName,int nodeIocAddress, int operation) {
		super();
		this.nodeName = nodeName;
		this.nodeIocAddress = nodeIocAddress;
		this.operation = operation;
	}
	public ClCpmEventNodePayLoadT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClCpmEventNodePayLoadT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClCpmEventNodePayLoadT implements Structure.ByValue {
		
	};
}
