package clUtils;
import clUtils.ClLogFilterT.ByValue;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import com.sun.jna.ptr.ShortByReference;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.LongBuffer;
import java.nio.ShortBuffer;
import java.util.List;
import com.sun.jna.Structure;
import java.util.Arrays;
/**
 * JNA Wrapper for library <b>ClUtils</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ClUtilsLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ClUtils";
	public static final ClUtilsLibrary MW_INST = Native.load("mw", ClUtilsLibrary.class);	
	public static final NativeLibrary MW_NATIVE_LIB = NativeLibrary.getInstance("mw");
	//public static final NativeLibrary UTILS_NATIVE_LIB = NativeLibrary.getInstance(ClUtilsLibrary.JNA_LIBRARY_NAME);
	public static final ClUtilsLibrary UTILS_INSTANCE = (ClUtilsLibrary)Native.load(ClUtilsLibrary.JNA_LIBRARY_NAME, ClUtilsLibrary.class);	
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i><br>
	 * enum values
	 */
	public static interface ClLogStreamScopeT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:88</i> */
		public static final int CL_LOG_STREAM_GLOBAL = 0;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:92</i> */
		public static final int CL_LOG_STREAM_LOCAL = 1;
	};
	
	public static interface ClLogStreamOpenFlagsT {		
		public static final int CL_LOG_STREAM_CREATE = 1;		
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i><br>
	 * enum values
	 */
	public static interface ClLogFileFullActionT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:108</i> */
		public static final int CL_LOG_FILE_FULL_ACTION_ROTATE = 0;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:113</i> */
		public static final int CL_LOG_FILE_FULL_ACTION_WRAP = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:117</i> */
		public static final int CL_LOG_FILE_FULL_ACTION_HALT = 2;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i><br>
	 * enum values
	 */
	public static interface ClLogSeverityT {
		/**
		 * setting severity as EMERGENCY.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:253</i>
		 */
		public static final int CL_LOG_SEV_EMERGENCY = 0x1;
		/**
		 * setting severity as ALERT.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:257</i>
		 */
		public static final int CL_LOG_SEV_ALERT = (0x1 + 1);
		/**
		 * setting severity as CRITICAL.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:261</i>
		 */
		public static final int CL_LOG_SEV_CRITICAL = (0x1 + 2);
		/**
		 * setting severity as ERROR.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:265</i>
		 */
		public static final int CL_LOG_SEV_ERROR = (0x1 + 3);
		/**
		 * setting severity as WARNING.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:269</i>
		 */
		public static final int CL_LOG_SEV_WARNING = (0x1 + 4);
		/**
		 * setting severity as NOTICE.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:273</i>
		 */
		public static final int CL_LOG_SEV_NOTICE = (0x1 + 5);
		/**
		 * setting severity as INFORMATION.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:277</i>
		 */
		public static final int CL_LOG_SEV_INFO = (0x1 + 6);
		/**
		 * setting severity as DEBUG.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:281</i>
		 */
		public static final int CL_LOG_SEV_DEBUG = (0x1 + 7);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:282</i> */
		public static final int CL_LOG_SEV_DEBUG1 = (int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:283</i> */
		public static final int CL_LOG_SEV_DEBUG2 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG + 1);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:284</i> */
		public static final int CL_LOG_SEV_DEBUG3 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG + 2);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:285</i> */
		public static final int CL_LOG_SEV_DEBUG4 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG + 3);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:286</i> */
		public static final int CL_LOG_SEV_DEBUG5 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG + 4);
		/**
		 * setting severity as DEBUG.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:290</i>
		 */
		public static final int CL_LOG_SEV_TRACE = (int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG5;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:291</i> */
		public static final int CL_LOG_SEV_DEBUG6 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG5 + 1);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:292</i> */
		public static final int CL_LOG_SEV_DEBUG7 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG5 + 2);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:293</i> */
		public static final int CL_LOG_SEV_DEBUG8 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG5 + 3);
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:294</i> */
		public static final int CL_LOG_SEV_DEBUG9 = ((int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG5 + 4);
		/**
		 * Maximum severity level.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:298</i>
		 */
		public static final int CL_LOG_SEV_MAX = (int)ClUtilsLibrary.ClLogSeverityT.CL_LOG_SEV_DEBUG9;
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_STREAM_NAME_MAX_LENGTH = (int)128;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_SLINE_MSG_LEN = (int)256;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_STREAM_CREATE = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_HANDLER_WILL_ACK = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_FILTER_ASSIGN = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_FILTER_MERGE_ADD = (int)0x2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_FILTER_MERGE_DELETE = (int)0x3;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_MSGID_BUFFER = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_MSGID_PRINTF_FMT = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_TAG_TERMINATE = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_TAG_BASIC_SIGNED = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_TAG_BASIC_UNSIGNED = (int)0x2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final int CL_LOG_TAG_STRING = (int)0x3;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final String CL_LOG_PRNT_FMT_STR = (String)"%-26s [%s:%d] (%.*s.%d : %s.%3s.%3s";
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final String CL_LOG_PRNT_FMT_STR_CONSOLE = (String)"%-26s [%s:%d] (%.*s.%d : %s.%3s.%3s.%05d : %6s) ";
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final String CL_LOG_PRNT_FMT_STR_WO_FILE = (String)"%-26s (%.*s.%d : %s.%3s.%3s";
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public static final String CL_LOG_PRNT_FMT_STR_WO_FILE_CONSOLE = (String)"%-26s (%.*s.%d : %s.%3s.%3s.%05d : %6s) ";
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public interface ClLogStreamOpenCallbackT extends Callback {
		void apply(long invocation, long hStream, int rc);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public interface ClLogFilterSetCallbackT extends Callback {
		void apply(long hStream, ClLogFilterT.ByValue filter);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i> */
	public interface ClLogRecordDeliveryCallbackT extends Callback {
		void apply(long hStream, long seqNum, int numRecords, Pointer pRecords);
	};
	
	/**
	 * \brief Logging for applications<br>
	 *  \par Description<br>
	 *  This macro provides the support to log messages by specifying<br>
	 *  the severity of log message and server information like the <br>
	 *  sub-component area and the context of logging.<br>
	 *  \par<br>
	 *  This macro is for applications as well as system components to output log message<br>
	 *  into file sys.0 file. This is default log file which ASP components use.<br>
	 *  \param streamHandle (in) This handle should be a valid stream handle. It should be <br>
	 *   either default handles(CL_LOG_HANDLE_APP & CL_LOG_HANDLE_SYS) or should <br>
	 *  have obtained from previous clLogStreamOpen() call. The stream handle is CL_LOG_HANDLE_SYS,<br>
	 *  then it outputs to "sys.log". It is CL_LOG_HANDLE_APP, then it outputs to "app.log". <br>
	 * <br>
	 *  \param severity (in) This field must be set to one of the values defined <br>
	 *  in this file (CL_LOG_SEV_DEBUG ... CL_LOG_SEV_EMERGENCY).  It defines the <br>
	 *  severity level of the Log Record being written.<br>
	 *  \param libname (in) This is a character pointer specifiying the library name<br>
	 *  which is logging. <br>
	 *  \param msg (in) contains format string for the message.<br>
	 *  \param ... (in) use a printf style string and arguments for your log message.<br>
	 * Original signature : <code>ClRcT clLogWriteDeferred(ClHandleT, ClLogSeverityT, ClUint16T, ClUint16T, ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1716</i><br>
	 * @deprecated use the safer methods {@link #clLogWriteDeferred(long, int, short, short, java.nio.ByteBuffer, java.lang.Object)} and {@link #clLogWriteDeferred(long, int, short, short, com.sun.jna.Pointer, java.lang.Object)} instead
	 */
	@Deprecated 
	int clLogWriteDeferred(long handle, int severity, short servicId, short msgId, Pointer pFmtStr, Object... varArgs1);
	/**
	 * \brief Logging for applications<br>
	 *  \par Description<br>
	 *  This macro provides the support to log messages by specifying<br>
	 *  the severity of log message and server information like the <br>
	 *  sub-component area and the context of logging.<br>
	 *  \par<br>
	 *  This macro is for applications as well as system components to output log message<br>
	 *  into file sys.0 file. This is default log file which ASP components use.<br>
	 *  \param streamHandle (in) This handle should be a valid stream handle. It should be <br>
	 *   either default handles(CL_LOG_HANDLE_APP & CL_LOG_HANDLE_SYS) or should <br>
	 *  have obtained from previous clLogStreamOpen() call. The stream handle is CL_LOG_HANDLE_SYS,<br>
	 *  then it outputs to "sys.log". It is CL_LOG_HANDLE_APP, then it outputs to "app.log". <br>
	 * <br>
	 *  \param severity (in) This field must be set to one of the values defined <br>
	 *  in this file (CL_LOG_SEV_DEBUG ... CL_LOG_SEV_EMERGENCY).  It defines the <br>
	 *  severity level of the Log Record being written.<br>
	 *  \param libname (in) This is a character pointer specifiying the library name<br>
	 *  which is logging. <br>
	 *  \param msg (in) contains format string for the message.<br>
	 *  \param ... (in) use a printf style string and arguments for your log message.<br>
	 * Original signature : <code>ClRcT clLogWriteDeferred(ClHandleT, ClLogSeverityT, ClUint16T, ClUint16T, ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1716</i>
	 */
	int clLogWriteDeferred(long handle, int severity, short servicId, short msgId, String pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogWriteDeferredForce(ClHandleT, ClLogSeverityT, ClUint16T, ClUint16T, ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1724</i><br>
	 * @deprecated use the safer methods {@link #clLogWriteDeferredForce(long, int, short, short, java.nio.ByteBuffer, java.lang.Object)} and {@link #clLogWriteDeferredForce(long, int, short, short, com.sun.jna.Pointer, java.lang.Object)} instead
	 */
	@Deprecated 
	int clLogWriteDeferredForce(long handle, int severity, short servicId, short msgId, Pointer pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogWriteDeferredForce(ClHandleT, ClLogSeverityT, ClUint16T, ClUint16T, ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1724</i>
	 */
	int clLogWriteDeferredForce(long handle, int severity, short servicId, short msgId, String pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogMsgWrite(ClHandleT, ClLogSeverityT, ClUint16T, const ClCharT*, const ClCharT*, const ClCharT*, ClUint32T, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1732</i><br>
	 * @deprecated use the safer methods {@link #clLogMsgWrite(long, int, short, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.nio.ByteBuffer, java.lang.Object)} and {@link #clLogMsgWrite(long, int, short, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, int, com.sun.jna.Pointer, java.lang.Object)} instead
	 */
	@Deprecated 
	int clLogMsgWrite(long streamHdl, int severity, short serviceId, Pointer pArea, Pointer pContext, Pointer pFileName, int lineNum, Pointer pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogMsgWrite(ClHandleT, ClLogSeverityT, ClUint16T, const ClCharT*, const ClCharT*, const ClCharT*, ClUint32T, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1732</i>
	 */
	int clLogMsgWrite(long streamHdl, int severity, short serviceId, String pArea, String pContext, String pFileName, int lineNum, String pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogMsgWriteDeferred(ClHandleT, ClLogSeverityT, ClUint16T, const ClCharT*, const ClCharT*, const ClCharT*, ClUint32T, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1743</i><br>
	 * @deprecated use the safer methods {@link #clLogMsgWriteDeferred(long, int, short, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.nio.ByteBuffer, java.lang.Object)} and {@link #clLogMsgWriteDeferred(long, int, short, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, int, com.sun.jna.Pointer, java.lang.Object)} instead
	 */
	@Deprecated 
	int clLogMsgWriteDeferred(long streamHdl, int severity, short serviceId, Pointer pArea, Pointer pContext, Pointer pFileName, int lineNum, Pointer pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogMsgWriteDeferred(ClHandleT, ClLogSeverityT, ClUint16T, const ClCharT*, const ClCharT*, const ClCharT*, ClUint32T, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1743</i>
	 */
	int clLogMsgWriteDeferred(long streamHdl, int severity, short serviceId, String pArea, String pContext, String pFileName, int lineNum, String pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogMsgWriteConsole(ClHandleT, ClLogSeverityT, ClUint16T, const ClCharT*, const ClCharT*, const ClCharT*, ClUint32T, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1754</i><br>
	 * @deprecated use the safer methods {@link #clLogMsgWriteConsole(long, int, short, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.nio.ByteBuffer, java.lang.Object)} and {@link #clLogMsgWriteConsole(long, int, short, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, int, com.sun.jna.Pointer, java.lang.Object)} instead
	 */
	@Deprecated 
	int clLogMsgWriteConsole(long streamHdl, int severity, short serviceId, Pointer pArea, Pointer pContext, Pointer pFileName, int lineNum, Pointer pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClRcT clLogMsgWriteConsole(ClHandleT, ClLogSeverityT, ClUint16T, const ClCharT*, const ClCharT*, const ClCharT*, ClUint32T, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1754</i>
	 */
	int clLogMsgWriteConsole(long streamHdl, int severity, short serviceId, String pArea, String pContext, String pFileName, int lineNum, String pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClUint32T clLogFormatRecordHeader(ClCharT*, ClUint32T, ClCharT*, ClBoolT, ClUint32T, ClLogSeverityT, const ClCharT*, ClUint32T, const ClCharT*, const ClCharT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1764</i><br>
	 * @deprecated use the safer methods {@link #clLogFormatRecordHeader(java.nio.ByteBuffer, int, java.nio.ByteBuffer, short, int, int, java.nio.ByteBuffer, int, java.nio.ByteBuffer, java.nio.ByteBuffer)} and {@link #clLogFormatRecordHeader(com.sun.jna.Pointer, int, com.sun.jna.Pointer, short, int, int, com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int clLogFormatRecordHeader(Pointer msgHeader, int maxHeaderLen, Pointer msg, short consoleFlag, int msgIdCnt, int severity, Pointer pFileName, int lineNum, Pointer pArea, Pointer pContext);
	/**
	 * Original signature : <code>ClUint32T clLogFormatRecordHeader(ClCharT*, ClUint32T, ClCharT*, ClBoolT, ClUint32T, ClLogSeverityT, const ClCharT*, ClUint32T, const ClCharT*, const ClCharT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1764</i>
	 */
	int clLogFormatRecordHeader(ByteBuffer msgHeader, int maxHeaderLen, String msg, short consoleFlag, int msgIdCnt, int severity, String pFileName, int lineNum, String pArea, String pContext);
	/**
	 * Original signature : <code>ClUint32T clLogFormatRecord(ClCharT*, ClUint32T, ClCharT*, ClUint32T, ClBoolT, ClUint32T, ClLogSeverityT, const ClCharT*, ClUint32T, const ClCharT*, const ClCharT*, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1766</i><br>
	 * @deprecated use the safer methods {@link #clLogFormatRecord(java.nio.ByteBuffer, int, java.nio.ByteBuffer, int, short, int, int, java.nio.ByteBuffer, int, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, java.lang.Object)} and {@link #clLogFormatRecord(com.sun.jna.Pointer, int, com.sun.jna.Pointer, int, short, int, int, com.sun.jna.Pointer, int, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, java.lang.Object)} instead
	 */
	@Deprecated 
	int clLogFormatRecord(Pointer msgHeader, int maxHeaderLen, Pointer msg, int maxMsgLen, short consoleFlag, int msgIdCnt, int severity, Pointer pFileName, int lineNum, Pointer pArea, Pointer pContext, Pointer pFmtStr, Object... varArgs1);
	/**
	 * Original signature : <code>ClUint32T clLogFormatRecord(ClCharT*, ClUint32T, ClCharT*, ClUint32T, ClBoolT, ClUint32T, ClLogSeverityT, const ClCharT*, ClUint32T, const ClCharT*, const ClCharT*, const ClCharT*, null)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1766</i>
	 */
	int clLogFormatRecord(String msgHeader, int maxHeaderLen, String msg, int maxMsgLen, short consoleFlag, int msgIdCnt, int severity, String pFileName, int lineNum, String pArea, String pContext, String pFmtStr, Object... varArgs1);
	
	/**
	 * Original signature : <code>ClLogSeverityT clLogSeverityGet(const ClCharT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1784</i><br>
	 * @deprecated use the safer methods {@link #clLogSeverityGet(java.nio.ByteBuffer)} and {@link #clLogSeverityGet(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int clLogSeverityGet(Pointer pSevName);
	/**
	 * Original signature : <code>ClLogSeverityT clLogSeverityGet(const ClCharT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1784</i>
	 */
	int clLogSeverityGet(saAis.SaAisLibrary.SaNameT pSevName);
	/**
	 * Original signature : <code>ClRcT clLogTimeGet(ClCharT*, ClUint32T)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1787</i><br>
	 * @deprecated use the safer methods {@link #clLogTimeGet(java.nio.ByteBuffer, int)} and {@link #clLogTimeGet(com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	int clLogTimeGet(Pointer pStrTime, int maxBytes);
	/**
	 * Original signature : <code>ClRcT clLogTimeGet(ClCharT*, ClUint32T)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h:1787</i>
	 */
	int clLogTimeGet(String pStrTime, int maxBytes);
	/*public static class ClRcT extends PointerType {
		public ClRcT(Pointer address) {
			super(address);
		}
		public ClRcT() {
			super();
		}
	};*/
	
	public static class ClNameT extends Structure {
	  /** C type : SaUint16T */
	  public short length;
	  /** C type : SaUint8T[256] */
	  public byte[] value = new byte[256];
	  public ClNameT() {
		  super();
	  }
	  protected List<String> getFieldOrder() {
		  return Arrays.asList("length", "value");
	  }
	  /**
	   * @param length C type : SaUint16T<br>
	   * @param value C type : SaUint8T[256]
	   */
	  public ClNameT(short length, byte value[]) {
		  super();
		  this.length = length;
		  if ((value.length != this.length) || (this.length > this.value.length)) 
			  throw new IllegalArgumentException("Wrong array size !");
		  this.value = value;
	  }
	  public ClNameT(Pointer peer) {
		  super(peer);
	  }
	
	  public String toNameString()
	  {
	    if (length<=0)
	      return "";
	    return new String(value,0,length);
	  }
	
	  public static class ByReference extends ClNameT implements Structure.ByReference {
		
	  };
	  public static class ByValue extends ClNameT implements Structure.ByValue {
		
	  };
  };
  Pointer clHeapAllocate(int size);
  Pointer clHeapCalloc(int numChunks, int chunkSize);
  void clHeapFree(Pointer pAddress);
  
  void clNameSet(ClNameT.ByReference name, String str);
  
}
