package clCkptApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/clCkptApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClCkptCheckpointCreationAttributesT extends Structure {
	/**
	 * Create time attributes.<br>
	 * C type : ClCkptCreationFlagsT
	 */
	public int creationFlags;
	/**
	 * Total size of application data in a replica.<br>
	 * C type : ClSizeT
	 */
	public long checkpointSize;
	/**
	 * Checkpoint which is inactive (not opened anywhere) for this duration (in nanoseconds) is deleted.<br>
	 * C type : ClTimeT
	 */
	public long retentionDuration;
	/**
	 * Maximum sections for this checkpoint.<br>
	 * C type : ClUint32T
	 */
	public int maxSections;
	/**
	 * Maximum size of a section.<br>
	 * C type : ClSizeT
	 */
	public long maxSectionSize;
	/**
	 * Maximum length of the section identifier.<br>
	 * C type : ClSizeT
	 */
	public long maxSectionIdSize;
	public ClCkptCheckpointCreationAttributesT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("creationFlags", "checkpointSize", "retentionDuration", "maxSections", "maxSectionSize", "maxSectionIdSize");
	}
	/**
	 * @param creationFlags Create time attributes.<br>
	 * C type : ClCkptCreationFlagsT<br>
	 * @param checkpointSize Total size of application data in a replica.<br>
	 * C type : ClSizeT<br>
	 * @param retentionDuration Checkpoint which is inactive (not opened anywhere) for this duration (in nanoseconds) is deleted.<br>
	 * C type : ClTimeT<br>
	 * @param maxSections Maximum sections for this checkpoint.<br>
	 * C type : ClUint32T<br>
	 * @param maxSectionSize Maximum size of a section.<br>
	 * C type : ClSizeT<br>
	 * @param maxSectionIdSize Maximum length of the section identifier.<br>
	 * C type : ClSizeT
	 */
	public ClCkptCheckpointCreationAttributesT(int creationFlags, long checkpointSize, long retentionDuration, int maxSections, long maxSectionSize, long maxSectionIdSize) {
		super();
		this.creationFlags = creationFlags;
		this.checkpointSize = checkpointSize;
		this.retentionDuration = retentionDuration;
		this.maxSections = maxSections;
		this.maxSectionSize = maxSectionSize;
		this.maxSectionIdSize = maxSectionIdSize;
	}
	public ClCkptCheckpointCreationAttributesT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClCkptCheckpointCreationAttributesT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClCkptCheckpointCreationAttributesT implements Structure.ByValue {
		
	};
}
