package clAmsNotificationApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsClientNotification.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsNotificationInfoT extends Structure {
	/**
	 * @see ClAmsNotificationTypeT<br>
	 * C type : ClAmsNotificationTypeT
	 */
	public int type;
	/** C type : amsNotificationInfo_union */
	public amsNotificationInfo_union amsNotificationInfo = new amsNotificationInfo_union();
	/** <i>native declaration : clAmsClientNotification.h:66</i> */
	public static class amsNotificationInfo_union extends Union {
		/** C type : ClAmsNotificationDescriptorT */
		public ClAmsNotificationDescriptorT amsStateInfo;
		/** C type : ClCpmEventPayLoadT */
		public ClCpmEventPayLoadT amsCompInfo;
		/** C type : ClCpmEventNodePayLoadT */
		public ClCpmEventNodePayLoadT amsNodeInfo;
		/*public amsNotificationInfo_union() {
			super();
		}*/
		/** @param amsStateInfo C type : ClAmsNotificationDescriptorT */
		/*public amsNotificationInfo_union(ClAmsNotificationDescriptorT amsStateInfo) {
			super();
			this.amsStateInfo = amsStateInfo;
			setType(ClAmsNotificationDescriptorT.class);
		}*/
		/** @param amsCompInfo C type : ClCpmEventPayLoadT */
		/*public amsNotificationInfo_union(ClCpmEventPayLoadT amsCompInfo) {
			super();
			this.amsCompInfo = amsCompInfo;
			setType(ClCpmEventPayLoadT.class);
		}*/
		/** @param amsNodeInfo C type : ClCpmEventNodePayLoadT */
		/*public amsNotificationInfo_union(ClCpmEventNodePayLoadT amsNodeInfo) {
			super();
			this.amsNodeInfo = amsNodeInfo;
			setType(ClCpmEventNodePayLoadT.class);
		}
		public amsNotificationInfo_union(Pointer peer) {
			super(peer);
		}*/
		/*public static class ByReference extends amsNotificationInfo_union implements Structure.ByReference {
			
		};
		public static class ByValue extends amsNotificationInfo_union implements Structure.ByValue {
			
		};*/
	};
	public ClAmsNotificationInfoT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "amsNotificationInfo");
	}
	/**
	 * @param type @see ClAmsNotificationTypeT<br>
	 * C type : ClAmsNotificationTypeT<br>
	 * @param amsNotificationInfo C type : amsNotificationInfo_union
	 */
	public ClAmsNotificationInfoT(int type, amsNotificationInfo_union amsNotificationInfo) {
		super();
		this.type = type;
		this.amsNotificationInfo = amsNotificationInfo;
	}
	public ClAmsNotificationInfoT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsNotificationInfoT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsNotificationInfoT implements Structure.ByValue {
		
	};
}
