package clAmsNotificationApi;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>ClAmsMgmt</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ClAmsNotificationLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ClAmsMgmt";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ClAmsNotificationLibrary.JNA_LIBRARY_NAME);
	public static final ClAmsNotificationLibrary INSTANCE = (ClAmsNotificationLibrary)Native.load(ClAmsNotificationLibrary.JNA_LIBRARY_NAME, ClAmsNotificationLibrary.class);	
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsMgmtStateT {
		/** <i>native declaration : clAmsTypes.h:15</i> */
		public static final int CL_AMS_MGMT_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:16</i> */
		public static final int CL_AMS_MGMT_STATE_DISABLED = 1;
		/** <i>native declaration : clAmsTypes.h:17</i> */
		public static final int CL_AMS_MGMT_STATE_ENABLED = 2;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsAdminStateT {
		/** <i>native declaration : clAmsTypes.h:29</i> */
		public static final int CL_AMS_ADMIN_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:30</i> */
		public static final int CL_AMS_ADMIN_STATE_UNLOCKED = 1;
		/** <i>native declaration : clAmsTypes.h:31</i> */
		public static final int CL_AMS_ADMIN_STATE_LOCKED_A = 2;
		/** <i>native declaration : clAmsTypes.h:32</i> */
		public static final int CL_AMS_ADMIN_STATE_LOCKED_I = 3;
		/** <i>native declaration : clAmsTypes.h:33</i> */
		public static final int CL_AMS_ADMIN_STATE_SHUTTINGDOWN = 4;
		/** <i>native declaration : clAmsTypes.h:34</i> */
		public static final int CL_AMS_ADMIN_STATE_MAX = 5;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsPresenceStateT {
		/** <i>native declaration : clAmsTypes.h:45</i> */
		public static final int CL_AMS_PRESENCE_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:46</i> */
		public static final int CL_AMS_PRESENCE_STATE_UNINSTANTIATED = 1;
		/** <i>native declaration : clAmsTypes.h:47</i> */
		public static final int CL_AMS_PRESENCE_STATE_INSTANTIATING = 2;
		/** <i>native declaration : clAmsTypes.h:48</i> */
		public static final int CL_AMS_PRESENCE_STATE_INSTANTIATED = 3;
		/** <i>native declaration : clAmsTypes.h:49</i> */
		public static final int CL_AMS_PRESENCE_STATE_TERMINATING = 4;
		/** <i>native declaration : clAmsTypes.h:50</i> */
		public static final int CL_AMS_PRESENCE_STATE_RESTARTING = 5;
		/** <i>native declaration : clAmsTypes.h:51</i> */
		public static final int CL_AMS_PRESENCE_STATE_INSTANTIATION_FAILED = 6;
		/** <i>native declaration : clAmsTypes.h:52</i> */
		public static final int CL_AMS_PRESENCE_STATE_TERMINATION_FAILED = 7;
		/** <i>native declaration : clAmsTypes.h:56</i> */
		public static final int CL_AMS_PRESENCE_STATE_ABSENT = 0;
		/** <i>native declaration : clAmsTypes.h:57</i> */
		public static final int CL_AMS_PRESENCE_STATE_FAULT = 8;
		/** <i>native declaration : clAmsTypes.h:58</i> */
		public static final int CL_AMS_PRESENCE_STATE_FAULT_WTC = 9;
		/** <i>native declaration : clAmsTypes.h:59</i> */
		public static final int CL_AMS_PRESENCE_STATE_FAULT_WTR = 10;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsOperStateT {
		/** <i>native declaration : clAmsTypes.h:69</i> */
		public static final int CL_AMS_OPER_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:70</i> */
		public static final int CL_AMS_OPER_STATE_ENABLED = 1;
		/** <i>native declaration : clAmsTypes.h:71</i> */
		public static final int CL_AMS_OPER_STATE_DISABLED = 2;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsHAStateT {
		/** <i>native declaration : clAmsTypes.h:81</i> */
		public static final int CL_AMS_HA_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:82</i> */
		public static final int CL_AMS_HA_STATE_ACTIVE = 1;
		/** <i>native declaration : clAmsTypes.h:83</i> */
		public static final int CL_AMS_HA_STATE_STANDBY = 2;
		/** <i>native declaration : clAmsTypes.h:84</i> */
		public static final int CL_AMS_HA_STATE_QUIESCED = 3;
		/** <i>native declaration : clAmsTypes.h:85</i> */
		public static final int CL_AMS_HA_STATE_QUIESCING = 4;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsReadinessStateT {
		/** <i>native declaration : clAmsTypes.h:96</i> */
		public static final int CL_AMS_READINESS_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:97</i> */
		public static final int CL_AMS_READINESS_STATE_OUTOFSERVICE = 1;
		/** <i>native declaration : clAmsTypes.h:98</i> */
		public static final int CL_AMS_READINESS_STATE_INSERVICE = 2;
		/** <i>native declaration : clAmsTypes.h:99</i> */
		public static final int CL_AMS_READINESS_STATE_STOPPING = 3;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsServiceStateT {
		/** <i>native declaration : clAmsTypes.h:109</i> */
		public static final int CL_AMS_SERVICE_STATE_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:110</i> */
		public static final int CL_AMS_SERVICE_STATE_RUNNING = 1;
		/** <i>native declaration : clAmsTypes.h:111</i> */
		public static final int CL_AMS_SERVICE_STATE_STOPPED = 2;
		/** <i>native declaration : clAmsTypes.h:112</i> */
		public static final int CL_AMS_SERVICE_STATE_STARTINGUP = 3;
		/** <i>native declaration : clAmsTypes.h:113</i> */
		public static final int CL_AMS_SERVICE_STATE_SHUTTINGDOWN = 4;
		/** <i>native declaration : clAmsTypes.h:114</i> */
		public static final int CL_AMS_SERVICE_STATE_UNAVAILABLE = 5;
		/** <i>native declaration : clAmsTypes.h:115</i> */
		public static final int CL_AMS_SERVICE_STATE_HOT_STANDBY = 6;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsNodeClassT {
		/** <i>native declaration : clAmsTypes.h:129</i> */
		public static final int CL_AMS_NODE_CLASS_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:130</i> */
		public static final int CL_AMS_NODE_CLASS_A = 1;
		/** <i>native declaration : clAmsTypes.h:131</i> */
		public static final int CL_AMS_NODE_CLASS_B = 2;
		/** <i>native declaration : clAmsTypes.h:132</i> */
		public static final int CL_AMS_NODE_CLASS_C = 3;
		/** <i>native declaration : clAmsTypes.h:133</i> */
		public static final int CL_AMS_NODE_CLASS_D = 4;
		/** <i>native declaration : clAmsTypes.h:134</i> */
		public static final int CL_AMS_NODE_CLASS_MAX = 5;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsNodeClusterMemberT {
		/** <i>native declaration : clAmsTypes.h:143</i> */
		public static final int CL_AMS_NODE_IS_NOT_CLUSTER_MEMBER = 0;
		/** <i>native declaration : clAmsTypes.h:144</i> */
		public static final int CL_AMS_NODE_IS_CLUSTER_MEMBER = 1;
		/** <i>native declaration : clAmsTypes.h:145</i> */
		public static final int CL_AMS_NODE_IS_LEAVING_CLUSTER = 2;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsSGRedundancyModelT {
		/** <i>native declaration : clAmsTypes.h:164</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:165</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_NO_REDUNDANCY = 1;
		/** <i>native declaration : clAmsTypes.h:166</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_TWO_N = 2;
		/** <i>native declaration : clAmsTypes.h:167</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_M_PLUS_N = 3;
		/** <i>native declaration : clAmsTypes.h:168</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_N_WAY = 4;
		/** <i>native declaration : clAmsTypes.h:169</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_N_WAY_ACTIVE = 5;
		/**
		 * user controlled redundancy mode<br>
		 * <i>native declaration : clAmsTypes.h:170</i>
		 */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_CUSTOM = 6;
		/** <i>native declaration : clAmsTypes.h:171</i> */
		public static final int CL_AMS_SG_REDUNDANCY_MODEL_MAX = 7;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsSGLoadingStrategyT {
		/**
		 * invalid<br>
		 * <i>native declaration : clAmsTypes.h:219</i>
		 */
		public static final int CL_AMS_SG_LOADING_STRATEGY_NONE = 0;
		/**
		 * all models<br>
		 * <i>native declaration : clAmsTypes.h:220</i>
		 */
		public static final int CL_AMS_SG_LOADING_STRATEGY_LEAST_SI_PER_SU = 1;
		/**
		 * all models<br>
		 * <i>native declaration : clAmsTypes.h:221</i>
		 */
		public static final int CL_AMS_SG_LOADING_STRATEGY_LEAST_SU_ASSIGNED = 2;
		/**
		 * all models<br>
		 * <i>native declaration : clAmsTypes.h:222</i>
		 */
		public static final int CL_AMS_SG_LOADING_STRATEGY_LEAST_LOAD_PER_SU = 3;
		/**
		 * n-way-* only<br>
		 * <i>native declaration : clAmsTypes.h:223</i>
		 */
		public static final int CL_AMS_SG_LOADING_STRATEGY_BY_SI_PREFERENCE = 4;
		/**
		 * user-callout<br>
		 * <i>native declaration : clAmsTypes.h:224</i>
		 */
		public static final int CL_AMS_SG_LOADING_STRATEGY_USER_DEFINED = 5;
		/** <i>native declaration : clAmsTypes.h:225</i> */
		public static final int CL_AMS_SG_LOADING_STRATEGY_MAX = 6;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsCompCapModelT {
		/** <i>native declaration : clAmsTypes.h:239</i> */
		public static final int CL_AMS_COMP_CAP_X_ACTIVE_AND_Y_STANDBY = 1;
		/** <i>native declaration : clAmsTypes.h:240</i> */
		public static final int CL_AMS_COMP_CAP_X_ACTIVE_OR_Y_STANDBY = 2;
		/** <i>native declaration : clAmsTypes.h:241</i> */
		public static final int CL_AMS_COMP_CAP_ONE_ACTIVE_OR_X_STANDBY = 3;
		/** <i>native declaration : clAmsTypes.h:242</i> */
		public static final int CL_AMS_COMP_CAP_ONE_ACTIVE_OR_ONE_STANDBY = 4;
		/** <i>native declaration : clAmsTypes.h:243</i> */
		public static final int CL_AMS_COMP_CAP_X_ACTIVE = 5;
		/** <i>native declaration : clAmsTypes.h:244</i> */
		public static final int CL_AMS_COMP_CAP_ONE_ACTIVE = 6;
		/** <i>native declaration : clAmsTypes.h:245</i> */
		public static final int CL_AMS_COMP_CAP_NON_PREINSTANTIABLE = 7;
		/** <i>native declaration : clAmsTypes.h:246</i> */
		public static final int CL_AMS_COMP_CAP_MAX = 8;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsCompPropertyT {
		/** <i>native declaration : clAmsTypes.h:263</i> */
		public static final int CL_AMS_COMP_PROPERTY_SA_AWARE = 1;
		/** <i>native declaration : clAmsTypes.h:264</i> */
		public static final int CL_AMS_COMP_PROPERTY_PROXIED_PREINSTANTIABLE = 2;
		/** <i>native declaration : clAmsTypes.h:265</i> */
		public static final int CL_AMS_COMP_PROPERTY_PROXIED_NON_PREINSTANTIABLE = 3;
		/** <i>native declaration : clAmsTypes.h:266</i> */
		public static final int CL_AMS_COMP_PROPERTY_NON_PROXIED_NON_PREINSTANTIABLE = 4;
		/** <i>native declaration : clAmsTypes.h:267</i> */
		public static final int CL_AMS_COMP_PROPERTY_MAX = 5;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsCompHealthcheckInvocationT {
		/** <i>native declaration : clAmsTypes.h:276</i> */
		public static final int CL_AMS_COMP_HEALTHCHECK_AMF_INVOKED = 1;
		/** <i>native declaration : clAmsTypes.h:277</i> */
		public static final int CL_AMS_COMP_HEALTHCHECK_CLIENT_INVOKED = 2;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsRecoveryT {
		/** <i>native declaration : clAmsTypes.h:293</i> */
		public static final int CL_AMS_RECOVERY_NONE = 0;
		/** <i>native declaration : clAmsTypes.h:294</i> */
		public static final int CL_AMS_RECOVERY_NO_RECOMMENDATION = 1;
		/** <i>native declaration : clAmsTypes.h:295</i> */
		public static final int CL_AMS_RECOVERY_COMP_RESTART = 2;
		/** <i>native declaration : clAmsTypes.h:296</i> */
		public static final int CL_AMS_RECOVERY_COMP_FAILOVER = 3;
		/** <i>native declaration : clAmsTypes.h:297</i> */
		public static final int CL_AMS_RECOVERY_NODE_SWITCHOVER = 4;
		/** <i>native declaration : clAmsTypes.h:298</i> */
		public static final int CL_AMS_RECOVERY_NODE_FAILOVER = 5;
		/** <i>native declaration : clAmsTypes.h:299</i> */
		public static final int CL_AMS_RECOVERY_NODE_FAILFAST = 6;
		/** <i>native declaration : clAmsTypes.h:300</i> */
		public static final int CL_AMS_RECOVERY_CLUSTER_RESET = 7;
		/** <i>native declaration : clAmsTypes.h:301</i> */
		public static final int CL_AMS_RECOVERY_APP_RESTART = 8;
		/** <i>native declaration : clAmsTypes.h:307</i> */
		public static final int CL_AMS_RECOVERY_INTERNALLY_RECOVERED = 20;
		/** <i>native declaration : clAmsTypes.h:308</i> */
		public static final int CL_AMS_RECOVERY_SU_RESTART = 21;
		/** <i>native declaration : clAmsTypes.h:309</i> */
		public static final int CL_AMS_RECOVERY_NODE_HALT = 22;
		/** <i>native declaration : clAmsTypes.h:315</i> */
		public static final int CL_AMS_EXTERNAL_RECOVERY_RESET = 30;
		/** <i>native declaration : clAmsTypes.h:316</i> */
		public static final int CL_AMS_EXTERNAL_RECOVERY_REBOOT = 31;
		/** <i>native declaration : clAmsTypes.h:317</i> */
		public static final int CL_AMS_EXTERNAL_RECOVERY_POWER_ON = 32;
		/** <i>native declaration : clAmsTypes.h:318</i> */
		public static final int CL_AMS_EXTERNAL_RECOVERY_POWER_OFF = 33;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsCSITransitionDescriptorT {
		/** <i>native declaration : clAmsTypes.h:337</i> */
		public static final int CL_AMS_CSI_NEW_ASSIGN = 1;
		/** <i>native declaration : clAmsTypes.h:338</i> */
		public static final int CL_AMS_CSI_QUIESCED = 2;
		/** <i>native declaration : clAmsTypes.h:339</i> */
		public static final int CL_AMS_CSI_NOT_QUIESCED = 3;
		/** <i>native declaration : clAmsTypes.h:340</i> */
		public static final int CL_AMS_CSI_STILL_ACTIVE = 4;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsPGTrackFlagT {
		/** <i>native declaration : clAmsTypes.h:399</i> */
		public static final int CL_AMS_PG_TRACK_CURRENT = 1;
		/** <i>native declaration : clAmsTypes.h:400</i> */
		public static final int CL_AMS_PG_TRACK_CHANGES = 2;
		/** <i>native declaration : clAmsTypes.h:401</i> */
		public static final int CL_AMS_PG_TRACK_CHANGES_ONLY = 4;
	};
	/**
	 * <i>native declaration : clAmsTypes.h</i><br>
	 * enum values
	 */
	public static interface ClAmsPGChangeT {
		/** <i>native declaration : clAmsTypes.h:406</i> */
		public static final int CL_AMS_PG_NO_CHANGE = 1;
		/** <i>native declaration : clAmsTypes.h:407</i> */
		public static final int CL_AMS_PG_ADDED = 2;
		/** <i>native declaration : clAmsTypes.h:408</i> */
		public static final int CL_AMS_PG_REMOVED = 3;
		/** <i>native declaration : clAmsTypes.h:409</i> */
		public static final int CL_AMS_PG_STATE_CHANGE = 4;
	};
	/**
	 * <i>native declaration : clCpmApi.h</i><br>
	 * enum values
	 */
	public static interface ClCpmNodeEventT {
		/** <i>native declaration : clCpmApi.h:164</i> */
		public static final int CL_CPM_NODE_ARRIVAL = 0;
		/** <i>native declaration : clCpmApi.h:169</i> */
		public static final int CL_CPM_NODE_DEPARTURE = 1;
		/** <i>native declaration : clCpmApi.h:174</i> */
		public static final int CL_CPM_NODE_DEATH = 2;
	};
	/**
	 * <i>native declaration : clCpmApi.h</i><br>
	 * enum values
	 */
	public static interface ClCpmCompEventT {
		/** <i>native declaration : clCpmApi.h:187</i> */
		public static final int CL_CPM_COMP_ARRIVAL = 0;
		/** <i>native declaration : clCpmApi.h:191</i> */
		public static final int CL_CPM_COMP_DEPARTURE = 1;
		/** <i>native declaration : clCpmApi.h:196</i> */
		public static final int CL_CPM_COMP_DEATH = 2;
	};
	/**
	 * <i>native declaration : clAmsEntities.h</i><br>
	 * enum values
	 */
	public static interface ClAmsEntityTypeT {
		/**
		 * < unused<br>
		 * <i>native declaration : clAmsEntities.h:23</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_ENTITY = 0;
		/**
		 * < A Cluster Node (system,computer)<br>
		 * <i>native declaration : clAmsEntities.h:24</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_NODE = 1;
		/**
		 * < A SAF application<br>
		 * <i>native declaration : clAmsEntities.h:25</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_APP = 2;
		/**
		 * < A SAF service group<br>
		 * <i>native declaration : clAmsEntities.h:26</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_SG = 3;
		/**
		 * < A SAF service unit<br>
		 * <i>native declaration : clAmsEntities.h:27</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_SU = 4;
		/**
		 * < A SAF service instance (work assignment)<br>
		 * <i>native declaration : clAmsEntities.h:28</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_SI = 5;
		/**
		 * < A SAF component (program)<br>
		 * <i>native declaration : clAmsEntities.h:29</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_COMP = 6;
		/**
		 * < A SAF component service instance (work assigned to a particular program)<br>
		 * <i>native declaration : clAmsEntities.h:30</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_CSI = 7;
		/**
		 * < A cluster<br>
		 * <i>native declaration : clAmsEntities.h:31</i>
		 */
		public static final int CL_AMS_ENTITY_TYPE_CLUSTER = 8;
	};
	/**
	 * <i>native declaration : clAmsEntities.h</i><br>
	 * enum values
	 */
	public static interface ClAmsEntityTimerTypeT {
		/** <i>native declaration : clAmsEntities.h:149</i> */
		public static final int CL_AMS_NODE_TIMER_SUFAILOVER = 1;
		/** <i>native declaration : clAmsEntities.h:151</i> */
		public static final int CL_AMS_SG_TIMER_INSTANTIATE = 10;
		/** <i>native declaration : clAmsEntities.h:152</i> */
		public static final int CL_AMS_SG_TIMER_ADJUST = 11;
		/** <i>native declaration : clAmsEntities.h:153</i> */
		public static final int CL_AMS_SG_TIMER_ADJUST_PROBATION = 12;
		/** <i>native declaration : clAmsEntities.h:154</i> */
		public static final int CL_AMS_SU_TIMER_COMPRESTART = 20;
		/** <i>native declaration : clAmsEntities.h:155</i> */
		public static final int CL_AMS_SU_TIMER_SURESTART = 21;
		/** <i>native declaration : clAmsEntities.h:156</i> */
		public static final int CL_AMS_SU_TIMER_PROBATION = 22;
		/** <i>native declaration : clAmsEntities.h:157</i> */
		public static final int CL_AMS_SU_TIMER_ASSIGNMENT = 23;
		/** <i>native declaration : clAmsEntities.h:159</i> */
		public static final int CL_AMS_COMP_TIMER_INSTANTIATE = 40;
		/** <i>native declaration : clAmsEntities.h:160</i> */
		public static final int CL_AMS_COMP_TIMER_TERMINATE = 41;
		/** <i>native declaration : clAmsEntities.h:161</i> */
		public static final int CL_AMS_COMP_TIMER_CLEANUP = 42;
		/** <i>native declaration : clAmsEntities.h:162</i> */
		public static final int CL_AMS_COMP_TIMER_AMSTART = 43;
		/** <i>native declaration : clAmsEntities.h:163</i> */
		public static final int CL_AMS_COMP_TIMER_AMSTOP = 44;
		/** <i>native declaration : clAmsEntities.h:164</i> */
		public static final int CL_AMS_COMP_TIMER_QUIESCINGCOMPLETE = 45;
		/** <i>native declaration : clAmsEntities.h:165</i> */
		public static final int CL_AMS_COMP_TIMER_CSISET = 46;
		/** <i>native declaration : clAmsEntities.h:166</i> */
		public static final int CL_AMS_COMP_TIMER_CSIREMOVE = 47;
		/** <i>native declaration : clAmsEntities.h:167</i> */
		public static final int CL_AMS_COMP_TIMER_PROXIEDCOMPINSTANTIATE = 48;
		/** <i>native declaration : clAmsEntities.h:168</i> */
		public static final int CL_AMS_COMP_TIMER_PROXIEDCOMPCLEANUP = 49;
		/** <i>native declaration : clAmsEntities.h:169</i> */
		public static final int CL_AMS_COMP_TIMER_INSTANTIATEDELAY = 50;
		/** <i>native declaration : clAmsEntities.h:170</i> */
		public static final int CL_AMS_COMP_TIMER_MAX = 51;
	};
	/**
	 * <i>native declaration : clAmsEntities.h</i><br>
	 * enum values
	 */
	public static interface ClAmsEntityRefTypeT {
		/** <i>native declaration : clAmsEntities.h:200</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_ENTITY = 0;
		/** <i>native declaration : clAmsEntities.h:201</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_NODE = 1;
		/** <i>native declaration : clAmsEntities.h:202</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_APP = 2;
		/** <i>native declaration : clAmsEntities.h:203</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_SG = 3;
		/** <i>native declaration : clAmsEntities.h:204</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_SU = 4;
		/** <i>native declaration : clAmsEntities.h:205</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_SI = 5;
		/** <i>native declaration : clAmsEntities.h:206</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_COMP = 6;
		/** <i>native declaration : clAmsEntities.h:207</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_CSI = 7;
		/** <i>native declaration : clAmsEntities.h:208</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_SUSI = 8;
		/** <i>native declaration : clAmsEntities.h:209</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_SISU = 9;
		/** <i>native declaration : clAmsEntities.h:210</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_COMPCSI = 10;
		/** <i>native declaration : clAmsEntities.h:211</i> */
		public static final int CL_AMS_ENTITY_REF_TYPE_CSICOMP = 11;
	};
	/**
	 * <i>native declaration : clAmsEntities.h</i><br>
	 * enum values
	 */
	public static interface ClAmsEntityListTypeT {
		/** <i>native declaration : clAmsEntities.h:236</i> */
		public static final int CL_AMS_START_LIST = 0;
		/** <i>native declaration : clAmsEntities.h:241</i> */
		public static final int CL_AMS_CONFIG_LIST_START = 1;
		/** <i>native declaration : clAmsEntities.h:242</i> */
		public static final int CL_AMS_NODE_CONFIG_NODE_DEPENDENT_LIST = 2;
		/** <i>native declaration : clAmsEntities.h:243</i> */
		public static final int CL_AMS_NODE_CONFIG_NODE_DEPENDENCIES_LIST = 3;
		/** <i>native declaration : clAmsEntities.h:244</i> */
		public static final int CL_AMS_NODE_CONFIG_SU_LIST = 4;
		/** <i>native declaration : clAmsEntities.h:245</i> */
		public static final int CL_AMS_SG_CONFIG_SU_LIST = 5;
		/** <i>native declaration : clAmsEntities.h:246</i> */
		public static final int CL_AMS_SG_CONFIG_SI_LIST = 6;
		/** <i>native declaration : clAmsEntities.h:247</i> */
		public static final int CL_AMS_SU_CONFIG_COMP_LIST = 7;
		/** <i>native declaration : clAmsEntities.h:248</i> */
		public static final int CL_AMS_SI_CONFIG_SU_RANK_LIST = 8;
		/** <i>native declaration : clAmsEntities.h:249</i> */
		public static final int CL_AMS_SI_CONFIG_SI_DEPENDENTS_LIST = 9;
		/** <i>native declaration : clAmsEntities.h:250</i> */
		public static final int CL_AMS_SI_CONFIG_SI_DEPENDENCIES_LIST = 10;
		/** <i>native declaration : clAmsEntities.h:251</i> */
		public static final int CL_AMS_SI_CONFIG_CSI_LIST = 11;
		/** <i>native declaration : clAmsEntities.h:252</i> */
		public static final int CL_AMS_CSI_CONFIG_NVP_LIST = 12;
		/** <i>native declaration : clAmsEntities.h:253</i> */
		public static final int CL_AMS_CSI_CONFIG_CSI_DEPENDENTS_LIST = 13;
		/** <i>native declaration : clAmsEntities.h:254</i> */
		public static final int CL_AMS_CSI_CONFIG_CSI_DEPENDENCIES_LIST = 14;
		/** <i>native declaration : clAmsEntities.h:255</i> */
		public static final int CL_AMS_CONFIG_LIST_END = 15;
		/** <i>native declaration : clAmsEntities.h:260</i> */
		public static final int CL_AMS_SG_STATUS_INSTANTIABLE_SU_LIST = 16;
		/** <i>native declaration : clAmsEntities.h:261</i> */
		public static final int CL_AMS_SG_STATUS_INSTANTIATED_SU_LIST = 17;
		/** <i>native declaration : clAmsEntities.h:262</i> */
		public static final int CL_AMS_SG_STATUS_IN_SERVICE_SPARE_SU_LIST = 18;
		/** <i>native declaration : clAmsEntities.h:263</i> */
		public static final int CL_AMS_SG_STATUS_ASSIGNED_SU_LIST = 19;
		/** <i>native declaration : clAmsEntities.h:264</i> */
		public static final int CL_AMS_SG_STATUS_FAULTY_SU_LIST = 20;
		/** <i>native declaration : clAmsEntities.h:265</i> */
		public static final int CL_AMS_SU_STATUS_SI_LIST = 21;
		/** <i>native declaration : clAmsEntities.h:266</i> */
		public static final int CL_AMS_SI_STATUS_SU_LIST = 22;
		/** <i>native declaration : clAmsEntities.h:267</i> */
		public static final int CL_AMS_COMP_STATUS_CSI_LIST = 23;
		/** <i>native declaration : clAmsEntities.h:268</i> */
		public static final int CL_AMS_CSI_STATUS_PG_LIST = 24;
		/** <i>native declaration : clAmsEntities.h:273</i> */
		public static final int CL_AMS_ENTITY_LIST_ALL_START = 25;
		/** <i>native declaration : clAmsEntities.h:275</i> */
		public static final int CL_AMS_SG_LIST = 26;
		/** <i>native declaration : clAmsEntities.h:276</i> */
		public static final int CL_AMS_SI_LIST = 27;
		/** <i>native declaration : clAmsEntities.h:277</i> */
		public static final int CL_AMS_NODE_LIST = 28;
		/** <i>native declaration : clAmsEntities.h:278</i> */
		public static final int CL_AMS_SU_LIST = 29;
		/** <i>native declaration : clAmsEntities.h:279</i> */
		public static final int CL_AMS_COMP_LIST = 30;
		/** <i>native declaration : clAmsEntities.h:280</i> */
		public static final int CL_AMS_CSI_LIST = 31;
		/** <i>native declaration : clAmsEntities.h:284</i> */
		public static final int CL_AMS_ENTITY_LIST_ALL_END = 32;
		/** <i>native declaration : clAmsEntities.h:287</i> */
		public static final int CL_AMS_CSI_PGTRACK_CLIENT_LIST = 33;
		/** <i>native declaration : clAmsEntities.h:289</i> */
		public static final int CL_AMS_SU_STATUS_SI_EXTENDED_LIST = 34;
		/** <i>native declaration : clAmsEntities.h:291</i> */
		public static final int CL_AMS_SI_STATUS_SU_EXTENDED_LIST = 35;
		/** <i>native declaration : clAmsEntities.h:293</i> */
		public static final int CL_AMS_END_LIST = 36;
	};	
	/**
	 * <i>native declaration : clAmsClientNotification.h</i><br>
	 * enum values
	 */
	public static interface ClAmsNotificationTypeT {
		/** <i>native declaration : clAmsClientNotification.h:24</i> */
		public static final int CL_AMS_NOTIFICATION_NONE = 0;
		/** <i>native declaration : clAmsClientNotification.h:25</i> */
		public static final int CL_AMS_NOTIFICATION_FAULT = 1;
		/** <i>native declaration : clAmsClientNotification.h:26</i> */
		public static final int CL_AMS_NOTIFICATION_SU_INSTANTIATION_FAILURE = 2;
		/** <i>native declaration : clAmsClientNotification.h:27</i> */
		public static final int CL_AMS_NOTIFICATION_SU_HA_STATE_CHANGE = 3;
		/** <i>native declaration : clAmsClientNotification.h:28</i> */
		public static final int CL_AMS_NOTIFICATION_SI_FULLY_ASSIGNED = 4;
		/** <i>native declaration : clAmsClientNotification.h:29</i> */
		public static final int CL_AMS_NOTIFICATION_SI_PARTIALLY_ASSIGNED = 5;
		/** <i>native declaration : clAmsClientNotification.h:30</i> */
		public static final int CL_AMS_NOTIFICATION_SI_UNASSIGNED = 6;
		/** <i>native declaration : clAmsClientNotification.h:31</i> */
		public static final int CL_AMS_NOTIFICATION_COMP_ARRIVAL = 7;
		/** <i>native declaration : clAmsClientNotification.h:32</i> */
		public static final int CL_AMS_NOTIFICATION_COMP_DEPARTURE = 8;
		/** <i>native declaration : clAmsClientNotification.h:33</i> */
		public static final int CL_AMS_NOTIFICATION_NODE_ARRIVAL = 9;
		/** <i>native declaration : clAmsClientNotification.h:34</i> */
		public static final int CL_AMS_NOTIFICATION_NODE_DEPARTURE = 10;
		/** <i>native declaration : clAmsClientNotification.h:35</i> */
		public static final int CL_AMS_NOTIFICATION_ENTITY_CREATE = 11;
		/** <i>native declaration : clAmsClientNotification.h:36</i> */
		public static final int CL_AMS_NOTIFICATION_ENTITY_DELETE = 12;
		/** <i>native declaration : clAmsClientNotification.h:37</i> */
		public static final int CL_AMS_NOTIFICATION_OPER_STATE_CHANGE = 13;
		/** <i>native declaration : clAmsClientNotification.h:38</i> */
		public static final int CL_AMS_NOTIFICATION_ADMIN_STATE_CHANGE = 14;
		/** <i>native declaration : clAmsClientNotification.h:39</i> */
		public static final int CL_AMS_NOTIFICATION_NODE_SWITCHOVER = 15;
		/** <i>native declaration : clAmsClientNotification.h:40</i> */
		public static final int CL_AMS_NOTIFICATION_NODE_FAILOVER = 16;
		/** <i>native declaration : clAmsClientNotification.h:41</i> */
		public static final int CL_AMS_NOTIFICATION_COMP_HA_STATE_CHANGE = 17;
		/** <i>native declaration : clAmsClientNotification.h:42</i> */
		public static final int CL_AMS_NOTIFICATION_MAX = 18;
	};	
	
	/**
	 * \brief Component Manager requests the component, identified by \e<br>
	 * compName, to execute healthcheck using \e healthcheckkey<br>
	 * [Asynchronous Call].<br>
	 * * \param invocation Particular invocation of this callback function.<br>
	 * * \param pCompName Pointer to the name of the component that must<br>
	 * undergo healthcheck.<br>
	 * * \param pHealthCheckKey Key to fetch the healthcheck related<br>
	 * attributes.<br>
	 * <i>native declaration : clCpmApi.h:326</i>
	 */	
	public interface ClAmsClientNotificationCallbackT extends Callback {
	  int apply(ClAmsNotificationInfoT.ByReference info);
	};	 
	
	/**
	 * Original signature : <code>ClRcT clAmsClientNotificationInitialize(ClAmsClientNotificationCallbackT)</code><br>
	 * <i>native declaration : clAmsClientNotification.h:81</i>
	 */
	int clAmsClientNotificationInitialize(ClAmsClientNotificationCallbackT callback);
	/**
	 * Original signature : <code>ClRcT clAmsClientNotificationFinalize()</code><br>
	 * <i>native declaration : clAmsClientNotification.h:83</i>
	 */
	int clAmsClientNotificationFinalize();
	/**
	 * Original signature : <code>ClRcT clAmsNotificationEventPayloadExtract(ClEventHandleT, ClSizeT, void*)</code><br>
	 * <i>native declaration : clAmsClientNotification.h:85</i>
	 */
	int clAmsNotificationEventPayloadExtract(long eventHandle, long eventDataSize, Pointer payLoad);	
}
