package saAmf;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
//import saamf.SaAmfLibrary.SaUint32T;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaAmfCSIAttributeListT extends Structure {
	/** C type : SaAmfCSIAttributeT* */
	//public saAmf.SaAmfCSIAttributeT.ByReference attr;
	public Pointer attr;
	//public Pointer attr;
	/** C type : SaUint32T */
	public int number;
	public SaAmfCSIAttributeListT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("attr", "number");
	}
	/**
	 * @param attr C type : SaAmfCSIAttributeT*<br>
	 * @param number C type : SaUint32T
	 */
	public SaAmfCSIAttributeListT(Pointer attr, int number) {
		super();
		this.attr = attr;
		this.number = number;
	}
	public SaAmfCSIAttributeListT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaAmfCSIAttributeListT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaAmfCSIAttributeListT implements Structure.ByValue {
		
	};
}
