package saAmf;
import com.sun.jna.Pointer;
import com.sun.jna.Union;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaAmfCSIStateDescriptorT extends Union {
	/** C type : SaAmfCSIActiveDescriptorT */
	public SaAmfCSIActiveDescriptorT activeDescriptor;
	/** C type : SaAmfCSIStandbyDescriptorT */
	public SaAmfCSIStandbyDescriptorT standbyDescriptor;
	public SaAmfCSIStateDescriptorT() {
		super();
	}
	/** @param activeDescriptor C type : SaAmfCSIActiveDescriptorT */
	public SaAmfCSIStateDescriptorT(SaAmfCSIActiveDescriptorT activeDescriptor) {
		super();
		this.activeDescriptor = activeDescriptor;
		setType(SaAmfCSIActiveDescriptorT.class);
	}
	/** @param standbyDescriptor C type : SaAmfCSIStandbyDescriptorT */
	public SaAmfCSIStateDescriptorT(SaAmfCSIStandbyDescriptorT standbyDescriptor) {
		super();
		this.standbyDescriptor = standbyDescriptor;
		setType(SaAmfCSIStandbyDescriptorT.class);
	}
	public SaAmfCSIStateDescriptorT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaAmfCSIStateDescriptorT implements com.sun.jna.Structure.ByReference {
		
	};
	public static class ByValue extends SaAmfCSIStateDescriptorT implements com.sun.jna.Structure.ByValue {
		
	};
}
