package saAmf;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
//import saamf.SaAmfLibrary.SaAmfCSIFlagsT;
import saAis.SaAisLibrary.SaNameT;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaAmfCSIDescriptorT extends Structure {
	/** C type : SaAmfCSIFlagsT */
	public int csiFlags;
	/** C type : SaNameT */
	public SaNameT csiName;
	/** C type : SaAmfCSIStateDescriptorT */
	public SaAmfCSIStateDescriptorT csiStateDescriptor;
	/** C type : SaAmfCSIAttributeListT */
	public SaAmfCSIAttributeListT csiAttr;
	public SaAmfCSIDescriptorT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("csiFlags", "csiName", "csiStateDescriptor", "csiAttr");
	}
	/**
	 * @param csiFlags C type : SaAmfCSIFlagsT<br>
	 * @param csiName C type : SaNameT<br>
	 * @param csiStateDescriptor C type : SaAmfCSIStateDescriptorT<br>
	 * @param csiAttr C type : SaAmfCSIAttributeListT
	 */
	public SaAmfCSIDescriptorT(int csiFlags, SaNameT csiName, SaAmfCSIStateDescriptorT csiStateDescriptor, SaAmfCSIAttributeListT csiAttr) {
		super();
		this.csiFlags = csiFlags;
		this.csiName = csiName;
		this.csiStateDescriptor = csiStateDescriptor;
		this.csiAttr = csiAttr;
	}
	public SaAmfCSIDescriptorT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaAmfCSIDescriptorT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaAmfCSIDescriptorT implements Structure.ByValue {
		
	};
}
