package saAmf;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import saAis.SaAisLibrary.SaNameT;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaAmfCSIActiveDescriptorT extends Structure {
	/**
	 * @see SaAmfCSITransitionDescriptorT<br>
	 * C type : SaAmfCSITransitionDescriptorT
	 */
	public int transitionDescriptor;
	/** C type : SaNameT */
	public SaNameT activeCompName;
	public SaAmfCSIActiveDescriptorT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("transitionDescriptor", "activeCompName");
	}
	/**
	 * @param transitionDescriptor @see SaAmfCSITransitionDescriptorT<br>
	 * C type : SaAmfCSITransitionDescriptorT<br>
	 * @param activeCompName C type : SaNameT
	 */
	public SaAmfCSIActiveDescriptorT(int transitionDescriptor, SaNameT activeCompName) {
		super();
		this.transitionDescriptor = transitionDescriptor;
		this.activeCompName = activeCompName;
	}
	public SaAmfCSIActiveDescriptorT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaAmfCSIActiveDescriptorT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaAmfCSIActiveDescriptorT implements Structure.ByValue {
		
	};
}
