package saAmf;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
//import saamf.SaAmfLibrary.SaUint8T;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaAmfCSIAttributeT extends Structure {
	/** C type : SaUint8T* */
	public byte[] attrName = new byte[256];
	/** C type : SaUint8T* */
	public byte[] attrValue = new byte[256];
	public SaAmfCSIAttributeT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("attrName", "attrValue");
	}
	/**
	 * @param attrName C type : SaUint8T*<br>
	 * @param attrValue C type : SaUint8T*
	 */
	public SaAmfCSIAttributeT(byte[] attrName, byte[] attrValue) {
		super();
		this.attrName = attrName;
		this.attrValue = attrValue;
	}
	public SaAmfCSIAttributeT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaAmfCSIAttributeT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaAmfCSIAttributeT implements Structure.ByValue {
		
	};
}
