package saAmf;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaAmfProtectionGroupNotificationBufferT extends Structure {
	/** C type : SaUint32T */
	public int numberOfItems;
	/** C type : SaAmfProtectionGroupNotificationT* */
	public saAmf.SaAmfProtectionGroupNotificationT.ByReference notification;
	public SaAmfProtectionGroupNotificationBufferT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("numberOfItems", "notification");
	}
	/**
	 * @param numberOfItems C type : SaUint32T<br>
	 * @param notification C type : SaAmfProtectionGroupNotificationT*
	 */
	public SaAmfProtectionGroupNotificationBufferT(int numberOfItems, saAmf.SaAmfProtectionGroupNotificationT.ByReference notification) {
		super();
		this.numberOfItems = numberOfItems;
		this.notification = notification;
	}
	public SaAmfProtectionGroupNotificationBufferT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaAmfProtectionGroupNotificationBufferT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaAmfProtectionGroupNotificationBufferT implements Structure.ByValue {
		
	};
}
