package saAmf;
import com.sun.jna.Callback;
//import com.sun.jna.*;
//import com.sun.jna.Library;
//import com.sun.jna.Native;
//import com.sun.jna.NativeLibrary;
//import com.sun.jna.NativeLibraryOptions;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import com.sun.jna.ptr.PointerByReference;
import java.nio.IntBuffer;
import saAmf.SaAmfCSIDescriptorT.ByValue;
import saAis.SaAisLibrary.*;
/**
 * JNA Wrapper for library <b>saAmf</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */

public interface SaAmfLibrary extends Library {
  public static final String JNA_LIBRARY_NAME = "ClAmfClient";
  /*NativeLibrary libAmfClient = NativeLibrary.getInstance(
            JNA_LIBRARY_NAME,
            NativeLibraryOptions.builder()
                .openFlags(Library.OPTION_OPEN_FLAG_RTLD_GLOBAL | Library.OPTION_OPEN_FLAG_RTLD_NOW)
                .build()
        );*/
	
	//public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SaAmfLibrary.JNA_LIBRARY_NAME);
	//public static final SaAmfLibrary UTILS_INST = Native.load("ClUtils", SaAmfLibrary.class);
	public static final SaAmfLibrary MW_INST = Native.load("mw", SaAmfLibrary.class);
	public static final SaAmfLibrary INSTANCE = Native.load(SaAmfLibrary.JNA_LIBRARY_NAME, SaAmfLibrary.class);

	//public static final SaAmfLibrary UTILS_INSTANCE = Native.load("ClUtils", SaAmfLibrary.class);


	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
	 * enum values
	 */
	public static interface SaAmfPmStopQualifierT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:11</i> */
		public static final int SA_AMF_PM_PROC = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:12</i> */
		public static final int SA_AMF_PM_PROC_AND_DESCENDENTS = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:13</i> */
		public static final int SA_AMF_PM_ALL_PROCESSES = 3;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
	 * enum values
	 */
	public static interface SaAmfHealthcheckInvocationT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:17</i> */
		public static final int SA_AMF_HEALTHCHECK_AMF_INVOKED = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:18</i> */
		public static final int SA_AMF_HEALTHCHECK_COMPONENT_INVOKED = 2;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
	 * enum values
	 */
	public static interface SaAmfHAStateT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:29</i> */
		public static final int SA_AMF_HA_ACTIVE = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:30</i> */
		public static final int SA_AMF_HA_STANDBY = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:31</i> */
		public static final int SA_AMF_HA_QUIESCED = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:32</i> */
		public static final int SA_AMF_HA_QUIESCING = 4;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
	 * enum values
	 */
	public static interface SaAmfCSITransitionDescriptorT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:42</i> */
		public static final int SA_AMF_CSI_NEW_ASSIGN = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:43</i> */
		public static final int SA_AMF_CSI_QUIESCED = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:44</i> */
		public static final int SA_AMF_CSI_NOT_QUIESCED = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:45</i> */
		public static final int SA_AMF_CSI_STILL_ACTIVE = 4;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
	 * enum values
	 */
	public static interface SaAmfProtectionGroupChangesT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:87</i> */
		public static final int SA_AMF_PROTECTION_GROUP_NO_CHANGE = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:88</i> */
		public static final int SA_AMF_PROTECTION_GROUP_ADDED = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:89</i> */
		public static final int SA_AMF_PROTECTION_GROUP_REMOVED = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:90</i> */
		public static final int SA_AMF_PROTECTION_GROUP_STATE_CHANGE = 4;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i><br>
	 * enum values
	 */
	public static interface SaAmfRecommendedRecoveryT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:104</i> */
		public static final int SA_AMF_NO_RECOMMENDATION = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:105</i> */
		public static final int SA_AMF_COMPONENT_RESTART = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:106</i> */
		public static final int SA_AMF_COMPONENT_FAILOVER = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:107</i> */
		public static final int SA_AMF_NODE_SWITCHOVER = 4;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:108</i> */
		public static final int SA_AMF_NODE_FAILOVER = 5;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:109</i> */
		public static final int SA_AMF_NODE_FAILFAST = 6;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:110</i> */
		public static final int SA_AMF_CLUSTER_RESET = 7;
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_PM_ZERO_EXIT = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_PM_NON_ZERO_EXIT = (int)0x2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_PM_ABNORMAL_END = (int)0x4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_HEALTHCHECK_KEY_MAX = (int)32;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_CSI_ADD_ONE = (int)0X1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_CSI_TARGET_ONE = (int)0X2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public static final int SA_AMF_CSI_TARGET_ALL = (int)0X4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfHealthcheckCallbackT extends Callback {
		void apply(long invocation, SaNameT compName, SaAmfHealthcheckKeyT healthcheckKey);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfComponentTerminateCallbackT extends Callback {
		void apply(long invocation, SaNameT compName);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfCSISetCallbackT extends Callback {
		void apply(long invocation, SaNameT compName, int haState, SaAmfCSIDescriptorT.ByValue csiDescriptor);
	};
	/*public interface SaAmfCSISetCallbackT extends Callback {
		void apply(long invocation, Pointer compName, int haState, ByValue csiDescriptor);
	};*/
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfCSIRemoveCallbackT extends Callback {
		void apply(long invocation, SaNameT compName, SaNameT csiName, int csiFlags);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfProtectionGroupTrackCallbackT extends Callback {
		void apply(SaNameT csiName, SaAmfProtectionGroupNotificationBufferT notificationBuffer, int numberOfMembers, int error);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfProxiedComponentInstantiateCallbackT extends Callback {
		void apply(long invocation, SaNameT proxiedCompName);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h</i> */
	public interface SaAmfProxiedComponentCleanupCallbackT extends Callback {
		void apply(long invocation, SaNameT proxiedCompName);
	};
	/**
	 * Original signature : <code>SaAisErrorT saAmfInitialize(long*, const SaAmfCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:159</i><br>
	 * @deprecated use the safer method {@link #saAmfInitialize(com.sun.jna.ptr.PointerByReference, saamf.SaAmfCallbacksT, saamf.SaVersionT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfInitialize(Pointer amfHandle, SaAmfCallbacksT amfCallbacks, SaVersionT version);
	/**
	 * Original signature : <code>SaAisErrorT saAmfInitialize(long*, const SaAmfCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:159</i>
	 */
	int saAmfInitialize(LongByReference amfHandle, SaAmfCallbacksT.ByReference amfCallbacks, saAis.SaAisLibrary.SaVersionT.ByReference version);
	//int saAmfInitialize(LongByReference amfHandle, Pointer amfCallbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saAmfSelectionObjectGet(long, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:162</i><br>
	 * @deprecated use the safer methods {@link #saAmfSelectionObjectGet(saamf.long, saamf.SaAmfLibrary.SaSelectionObjectT)} and {@link #saAmfSelectionObjectGet(com.sun.jna.Pointer, saamf.SaAmfLibrary.SaSelectionObjectT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfSelectionObjectGet(Pointer amfHandle, SaAmfLibrary.SaSelectionObjectT selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saAmfSelectionObjectGet(long, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:162</i>
	 */
	int saAmfSelectionObjectGet(long amfHandle, LongByReference selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saAmfDispatch(long, SaDispatchFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:165</i><br>
	 * @deprecated use the safer methods {@link #saAmfDispatch(saamf.long, saamf.int)} and {@link #saAmfDispatch(com.sun.jna.Pointer, saamf.int)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfDispatch(Pointer amfHandle, int dispatchFlags);
	/**
	 * Original signature : <code>SaAisErrorT saAmfDispatch(long, SaDispatchFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:165</i>
	 */
	int saAmfDispatch(long amfHandle, int dispatchFlags);
	/**
	 * Original signature : <code>SaAisErrorT saAmfFinalize(long)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:167</i><br>
	 * @deprecated use the safer methods {@link #saAmfFinalize(saamf.long)} and {@link #saAmfFinalize(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfFinalize(Pointer amfHandle);
	/**
	 * Original signature : <code>SaAisErrorT saAmfFinalize(long)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:167</i>
	 */
	int saAmfFinalize(long amfHandle);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentRegister(long, const SaNameT*, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:170</i><br>
	 * @deprecated use the safer methods {@link #saAmfComponentRegister(saamf.long, saamf.SaNameT[], saamf.SaNameT[])} and {@link #saAmfComponentRegister(com.sun.jna.Pointer, saamf.SaNameT, saamf.SaNameT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfComponentRegister(Pointer amfHandle, SaNameT compName, SaNameT proxyCompName);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentRegister(long, const SaNameT*, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:170</i>
	 */
	int saAmfComponentRegister(long amfHandle, Pointer compName, Pointer proxyCompName);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentUnregister(long, const SaNameT*, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:173</i><br>
	 * @deprecated use the safer methods {@link #saAmfComponentUnregister(saamf.long, saamf.SaNameT[], saamf.SaNameT[])} and {@link #saAmfComponentUnregister(com.sun.jna.Pointer, saamf.SaNameT, saamf.SaNameT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfComponentUnregister(Pointer amfHandle, SaNameT compName, SaNameT proxyCompName);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentUnregister(long, const SaNameT*, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:173</i>
	 */
	//int saAmfComponentUnregister(long amfHandle, saAis.SaAisLibrary.SaNameT.ByReference compName, saAis.SaAisLibrary.SaNameT.ByReference proxyCompName);
	int saAmfComponentUnregister(long amfHandle, Pointer compName, Pointer proxyCompName);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentNameGet(long, SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:178</i><br>
	 * @deprecated use the safer methods {@link #saAmfComponentNameGet(saamf.long, saamf.SaNameT)} and {@link #saAmfComponentNameGet(com.sun.jna.Pointer, saamf.SaNameT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfComponentNameGet(Pointer amfHandle, SaNameT compName);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentNameGet(long, SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:178</i>
	 */
	int saAmfComponentNameGet(long amfHandle, saAis.SaAisLibrary.SaNameT.ByReference compName);
	
	/**
	 * Original signature : <code>SaAisErrorT saAmfHealthcheckStart(long, const SaNameT*, const SaAmfHealthcheckKeyT*, SaAmfHealthcheckInvocationT, SaAmfRecommendedRecoveryT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:196</i>
	 */
	int saAmfHealthcheckStart(long amfHandle, SaNameT compName[], SaAmfHealthcheckKeyT healthcheckKey, int invocationType, int recommendedRecovery);
	/**
	 * Original signature : <code>SaAisErrorT saAmfHealthcheckConfirm(long, const SaNameT*, const SaAmfHealthcheckKeyT*, SaAisErrorT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:203</i><br>
	 * @deprecated use the safer methods {@link #saAmfHealthcheckConfirm(saamf.long, saamf.SaNameT[], saamf.SaAmfHealthcheckKeyT, saamf.SaAisErrorT)} and {@link #saAmfHealthcheckConfirm(com.sun.jna.Pointer, saamf.SaNameT, saamf.SaAmfHealthcheckKeyT, saamf.SaAisErrorT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfHealthcheckConfirm(Pointer amfHandle, SaNameT compName, SaAmfHealthcheckKeyT healthcheckKey, SaAisErrorT healthcheckResult);
	/**
	 * Original signature : <code>SaAisErrorT saAmfHealthcheckConfirm(long, const SaNameT*, const SaAmfHealthcheckKeyT*, SaAisErrorT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:203</i>
	 */
	int saAmfHealthcheckConfirm(long amfHandle, SaNameT compName[], SaAmfHealthcheckKeyT healthcheckKey, int healthcheckResult);
	/**
	 * Original signature : <code>SaAisErrorT saAmfHealthcheckStop(long, const SaNameT*, const SaAmfHealthcheckKeyT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:209</i><br>
	 * @deprecated use the safer methods {@link #saAmfHealthcheckStop(saamf.long, saamf.SaNameT[], saamf.SaAmfHealthcheckKeyT)} and {@link #saAmfHealthcheckStop(com.sun.jna.Pointer, saamf.SaNameT, saamf.SaAmfHealthcheckKeyT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfHealthcheckStop(Pointer amfHandle, SaNameT compName, SaAmfHealthcheckKeyT healthcheckKey);
	/**
	 * Original signature : <code>SaAisErrorT saAmfHealthcheckStop(long, const SaNameT*, const SaAmfHealthcheckKeyT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:209</i>
	 */
	int saAmfHealthcheckStop(long amfHandle, SaNameT compName[], SaAmfHealthcheckKeyT healthcheckKey);
	/**
	 * Original signature : <code>SaAisErrorT saAmfCSIQuiescingComplete(long, SaInvocationT, SaAisErrorT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:214</i><br>
	 * @deprecated use the safer methods {@link #saAmfCSIQuiescingComplete(saamf.long, saamf.long, saamf.SaAisErrorT)} and {@link #saAmfCSIQuiescingComplete(com.sun.jna.Pointer, saamf.long, saamf.SaAisErrorT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfCSIQuiescingComplete(Pointer amfHandle, long invocation, SaAisErrorT error);
	/**
	 * Original signature : <code>SaAisErrorT saAmfCSIQuiescingComplete(long, SaInvocationT, SaAisErrorT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:214</i>
	 */
	int saAmfCSIQuiescingComplete(long amfHandle, long invocation, int error);
	/**
	 * Original signature : <code>SaAisErrorT saAmfHAStateGet(long, const SaNameT*, const SaNameT*, SaAmfHAStateT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:219</i><br>
	 * @deprecated use the safer methods {@link #saAmfHAStateGet(saamf.long, saamf.SaNameT[], saamf.SaNameT[], java.nio.IntBuffer)} and {@link #saAmfHAStateGet(com.sun.jna.Pointer, saamf.SaNameT, saamf.SaNameT, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfHAStateGet(Pointer amfHandle, SaNameT compName, SaNameT csiName, IntByReference haState);
	/**
	 * Original signature : <code>SaAisErrorT saAmfHAStateGet(long, const SaNameT*, const SaNameT*, SaAmfHAStateT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:219</i>
	 */
	int saAmfHAStateGet(long amfHandle, SaNameT compName[], SaNameT csiName[], IntByReference haState);
	/**
	 * Original signature : <code>SaAisErrorT saAmfProtectionGroupTrack(long, const SaNameT*, SaUint8T, SaAmfProtectionGroupNotificationBufferT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:225</i><br>
	 * @deprecated use the safer methods {@link #saAmfProtectionGroupTrack(saamf.long, saamf.SaNameT[], saamf.byte, saamf.SaAmfProtectionGroupNotificationBufferT)} and {@link #saAmfProtectionGroupTrack(com.sun.jna.Pointer, saamf.SaNameT, saamf.byte, saamf.SaAmfProtectionGroupNotificationBufferT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfProtectionGroupTrack(Pointer amfHandle, SaNameT csiName, byte trackFlags, SaAmfProtectionGroupNotificationBufferT notificationBuffer);
	/**
	 * Original signature : <code>SaAisErrorT saAmfProtectionGroupTrack(long, const SaNameT*, SaUint8T, SaAmfProtectionGroupNotificationBufferT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:225</i>
	 */
	int saAmfProtectionGroupTrack(long amfHandle, SaNameT csiName[], byte trackFlags, SaAmfProtectionGroupNotificationBufferT notificationBuffer);
	/**
	 * Original signature : <code>SaAisErrorT saAmfProtectionGroupTrackStop(long, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:231</i><br>
	 * @deprecated use the safer methods {@link #saAmfProtectionGroupTrackStop(saamf.long, saamf.SaNameT[])} and {@link #saAmfProtectionGroupTrackStop(com.sun.jna.Pointer, saamf.SaNameT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfProtectionGroupTrackStop(Pointer amfHandle, SaNameT csiName);
	/**
	 * Original signature : <code>SaAisErrorT saAmfProtectionGroupTrackStop(long, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:231</i>
	 */
	int saAmfProtectionGroupTrackStop(long amfHandle, SaNameT csiName[]);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentErrorReport(long, const SaNameT*, SaTimeT, SaAmfRecommendedRecoveryT, SaNtfIdentifierT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:235</i><br>
	 * @deprecated use the safer methods {@link #saAmfComponentErrorReport(saamf.long, saamf.SaNameT[], saamf.long, int, saamf.long)} and {@link #saAmfComponentErrorReport(com.sun.jna.Pointer, saamf.SaNameT, saamf.long, int, saamf.long)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfComponentErrorReport(Pointer amfHandle, SaNameT erroneousComponent, long errorDetectionTime, int recommendedRecovery, long ntfIdentifier);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentErrorReport(long, const SaNameT*, SaTimeT, SaAmfRecommendedRecoveryT, SaNtfIdentifierT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:235</i>
	 */
	int saAmfComponentErrorReport(long amfHandle, SaNameT erroneousComponent[], long errorDetectionTime, int recommendedRecovery, long ntfIdentifier);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentErrorClear(long, const SaNameT*, SaNtfIdentifierT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:241</i><br>
	 * @deprecated use the safer methods {@link #saAmfComponentErrorClear(saamf.long, saamf.SaNameT[], saamf.long)} and {@link #saAmfComponentErrorClear(com.sun.jna.Pointer, saamf.SaNameT, saamf.long)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfComponentErrorClear(Pointer amfHandle, SaNameT compName, long ntfIdentifier);
	/**
	 * Original signature : <code>SaAisErrorT saAmfComponentErrorClear(long, const SaNameT*, SaNtfIdentifierT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:241</i>
	 */
	int saAmfComponentErrorClear(long amfHandle, SaNameT compName[], long ntfIdentifier);
	/**
	 * Original signature : <code>SaAisErrorT saAmfResponse(long, SaInvocationT, SaAisErrorT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:246</i><br>
	 * @deprecated use the safer methods {@link #saAmfResponse(saamf.long, saamf.long, saamf.SaAisErrorT)} and {@link #saAmfResponse(com.sun.jna.Pointer, saamf.long, saamf.SaAisErrorT)} instead
	 */
	@Deprecated 
	SaAisErrorT saAmfResponse(Pointer amfHandle, long invocation, SaAisErrorT error);
	/**
	 * Original signature : <code>SaAisErrorT saAmfResponse(long, SaInvocationT, SaAisErrorT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/amf/include/saAmf.h:246</i>
	 */
	int saAmfResponse(long amfHandle, long invocation, int error);
	/*public static class SaUint8T extends PointerType {
		public SaUint8T(Pointer address) {
			super(address);
		}
		public SaUint8T() {
			super();
		}
	};*/
	public static interface SaAmfHaStateT {
	  public static final int SA_AMF_HA_ACTIVE = 1;
	  public static final int SA_AMF_HA_STANDBY = 2;
	  public static final int SA_AMF_HA_QUIESCED = 3;
	  public static final int SA_AMF_HA_QUIESCING = 4;
	};
	
	public static class SaSelectionObjectT extends PointerType {
		public SaSelectionObjectT(Pointer address) {
			super(address);
		}
		public SaSelectionObjectT() {
			super();
		}
	};
	/*public static class SaUint16T extends PointerType {
		public SaUint16T(Pointer address) {
			super(address);
		}
		public SaUint16T() {
			super();
		}
	};*/
	/*public static class SaDispatchFlagsT extends PointerType {
		public SaDispatchFlagsT(Pointer address) {
			super(address);
		}
		public SaDispatchFlagsT() {
			super();
		}
	};*/
	/*public static class long extends PointerType {
		public long(Pointer address) {
			super(address);
		}
		public long() {
			super();
		}
	};*/
	/*public static class SaTimeT extends PointerType {
		public SaTimeT(Pointer address) {
			super(address);
		}
		public SaTimeT() {
			super();
		}
	};*/
	/*public static class SaInt64T extends PointerType {
		public SaInt64T(Pointer address) {
			super(address);
		}
		public SaInt64T() {
			super();
		}
	};*/
	/*public static class SaNtfIdentifierT extends PointerType {
		public SaNtfIdentifierT(Pointer address) {
			super(address);
		}
		public SaNtfIdentifierT() {
			super();
		}
	};*/
	/*public static class SaInt32T extends PointerType {
		public SaInt32T(Pointer address) {
			super(address);
		}
		public SaInt32T() {
			super();
		}
	};*/
	/*public static class SaUint32T extends PointerType {
		public SaUint32T(Pointer address) {
			super(address);
		}
		public SaUint32T() {
			super();
		}
	};*/
	/*public static class SaAmfCSIFlagsT extends PointerType {
		public SaAmfCSIFlagsT(Pointer address) {
			super(address);
		}
		public SaAmfCSIFlagsT() {
			super();
		}
	};*/
	/*public static class SaUint64T extends PointerType {
		public SaUint64T(Pointer address) {
			super(address);
		}
		public SaUint64T() {
			super();
		}
	};*/
	/*public static class SaVersionT extends PointerType {
		public SaVersionT(Pointer address) {
			super(address);
		}
		public SaVersionT() {
			super();
		}
	};*/
	/*public static class SaVersionT extends Structure {
        public byte releaseCode;
        public byte majorVersion;
        public byte minorVersion;

        @Override
        protected List<String> getFieldOrder() {
            return List.of("releaseCode", "majorVersion", "minorVersion");
        }
    };*/
	/*public static class SaAisErrorT extends PointerType {
		public SaAisErrorT(Pointer address) {
			super(address);
		}
		public SaAisErrorT() {
			super();
		}
	};
	public static class SaInvocationT extends PointerType {
		public SaInvocationT(Pointer address) {
			super(address);
		}
		public SaInvocationT() {
			super();
		}
	};
	/*public static class SaNameT extends PointerType {
		public SaNameT(Pointer address) {
			super(address);
		}
		public SaNameT() {
			super();
		}
	};
	public static class SaAmfPmErrorsT extends PointerType {
		public SaAmfPmErrorsT(Pointer address) {
			super(address);
		}
		public SaAmfPmErrorsT() {
			super();
		}
	};*/
}
