package saCkpt;
import saCkpt.SaCkptLibrary.SaCkptCheckpointOpenCallbackT;
import saCkpt.SaCkptLibrary.SaCkptCheckpointSynchronizeCallbackT;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaCkptCallbacksT extends Structure {
	/** C type : SaCkptCheckpointOpenCallbackT */
	public SaCkptCheckpointOpenCallbackT saCkptCheckpointOpenCallback;
	/** C type : SaCkptCheckpointSynchronizeCallbackT */
	public SaCkptCheckpointSynchronizeCallbackT saCkptCheckpointSynchronizeCallback;
	public SaCkptCallbacksT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("saCkptCheckpointOpenCallback", "saCkptCheckpointSynchronizeCallback");
	}
	/**
	 * @param saCkptCheckpointOpenCallback C type : SaCkptCheckpointOpenCallbackT<br>
	 * @param saCkptCheckpointSynchronizeCallback C type : SaCkptCheckpointSynchronizeCallbackT
	 */
	public SaCkptCallbacksT(SaCkptCheckpointOpenCallbackT saCkptCheckpointOpenCallback, SaCkptCheckpointSynchronizeCallbackT saCkptCheckpointSynchronizeCallback) {
		super();
		this.saCkptCheckpointOpenCallback = saCkptCheckpointOpenCallback;
		this.saCkptCheckpointSynchronizeCallback = saCkptCheckpointSynchronizeCallback;
	}
	public SaCkptCallbacksT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaCkptCallbacksT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaCkptCallbacksT implements Structure.ByValue {
		
	};
}
