package saCkpt;
//import saCkpt.SaCkptLibrary.SaOffsetT;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaCkptIOVectorElementT extends Structure {
	/** C type : SaCkptSectionIdT */
	public SaCkptSectionIdT sectionId;
	/** C type : void* */
	public Pointer dataBuffer;
	/** C type : SaSizeT */
	public long dataSize;
	/** C type : SaOffsetT */
	//public SaOffsetT dataOffset;
	public long dataOffset;
	/** C type : SaSizeT */
	public long readSize;
	public SaCkptIOVectorElementT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sectionId", "dataBuffer", "dataSize", "dataOffset", "readSize");
	}
	/**
	 * @param sectionId C type : SaCkptSectionIdT<br>
	 * @param dataBuffer C type : void*<br>
	 * @param dataSize C type : SaSizeT<br>
	 * @param dataOffset C type : SaOffsetT<br>
	 * @param readSize C type : SaSizeT
	 */
	public SaCkptIOVectorElementT(SaCkptSectionIdT sectionId, Pointer dataBuffer, long dataSize, long dataOffset, long readSize) {
		super();
		this.sectionId = sectionId;
		this.dataBuffer = dataBuffer;
		this.dataSize = dataSize;
		this.dataOffset = dataOffset;
		this.readSize = readSize;
	}
	public SaCkptIOVectorElementT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaCkptIOVectorElementT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaCkptIOVectorElementT implements Structure.ByValue {
		
	};
}
