package saCkpt;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaCkptSectionCreationAttributesT extends Structure {
	/** C type : SaCkptSectionIdT* */
	//public saCkpt.SaCkptSectionIdT.ByReference sectionId;
	public Pointer sectionId;
	/** C type : SaTimeT */
	public long expirationTime;
	public SaCkptSectionCreationAttributesT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("sectionId", "expirationTime");
	}
	/**
	 * @param sectionId C type : SaCkptSectionIdT*<br>
	 * @param expirationTime C type : SaTimeT
	 */
	public SaCkptSectionCreationAttributesT(Pointer sectionId, long expirationTime) {
		super();
		this.sectionId = sectionId;
		this.expirationTime = expirationTime;
	}
	public SaCkptSectionCreationAttributesT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaCkptSectionCreationAttributesT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaCkptSectionCreationAttributesT implements Structure.ByValue {
		
	};
}
