package saCkpt;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaCkptCheckpointCreationAttributesT extends Structure {
	/** C type : SaCkptCheckpointCreationFlagsT */
	public int creationFlags;
	/** C type : SaSizeT */
	public long checkpointSize;
	/** C type : SaTimeT */
	public long retentionDuration;
	/** C type : SaUint32T */
	public int maxSections;
	/** C type : SaSizeT */
	public long maxSectionSize;
	/** C type : SaSizeT */
	public long maxSectionIdSize;
	public SaCkptCheckpointCreationAttributesT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("creationFlags", "checkpointSize", "retentionDuration", "maxSections", "maxSectionSize", "maxSectionIdSize");
	}
	/**
	 * @param creationFlags C type : SaCkptCheckpointCreationFlagsT<br>
	 * @param checkpointSize C type : SaSizeT<br>
	 * @param retentionDuration C type : SaTimeT<br>
	 * @param maxSections C type : SaUint32T<br>
	 * @param maxSectionSize C type : SaSizeT<br>
	 * @param maxSectionIdSize C type : SaSizeT
	 */
	public SaCkptCheckpointCreationAttributesT(int creationFlags, long checkpointSize, long retentionDuration, int maxSections, long maxSectionSize, long maxSectionIdSize) {
		super();
		this.creationFlags = creationFlags;
		this.checkpointSize = checkpointSize;
		this.retentionDuration = retentionDuration;
		this.maxSections = maxSections;
		this.maxSectionSize = maxSectionSize;
		this.maxSectionIdSize = maxSectionIdSize;
	}
	public SaCkptCheckpointCreationAttributesT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaCkptCheckpointCreationAttributesT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaCkptCheckpointCreationAttributesT implements Structure.ByValue {
		
	};
}
