package saCkpt;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.LongByReference;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>clCkpt</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SaCkptLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ClCkpt";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SaCkptLibrary.JNA_LIBRARY_NAME);
	public static final SaCkptLibrary INSTANCE = (SaCkptLibrary)Native.load(SaCkptLibrary.JNA_LIBRARY_NAME, SaCkptLibrary.class);
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
	 * enum values
	 */
	public static interface SaCkptSectionStateT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:80</i> */
		public static final int SA_CKPT_SECTION_VALID = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:81</i> */
		public static final int SA_CKPT_SECTION_CORRUPTED = 2;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
	 * enum values
	 */
	public static interface SaCkptSectionsChosenT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:93</i> */
		public static final int SA_CKPT_SECTIONS_FOREVER = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:94</i> */
		public static final int SA_CKPT_SECTIONS_LEQ_EXPIRATION_TIME = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:95</i> */
		public static final int SA_CKPT_SECTIONS_GEQ_EXPIRATION_TIME = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:96</i> */
		public static final int SA_CKPT_SECTIONS_CORRUPTED = 4;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:97</i> */
		public static final int SA_CKPT_SECTIONS_ANY = 5;
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_WR_ALL_REPLICAS = (int)0X1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_WR_ACTIVE_REPLICA = (int)0X2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_WR_ACTIVE_REPLICA_WEAK = (int)0X4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_CHECKPOINT_COLLOCATED = (int)0X8;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_CHECKPOINT_READ = (int)0X1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_CHECKPOINT_WRITE = (int)0X2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public static final int SA_CKPT_CHECKPOINT_CREATE = (int)0X4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public interface SaCkptCheckpointOpenCallbackT extends Callback {
		void apply(long invocation, long checkpointHandle, int error);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i> */
	public interface SaCkptCheckpointSynchronizeCallbackT extends Callback {
		void apply(long invocation, int error);
	};
	/**
	 * Original signature : <code>SaAisErrorT saCkptInitialize(SaCkptHandleT*, const SaCkptCallbacksT*, SaVersionT*)</code><br>
	 
	 */
	 
	int saCkptInitialize(LongByReference ckptHandle, SaCkptCallbacksT callbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saCkptInitialize(SaCkptHandleT*, const SaCkptCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:127</i>
	 */
	//int saCkptInitialize(LongBuffer ckptHandle, SaCkptCallbacksT callbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSelectionObjectGet(SaCkptHandleT, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:131</i><br>
	 * use the safer methods {@link #saCkptSelectionObjectGet(long, java.nio.LongBuffer)} and {@link #saCkptSelectionObjectGet(long, com.sun.jna.ptr.LongByReference)} instead
	 */
	
	int saCkptSelectionObjectGet(long ckptHandle, LongByReference selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSelectionObjectGet(SaCkptHandleT, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:131</i>
	 */
	//int saCkptSelectionObjectGet(long ckptHandle, LongBuffer selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saCkptDispatch(SaCkptHandleT, SaDispatchFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:134</i>
	 */
	int saCkptDispatch(long ckptHandle, int dispatchFlags);
	/**
	 * Original signature : <code>SaAisErrorT saCkptFinalize(SaCkptHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:137</i>
	 */
	int saCkptFinalize(long ckptHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointOpen(SaCkptHandleT, const SaNameT*, const SaCkptCheckpointCreationAttributesT*, SaCkptCheckpointOpenFlagsT, SaTimeT, SaCkptCheckpointHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:139</i><br>
	
	 */
	 
	int saCkptCheckpointOpen(long ckptHandle, Pointer ckeckpointName, SaCkptCheckpointCreationAttributesT checkpointCreationAttributes, int checkpointOpenFlags, long timeout, LongByReference checkpointHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointOpen(SaCkptHandleT, const SaNameT*, const SaCkptCheckpointCreationAttributesT*, SaCkptCheckpointOpenFlagsT, SaTimeT, SaCkptCheckpointHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:139</i>
	 */
	//int saCkptCheckpointOpen(long ckptHandle, Pointer ckeckpointName, SaCkptCheckpointCreationAttributesT checkpointCreationAttributes, int checkpointOpenFlags, long timeout, LongBuffer checkpointHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointOpenAsync(SaCkptHandleT, SaInvocationT, const SaNameT*, const SaCkptCheckpointCreationAttributesT*, SaCkptCheckpointOpenFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:146</i>
	 */
	int saCkptCheckpointOpenAsync(long ckptHandle, long invocation, Pointer ckeckpointName, SaCkptCheckpointCreationAttributesT checkpointCreationAttributes, int checkpointOpenFlags);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointClose(SaCkptCheckpointHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:152</i>
	 */
	int saCkptCheckpointClose(long checkpointHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointUnlink(SaCkptHandleT, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:154</i>
	 */
	int saCkptCheckpointUnlink(long ckptHandle, Pointer checkpointName);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointRetentionDurationSet(SaCkptCheckpointHandleT, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:157</i>
	 */
	int saCkptCheckpointRetentionDurationSet(long checkpointHandle, long retentionDuration);
	/**
	 * Original signature : <code>SaAisErrorT saCkptActiveReplicaSet(SaCkptCheckpointHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:160</i>
	 */
	int saCkptActiveReplicaSet(long checkpointHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointStatusGet(SaCkptCheckpointHandleT, SaCkptCheckpointDescriptorT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:162</i>
	 */
	int saCkptCheckpointStatusGet(long checkpointHandle, SaCkptCheckpointDescriptorT checkpointStatus);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionCreate(SaCkptCheckpointHandleT, SaCkptSectionCreationAttributesT*, const SaUint8T*, SaSizeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:165</i><br>
	 * @deprecated use the safer methods {@link #saCkptSectionCreate(long, clckpt.SaCkptSectionCreationAttributesT, java.nio.ByteBuffer, long)} and {@link #saCkptSectionCreate(long, clckpt.SaCkptSectionCreationAttributesT, com.sun.jna.Pointer, long)} instead
	 */
	@Deprecated 
	int saCkptSectionCreate(long checkpointHandle, SaCkptSectionCreationAttributesT sectionCreationAttributes, Pointer initialData, long initialDataSize);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionCreate(SaCkptCheckpointHandleT, SaCkptSectionCreationAttributesT*, const SaUint8T*, SaSizeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:165</i>
	 */
	int saCkptSectionCreate(long checkpointHandle, SaCkptSectionCreationAttributesT sectionCreationAttributes, ByteBuffer initialData, long initialDataSize);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionDelete(SaCkptCheckpointHandleT, const SaCkptSectionIdT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:170</i>
	 */
	int saCkptSectionDelete(long checkpointHandle, SaCkptSectionIdT sectionId);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionExpirationTimeSet(SaCkptCheckpointHandleT, const SaCkptSectionIdT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:173</i>
	 */
	int saCkptSectionExpirationTimeSet(long checkpointHandle, SaCkptSectionIdT sectionId, long expirationTime);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionIterationInitialize(SaCkptCheckpointHandleT, SaCkptSectionsChosenT, SaTimeT, SaCkptSectionIterationHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:177</i><br>
	 * @deprecated use the safer methods {@link #saCkptSectionIterationInitialize(long, int, long, java.nio.LongBuffer)} and {@link #saCkptSectionIterationInitialize(long, int, long, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	int saCkptSectionIterationInitialize(long checkpointHandle, int sectionsChosen, long expirationTime, LongByReference sectionIterationHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionIterationInitialize(SaCkptCheckpointHandleT, SaCkptSectionsChosenT, SaTimeT, SaCkptSectionIterationHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:177</i>
	 */
	int saCkptSectionIterationInitialize(long checkpointHandle, int sectionsChosen, long expirationTime, LongBuffer sectionIterationHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionIterationNext(SaCkptSectionIterationHandleT, SaCkptSectionDescriptorT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:182</i>
	 */
	int saCkptSectionIterationNext(long sectionIterationHandle, SaCkptSectionDescriptorT sectionDescriptor);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionIterationFinalize(SaCkptSectionIterationHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:185</i>
	 */
	int saCkptSectionIterationFinalize(long sectionIterationHandle);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointWrite(SaCkptCheckpointHandleT, const SaCkptIOVectorElementT*, SaUint32T, SaUint32T*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:187</i><br>
	 
	 */
	 
	int saCkptCheckpointWrite(long checkpointHandle, SaCkptIOVectorElementT ioVector, int numberOfElements, IntByReference erroneousVectorIndex);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointWrite(SaCkptCheckpointHandleT, const SaCkptIOVectorElementT*, SaUint32T, SaUint32T*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:187</i>
	 */
	//int saCkptCheckpointWrite(long checkpointHandle, SaCkptIOVectorElementT ioVector, int numberOfElements, IntBuffer erroneousVectorIndex);
	/**
	 * Original signature : <code>SaAisErrorT saCkptSectionOverwrite(SaCkptCheckpointHandleT, const SaCkptSectionIdT*, const void*, SaSizeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:192</i>
	 */
	int saCkptSectionOverwrite(long checkpointHandle, SaCkptSectionIdT sectionId, Pointer dataBuffer, long dataSize);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointRead(SaCkptCheckpointHandleT, SaCkptIOVectorElementT*, SaUint32T, SaUint32T*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:197</i><br>	 
	 */	 
	int saCkptCheckpointRead(long checkpointHandle, SaCkptIOVectorElementT ioVector, int numberOfElements, IntByReference erroneousVectorIndex);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointRead(SaCkptCheckpointHandleT, SaCkptIOVectorElementT*, SaUint32T, SaUint32T*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:197</i>
	 */
	//int saCkptCheckpointRead(long checkpointHandle, SaCkptIOVectorElementT ioVector, int numberOfElements, IntBuffer erroneousVectorIndex);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointSynchronize(SaCkptCheckpointHandleT, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:202</i>
	 */
	int saCkptCheckpointSynchronize(long ckeckpointHandle, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saCkptCheckpointSynchronizeAsync(SaCkptCheckpointHandleT, SaInvocationT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h:205</i>
	 */
	int saCkptCheckpointSynchronizeAsync(long checkpointHandle, long invocation);
	/*public static class SaOffsetT extends PointerType {
		public SaOffsetT(Pointer address) {
			super(address);
		}
		public SaOffsetT() {
			super();
		}
	};*/
}
