package saCkpt;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ckpt/include/saCkpt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaCkptSectionIdT extends Structure {
	/** C type : SaUint16T */
	public short idLen;
	/** C type : SaUint8T* */
	public Pointer id;
	public SaCkptSectionIdT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("idLen", "id");
	}
	/**
	 * @param idLen C type : SaUint16T<br>
	 * @param id C type : SaUint8T*
	 */
	public SaCkptSectionIdT(short idLen, Pointer id) {
		super();
		this.idLen = idLen;
		this.id = id;
	}
	public SaCkptSectionIdT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaCkptSectionIdT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaCkptSectionIdT implements Structure.ByValue {
		
	};
}
