package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsAppConfigT extends Structure {
	/**
	 * base class<br>
	 * C type : ClAmsEntityConfigT
	 */
	public ClAmsEntityConfigT entity;
	public ClAmsAppConfigT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity");
	}
	/**
	 * @param entity base class<br>
	 * C type : ClAmsEntityConfigT
	 */
	public ClAmsAppConfigT(ClAmsEntityConfigT entity) {
		super();
		this.entity = entity;
	}
	public ClAmsAppConfigT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsAppConfigT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsAppConfigT implements Structure.ByValue {
		
	};
}
