package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsCSICompRefT extends Structure {
	/**
	 * < base reference to Comp<br>
	 * C type : ClAmsEntityRefT
	 */
	public ClAmsEntityRefT entityRef;
	/**
	 * @see ClAmsHAStateT<br>
	 * < ha state for CSI<br>
	 * C type : ClAmsHAStateT
	 */
	public int haState;
	/**
	 * < rank of the assignment<br>
	 * C type : int
	 */
	public int rank;
	public ClAmsCSICompRefT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entityRef", "haState", "rank");
	}
	/**
	 * @param entityRef < base reference to Comp<br>
	 * C type : ClAmsEntityRefT<br>
	 * @param haState @see ClAmsHAStateT<br>
	 * < ha state for CSI<br>
	 * C type : ClAmsHAStateT<br>
	 * @param rank < rank of the assignment<br>
	 * C type : int
	 */
	public ClAmsCSICompRefT(ClAmsEntityRefT entityRef, int haState, int rank) {
		super();
		this.entityRef = entityRef;
		this.haState = haState;
		this.rank = rank;
	}
	public ClAmsCSICompRefT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsCSICompRefT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsCSICompRefT implements Structure.ByValue {
		
	};
}
