package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSUConfigT extends Structure {
	/**
	 * < base class<br>
	 * C type : ClAmsEntityConfigT
	 */
	public ClAmsEntityConfigT entity;
	/**
	 * @see ClAmsAdminStateT<br>
	 * < can AMS use entity?<br>
	 * C type : ClAmsAdminStateT
	 */
	public int adminState;
	/**
	 * < preference 1..4294967295<br>
	 * C type : int
	 */
	public int rank;
	/**
	 * < components in SU<br>
	 * C type : int
	 */
	public int numComponents;
	/**
	 * < true if any comp is prei<br>
	 * C type : ClBoolT
	 */
	public short isPreinstantiable;
	/**
	 * < is SU restartable?<br>
	 * C type : ClBoolT
	 */
	public short isRestartable;
	/**
	 * < does SU contain other SUs<br>
	 * C type : ClBoolT
	 */
	public short isContainerSU;
	/**
	 * < list of components in SU<br>
	 * C type : ClAmsEntityListT
	 */
	public ClAmsEntityListT compList;
	/**
	 * < SU is part of this SG<br>
	 * C type : ClAmsEntityRefT
	 */
	public ClAmsEntityRefT parentSG;
	/**
	 * < SU is part of this node<br>
	 * C type : ClAmsEntityRefT
	 */
	public ClAmsEntityRefT parentNode;
	public ClAmsSUConfigT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity", "adminState", "rank", "numComponents", "isPreinstantiable", "isRestartable", "isContainerSU", "compList", "parentSG", "parentNode");
	}
	public ClAmsSUConfigT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSUConfigT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSUConfigT implements Structure.ByValue {
		
	};
}
