package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtClientApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsMgmtCallbacksT extends Structure {
	public int nothingForNow;
	public ClAmsMgmtCallbacksT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("nothingForNow");
	}
	public ClAmsMgmtCallbacksT(int nothingForNow) {
		super();
		this.nothingForNow = nothingForNow;
	}
	public ClAmsMgmtCallbacksT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsMgmtCallbacksT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsMgmtCallbacksT implements Structure.ByValue {
		
	};
}
