package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import clUtils.ClUtilsLibrary.*;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsCSINameValuePairT extends Structure {
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 *
	 */
	public ClNameT csiName;
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	public ClNameT paramName;
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	public ClNameT paramValue;
	public ClAmsCSINameValuePairT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("csiName","paramName","paramValue");
	}
	public ClAmsCSINameValuePairT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsCSINameValuePairT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsCSINameValuePairT implements Structure.ByValue {
		
	};
}
