package clAmsMgmtClientApi;
import clUtils.ClUtilsLibrary.*;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsEntityConfigT extends Structure {
	/**
	 * @see ClAmsEntityTypeT<br>
	 * < Type of entity (SG,SU,SI,CSI, etc)<br>
	 * C type : ClAmsEntityTypeT
	 */
	public int type;
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	public ClNameT name;
	/**
	 * debug sub area flags<br>
	 * C type : ClUint8T
	 */
	public byte debugFlags;
	public ClAmsEntityConfigT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type","name", "debugFlags");
	}
	/**
	 * @param type @see ClAmsEntityTypeT<br>
	 * < Type of entity (SG,SU,SI,CSI, etc)<br>
	 * C type : ClAmsEntityTypeT<br>
	 * @param debugFlags debug sub area flags<br>
	 * C type : ClUint8T
	 */
	public ClAmsEntityConfigT(int type, ClNameT name, byte debugFlags) {
		super();
		this.type = type;
		this.name = name;
		this.debugFlags = debugFlags;
	}
	public ClAmsEntityConfigT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsEntityConfigT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsEntityConfigT implements Structure.ByValue {
		
	};
}
