package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsCSINVPBufferT extends Structure {
	/** C type : int */
	public int count;
	/** C type : ClAmsCSINVPT* */
	public clAmsMgmtClientApi.ClAmsCSINameValuePairT.ByReference nvp;
	public ClAmsCSINVPBufferT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("count", "nvp");
	}
	/**
	 * @param count C type : int<br>
	 * @param nvp C type : ClAmsCSINVPT*
	 */
	public ClAmsCSINVPBufferT(int count, clAmsMgmtClientApi.ClAmsCSINameValuePairT.ByReference nvp) {
		super();
		this.count = count;
		this.nvp = nvp;
	}
	public ClAmsCSINVPBufferT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsCSINVPBufferT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsCSINVPBufferT implements Structure.ByValue {
		
	};
}
