package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsCSIActiveDescriptorT extends Structure {
	/**
	 * @see ClAmsCSITransitionDescriptorT<br>
	 * C type : ClAmsCSITransitionDescriptorT
	 */
	public int transitionDescriptor;
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	public ClAmsCSIActiveDescriptorT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("transitionDescriptor");
	}
	/**
	 * @param transitionDescriptor @see ClAmsCSITransitionDescriptorT<br>
	 * C type : ClAmsCSITransitionDescriptorT
	 */
	public ClAmsCSIActiveDescriptorT(int transitionDescriptor) {
		super();
		this.transitionDescriptor = transitionDescriptor;
	}
	public ClAmsCSIActiveDescriptorT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsCSIActiveDescriptorT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsCSIActiveDescriptorT implements Structure.ByValue {
		
	};
}
