package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsMgmtMigrateList extends Structure {
	/** C type : ClAmsEntityBufferT */
	public ClAmsEntityBufferT si;
	/** C type : ClAmsEntityBufferT */
	public ClAmsEntityBufferT csi;
	/** C type : ClAmsEntityBufferT */
	public ClAmsEntityBufferT node;
	/** C type : ClAmsEntityBufferT */
	public ClAmsEntityBufferT su;
	/** C type : ClAmsEntityBufferT */
	public ClAmsEntityBufferT comp;
	public ClAmsMgmtMigrateList() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("si", "csi", "node", "su", "comp");
	}
	/**
	 * @param si C type : ClAmsEntityBufferT<br>
	 * @param csi C type : ClAmsEntityBufferT<br>
	 * @param node C type : ClAmsEntityBufferT<br>
	 * @param su C type : ClAmsEntityBufferT<br>
	 * @param comp C type : ClAmsEntityBufferT
	 */
	public ClAmsMgmtMigrateList(ClAmsEntityBufferT si, ClAmsEntityBufferT csi, ClAmsEntityBufferT node, ClAmsEntityBufferT su, ClAmsEntityBufferT comp) {
		super();
		this.si = si;
		this.csi = csi;
		this.node = node;
		this.su = su;
		this.comp = comp;
	}
	public ClAmsMgmtMigrateList(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsMgmtMigrateList implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsMgmtMigrateList implements Structure.ByValue {
		
	};
}
