package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSUT extends Structure {
	/** C type : ClAmsSUConfigT */
	public ClAmsSUConfigT config;
	/** C type : ClAmsSUStatusT */
	public ClAmsSUStatusT status;
	/** C type : ClAmsSUMethodsT */
	public ClAmsSUMethodsT methods;
	public ClAmsSUT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("config", "status", "methods");
	}
	/**
	 * @param config C type : ClAmsSUConfigT<br>
	 * @param status C type : ClAmsSUStatusT<br>
	 * @param methods C type : ClAmsSUMethodsT
	 */
	public ClAmsSUT(ClAmsSUConfigT config, ClAmsSUStatusT status, ClAmsSUMethodsT methods) {
		super();
		this.config = config;
		this.status = status;
		this.methods = methods;
	}
	public ClAmsSUT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSUT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSUT implements Structure.ByValue {
		
	};
}
