package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class clAmsMgmtDebugEnableLogToConsoleRequestT extends Structure {
	/** C type : ClAmsMgmtHandleT */
	public long handle;
	public clAmsMgmtDebugEnableLogToConsoleRequestT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("handle");
	}
	/** @param handle C type : ClAmsMgmtHandleT */
	public clAmsMgmtDebugEnableLogToConsoleRequestT(long handle) {
		super();
		this.handle = handle;
	}
	public clAmsMgmtDebugEnableLogToConsoleRequestT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends clAmsMgmtDebugEnableLogToConsoleRequestT implements Structure.ByReference {
		
	};
	public static class ByValue extends clAmsMgmtDebugEnableLogToConsoleRequestT implements Structure.ByValue {
		
	};
}
