package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsEntityListT extends Structure {
	/**
	 * @see ClAmsEntityTypeT<br>
	 * entity type in list<br>
	 * C type : ClAmsEntityTypeT
	 */
	public int type;
	/**
	 * Ranked list or Unranked list<br>
	 * C type : ClBoolT
	 */
	public short isRankedList;
	/**
	 * is list valid<br>
	 * C type : ClBoolT
	 */
	public short isValid;
	/**
	 * list count<br>
	 * C type : int
	 */
	public int numEntities;
	/**
	 * list container<br>
	 * C type : ClCntHandleT
	 */
	public Pointer list;
	public ClAmsEntityListT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "isRankedList", "isValid", "numEntities", "list");
	}
	/**
	 * @param type @see ClAmsEntityTypeT<br>
	 * entity type in list<br>
	 * C type : ClAmsEntityTypeT<br>
	 * @param isRankedList Ranked list or Unranked list<br>
	 * C type : ClBoolT<br>
	 * @param isValid is list valid<br>
	 * C type : ClBoolT<br>
	 * @param numEntities list count<br>
	 * C type : int<br>
	 * @param list list container<br>
	 * C type : ClCntHandleT
	 */
	public ClAmsEntityListT(int type, short isRankedList, short isValid, int numEntities, Pointer list) {
		super();
		this.type = type;
		this.isRankedList = isRankedList;
		this.isValid = isValid;
		this.numEntities = numEntities;
		this.list = list;
	}
	public ClAmsEntityListT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsEntityListT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsEntityListT implements Structure.ByValue {
		
	};
}
