package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsEntityStatusT extends Structure {
	/**
	 * < time when started<br>
	 * C type : ClTimeT
	 */
	public long epoch;
	/**
	 * < # timers running<br>
	 * C type : int
	 */
	public int timerCount;
	/** C type : ClAmsEntityOpStackT */
	public ClAmsEntityOpStack opStack;
	public ClAmsEntityStatusT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("epoch", "timerCount", "opStack");
	}
	/**
	 * @param epoch < time when started<br>
	 * C type : ClTimeT<br>
	 * @param timerCount < # timers running<br>
	 * C type : int<br>
	 * @param opStack C type : ClAmsEntityOpStackT
	 */
	public ClAmsEntityStatusT(long epoch, int timerCount, ClAmsEntityOpStack opStack) {
		super();
		this.epoch = epoch;
		this.timerCount = timerCount;
		this.opStack = opStack;
	}
	public ClAmsEntityStatusT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsEntityStatusT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsEntityStatusT implements Structure.ByValue {
		
	};
}
