package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsCompTimerDurationsT extends Structure {
	/** C type : ClTimeT */
	public long instantiate;
	/** C type : ClTimeT */
	public long terminate;
	/** C type : ClTimeT */
	public long cleanup;
	/** C type : ClTimeT */
	public long amStart;
	/** C type : ClTimeT */
	public long amStop;
	/** C type : ClTimeT */
	public long quiescingComplete;
	/** C type : ClTimeT */
	public long csiSet;
	/** C type : ClTimeT */
	public long csiRemove;
	/** C type : ClTimeT */
	public long proxiedCompInstantiate;
	/** C type : ClTimeT */
	public long proxiedCompCleanup;
	/** C type : ClTimeT */
	public long instantiateDelay;
	public ClAmsCompTimerDurationsT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("instantiate", "terminate", "cleanup", "amStart", "amStop", "quiescingComplete", "csiSet", "csiRemove", "proxiedCompInstantiate", "proxiedCompCleanup", "instantiateDelay");
	}
	public ClAmsCompTimerDurationsT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsCompTimerDurationsT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsCompTimerDurationsT implements Structure.ByValue {
		
	};
}
