package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsNodeT extends Structure {
	/** C type : ClAmsNodeConfigT */
	public ClAmsNodeConfigT config;
	/** C type : ClAmsNodeStatusT */
	public ClAmsNodeStatusT status;
	/** C type : ClAmsNodeMethodsT */
	public ClAmsNodeMethodsT methods;
	public ClAmsNodeT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("config", "status", "methods");
	}
	/**
	 * @param config C type : ClAmsNodeConfigT<br>
	 * @param status C type : ClAmsNodeStatusT<br>
	 * @param methods C type : ClAmsNodeMethodsT
	 */
	public ClAmsNodeT(ClAmsNodeConfigT config, ClAmsNodeStatusT status, ClAmsNodeMethodsT methods) {
		super();
		this.config = config;
		this.status = status;
		this.methods = methods;
	}
	public ClAmsNodeT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsNodeT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsNodeT implements Structure.ByValue {
		
	};
}
