package clAmsMgmtClientApi;
import clUtils.ClUtilsLibrary.*;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsPGMemberT extends Structure {
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	ClNameT compName;
	/**
	 * @see ClAmsHAStateT<br>
	 * ha state for CSI<br>
	 * C type : ClAmsHAStateT
	 */
	public int haState;
	/**
	 * rank, if state is standby<br>
	 * C type : int
	 */
	public int rank;
	public ClAmsPGMemberT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("compName","haState", "rank");
	}
	/**
	 * @param haState @see ClAmsHAStateT<br>
	 * ha state for CSI<br>
	 * C type : ClAmsHAStateT<br>
	 * @param rank rank, if state is standby<br>
	 * C type : int
	 */
	public ClAmsPGMemberT(ClNameT compName, int haState, int rank) {
		super();
		this.compName = compName;
		this.haState = haState;
		this.rank = rank;
	}
	public ClAmsPGMemberT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsPGMemberT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsPGMemberT implements Structure.ByValue {
		
	};
}
