package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class clAmsMgmtCCBSetNodeDependencyRequestT extends Structure {
	/** C type : ClAmsMgmtCCBHandleT */
	public long handle;
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT nodeName;
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT dependencyNodeName;
	public clAmsMgmtCCBSetNodeDependencyRequestT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("handle", "nodeName", "dependencyNodeName");
	}
	/**
	 * @param handle C type : ClAmsMgmtCCBHandleT<br>
	 * @param nodeName C type : ClAmsEntityT<br>
	 * @param dependencyNodeName C type : ClAmsEntityT
	 */
	public clAmsMgmtCCBSetNodeDependencyRequestT(long handle, ClAmsEntityConfigT nodeName, ClAmsEntityConfigT dependencyNodeName) {
		super();
		this.handle = handle;
		this.nodeName = nodeName;
		this.dependencyNodeName = dependencyNodeName;
	}
	public clAmsMgmtCCBSetNodeDependencyRequestT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends clAmsMgmtCCBSetNodeDependencyRequestT implements Structure.ByReference {
		
	};
	public static class ByValue extends clAmsMgmtCCBSetNodeDependencyRequestT implements Structure.ByValue {
		
	};
}
