package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSUSIExtendedRefT extends Structure {
	/** C type : ClAmsEntityRefT */
	public ClAmsEntityRefT entityRef;
	/**
	 * @see ClAmsHAStateT<br>
	 * C type : ClAmsHAStateT
	 */
	public int haState;
	/**
	 * < active csis in this si<br>
	 * C type : int
	 */
	public int numActiveCSIs;
	/**
	 * < standby csis in this si<br>
	 * C type : int
	 */
	public int numStandbyCSIs;
	/**
	 * < quiesced csis in this si<br>
	 * C type : int
	 */
	public int numQuiescedCSIs;
	/**
	 * < quiescing csis in this si<br>
	 * C type : int
	 */
	public int numQuiescingCSIs;
	/**
	 * num configured csis in this si<br>
	 * C type : int
	 */
	public int numCSIs;
	/**
	 * < rank associated with SI<br>
	 * C type : int
	 */
	public int rank;
	/**
	 * number of pending invocations for this si<br>
	 * C type : int
	 */
	public int pendingInvocations;
	public ClAmsSUSIExtendedRefT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entityRef", "haState", "numActiveCSIs", "numStandbyCSIs", "numQuiescedCSIs", "numQuiescingCSIs", "numCSIs", "rank", "pendingInvocations");
	}
	/**
	 * @param entityRef C type : ClAmsEntityRefT<br>
	 * @param haState @see ClAmsHAStateT<br>
	 * C type : ClAmsHAStateT<br>
	 * @param numActiveCSIs < active csis in this si<br>
	 * C type : int<br>
	 * @param numStandbyCSIs < standby csis in this si<br>
	 * C type : int<br>
	 * @param numQuiescedCSIs < quiesced csis in this si<br>
	 * C type : int<br>
	 * @param numQuiescingCSIs < quiescing csis in this si<br>
	 * C type : int<br>
	 * @param numCSIs num configured csis in this si<br>
	 * C type : int<br>
	 * @param rank < rank associated with SI<br>
	 * C type : int<br>
	 * @param pendingInvocations number of pending invocations for this si<br>
	 * C type : int
	 */
	public ClAmsSUSIExtendedRefT(ClAmsEntityRefT entityRef, int haState, int numActiveCSIs, int numStandbyCSIs, int numQuiescedCSIs, int numQuiescingCSIs, int numCSIs, int rank, int pendingInvocations) {
		super();
		this.entityRef = entityRef;
		this.haState = haState;
		this.numActiveCSIs = numActiveCSIs;
		this.numStandbyCSIs = numStandbyCSIs;
		this.numQuiescedCSIs = numQuiescedCSIs;
		this.numQuiescingCSIs = numQuiescingCSIs;
		this.numCSIs = numCSIs;
		this.rank = rank;
		this.pendingInvocations = pendingInvocations;
	}
	public ClAmsSUSIExtendedRefT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSUSIExtendedRefT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSUSIExtendedRefT implements Structure.ByValue {
		
	};
}
