package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsEntityRefT extends Structure {
	/**
	 * type/name of target<br>
	 * C type : ClAmsEntityT
	 */
	public ClAmsEntityConfigT entity;
	/**
	 * ptr to target<br>
	 * C type : ClAmsEntityT*
	 */
	public ClAmsEntityConfigT.ByReference ptr;
	/**
	 * target's cnt handle<br>
	 * C type : ClCntNodeHandleT
	 */
	public Pointer nodeHandle;
	public ClAmsEntityRefT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity", "ptr", "nodeHandle");
	}
	/**
	 * @param entity type/name of target<br>
	 * C type : ClAmsEntityT<br>
	 * @param ptr ptr to target<br>
	 * C type : ClAmsEntityT*<br>
	 * @param nodeHandle target's cnt handle<br>
	 * C type : ClCntNodeHandleT
	 */
	public ClAmsEntityRefT(ClAmsEntityConfigT entity, ClAmsEntityConfigT.ByReference ptr, Pointer nodeHandle) {
		super();
		this.entity = entity;
		this.ptr = ptr;
		this.nodeHandle = nodeHandle;
	}
	public ClAmsEntityRefT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsEntityRefT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsEntityRefT implements Structure.ByValue {
		
	};
}
