package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsCompT extends Structure {
	/** C type : ClAmsCompConfigT */
	public ClAmsCompConfigT config;
	/** C type : ClAmsCompStatusT */
	public ClAmsCompStatusT status;
	/** C type : ClAmsCompMethodsT */
	public ClAmsCompMethodsT methods;
	public ClAmsCompT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("config", "status", "methods");
	}
	/**
	 * @param config C type : ClAmsCompConfigT<br>
	 * @param status C type : ClAmsCompStatusT<br>
	 * @param methods C type : ClAmsCompMethodsT
	 */
	public ClAmsCompT(ClAmsCompConfigT config, ClAmsCompStatusT status, ClAmsCompMethodsT methods) {
		super();
		this.config = config;
		this.status = status;
		this.methods = methods;
	}
	public ClAmsCompT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsCompT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsCompT implements Structure.ByValue {
		
	};
}
