package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsMgmtUserDataGetRequest extends Structure {
	/** C type : ClAmsEntityT* */
	public clAmsMgmtClientApi.ClAmsEntityConfigT.ByReference entity;
	/** C type : ClNameT* */
	public Pointer key;
	/** C type : ClCharT** */
	public PointerByReference data;
	/** C type : int* */
	public int len;
	public ClAmsMgmtUserDataGetRequest() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity", "key", "data", "len");
	}
	/**
	 * @param entity C type : ClAmsEntityT*<br>
	 * @param key C type : ClNameT*<br>
	 * @param data C type : ClCharT**<br>
	 * @param len C type : int*
	 */
	public ClAmsMgmtUserDataGetRequest(clAmsMgmtClientApi.ClAmsEntityConfigT.ByReference entity, Pointer key, PointerByReference data, int len) {
		super();
		this.entity = entity;
		this.key = key;
		this.data = data;
		this.len = len;
	}
	public ClAmsMgmtUserDataGetRequest(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsMgmtUserDataGetRequest implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsMgmtUserDataGetRequest implements Structure.ByValue {
		
	};
}
