package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsMgmtSIAssignSUCustomRequest extends Structure {
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT si;
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT activeSU;
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT standbySU;
	public ClAmsMgmtSIAssignSUCustomRequest() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("si", "activeSU", "standbySU");
	}
	/**
	 * @param si C type : ClAmsEntityT<br>
	 * @param activeSU C type : ClAmsEntityT<br>
	 * @param standbySU C type : ClAmsEntityT
	 */
	public ClAmsMgmtSIAssignSUCustomRequest(ClAmsEntityConfigT si, ClAmsEntityConfigT activeSU, ClAmsEntityConfigT standbySU) {
		super();
		this.si = si;
		this.activeSU = activeSU;
		this.standbySU = standbySU;
	}
	public ClAmsMgmtSIAssignSUCustomRequest(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsMgmtSIAssignSUCustomRequest implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsMgmtSIAssignSUCustomRequest implements Structure.ByValue {
		
	};
}
