package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSUStatusT extends Structure {
	/**
	 * < base class<br>
	 * C type : ClAmsEntityStatusT
	 */
	public ClAmsEntityStatusT entity;
	/**
	 * @see ClAmsPresenceStateT<br>
	 * < presence state (saf)<br>
	 * C type : ClAmsPresenceStateT
	 */
	public int presenceState;
	/**
	 * @see ClAmsOperStateT<br>
	 * < operational state (saf)<br>
	 * C type : ClAmsOperStateT
	 */
	public int operState;
	/**
	 * @see ClAmsReadinessStateT<br>
	 * < readiness state (saf)<br>
	 * C type : ClAmsReadinessStateT
	 */
	public int readinessState;
	/**
	 * @see ClAmsRecoveryT<br>
	 * < recovery action<br>
	 * C type : ClAmsLocalRecoveryT
	 */
	public int recovery;
	/**
	 * < active SI count for SU<br>
	 * C type : int
	 */
	public int numActiveSIs;
	/**
	 * < standby SI count for SU<br>
	 * C type : int
	 */
	public int numStandbySIs;
	/**
	 * < quiesced SI count for SU<br>
	 * C type : int
	 */
	public int numQuiescedSIs;
	/**
	 * < current SU failure count<br>
	 * C type : int
	 */
	public int compRestartCount;
	/**
	 * < timer details<br>
	 * C type : ClAmsEntityTimerT
	 */
	public ClAmsEntityTimerT compRestartTimer;
	/**
	 * < current SU failure count<br>
	 * C type : int
	 */
	public int suRestartCount;
	/**
	 * < timer details<br>
	 * C type : ClAmsEntityTimerT
	 */
	public ClAmsEntityTimerT suRestartTimer;
	/**
	 * <probation timer details<br>
	 * C type : ClAmsEntityTimerT
	 */
	public ClAmsEntityTimerT suProbationTimer;
	/**
	 * pref.assignment timer<br>
	 * C type : ClAmsEntityTimerT
	 */
	public ClAmsEntityTimerT suAssignmentTimer;
	/**
	 * < num instantiated comps<br>
	 * C type : int
	 */
	public int numInstantiatedComp;
	/**
	 * < preinstantiable comps<br>
	 * C type : int
	 */
	public int numPIComp;
	/**
	 * SUs current instantiate level<br>
	 * C type : int
	 */
	public int instantiateLevel;
	/**
	 * < adjustments waited for higher rank realignments for active<br>
	 * C type : int
	 */
	public int numWaitAdjustments;
	/**
	 * Assignment delays for SI preference  *<br>
	 * C type : int
	 */
	public int numDelayAssignments;
	/**
	 * < list of SI for this SU<br>
	 * C type : ClAmsEntityListT
	 */
	public ClAmsEntityListT siList;
	public ClAmsSUStatusT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity", "presenceState", "operState", "readinessState", "recovery", "numActiveSIs", "numStandbySIs", "numQuiescedSIs", "compRestartCount", "compRestartTimer", "suRestartCount", "suRestartTimer", "suProbationTimer", "suAssignmentTimer", "numInstantiatedComp", "numPIComp", "instantiateLevel", "numWaitAdjustments", "numDelayAssignments", "siList");
	}
	public ClAmsSUStatusT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSUStatusT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSUStatusT implements Structure.ByValue {
		
	};
}
