package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsMgmtDBGetResponse extends Structure {
	/** C type : int */
	public int len;
	/** C type : ClUint8T* */
	public Pointer buffer;
	public ClAmsMgmtDBGetResponse() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("len", "buffer");
	}
	/**
	 * @param len C type : int<br>
	 * @param buffer C type : ClUint8T*
	 */
	public ClAmsMgmtDBGetResponse(int len, Pointer buffer) {
		super();
		this.len = len;
		this.buffer = buffer;
	}
	public ClAmsMgmtDBGetResponse(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsMgmtDBGetResponse implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsMgmtDBGetResponse implements Structure.ByValue {
		
	};
}
