package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class clAmsMgmtEntityGetConfigRequestT extends Structure {
	/** C type : ClAmsMgmtHandleT */
	public long handle;
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT entity;
	public clAmsMgmtEntityGetConfigRequestT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("handle", "entity");
	}
	/**
	 * @param handle C type : ClAmsMgmtHandleT<br>
	 * @param entity C type : ClAmsEntityT
	 */
	public clAmsMgmtEntityGetConfigRequestT(long handle, ClAmsEntityConfigT entity) {
		super();
		this.handle = handle;
		this.entity = entity;
	}
	public clAmsMgmtEntityGetConfigRequestT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends clAmsMgmtEntityGetConfigRequestT implements Structure.ByReference {
		
	};
	public static class ByValue extends clAmsMgmtEntityGetConfigRequestT implements Structure.ByValue {
		
	};
}
