package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSUReassignOp extends Structure {
	/** C type : int */
	public int numSIs;
	/** C type : ClAmsEntityT* */
	public clAmsMgmtClientApi.ClAmsEntityConfigT.ByReference sis;
	public ClAmsSUReassignOp() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("numSIs", "sis");
	}
	/**
	 * @param numSIs C type : int<br>
	 * @param sis C type : ClAmsEntityT*
	 */
	public ClAmsSUReassignOp(int numSIs, clAmsMgmtClientApi.ClAmsEntityConfigT.ByReference sis) {
		super();
		this.numSIs = numSIs;
		this.sis = sis;
	}
	public ClAmsSUReassignOp(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSUReassignOp implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSUReassignOp implements Structure.ByValue {
		
	};
}
