package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsCompCSIRefT extends Structure {
	/**
	 * < base reference to CSI<br>
	 * C type : ClAmsEntityRefT
	 */
	public ClAmsEntityRefT entityRef;
	/**
	 * @see ClAmsHAStateT<br>
	 * < ha state for CSI<br>
	 * C type : ClAmsHAStateT
	 */
	public int haState;
	/**
	 * @see ClAmsCSITransitionDescriptorT<br>
	 * < transition descriptor<br>
	 * C type : ClAmsCSITransitionDescriptorT
	 */
	public int tdescriptor;
	/**
	 * < rank of the assignment<br>
	 * C type : int
	 */
	public int rank;
	/**
	 * < comp with active ha state<br>
	 * C type : ClAmsEntityT*
	 */
	public clAmsMgmtClientApi.ClAmsEntityConfigT.ByReference activeComp;
	/**
	 * < pending op on CSI<br>
	 * C type : ClUint16T
	 */
	public short pendingOp;
	public ClAmsCompCSIRefT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entityRef", "haState", "tdescriptor", "rank", "activeComp", "pendingOp");
	}
	/**
	 * @param entityRef < base reference to CSI<br>
	 * C type : ClAmsEntityRefT<br>
	 * @param haState @see ClAmsHAStateT<br>
	 * < ha state for CSI<br>
	 * C type : ClAmsHAStateT<br>
	 * @param tdescriptor @see ClAmsCSITransitionDescriptorT<br>
	 * < transition descriptor<br>
	 * C type : ClAmsCSITransitionDescriptorT<br>
	 * @param rank < rank of the assignment<br>
	 * C type : int<br>
	 * @param activeComp < comp with active ha state<br>
	 * C type : ClAmsEntityT*<br>
	 * @param pendingOp < pending op on CSI<br>
	 * C type : ClUint16T
	 */
	public ClAmsCompCSIRefT(ClAmsEntityRefT entityRef, int haState, int tdescriptor, int rank, clAmsMgmtClientApi.ClAmsEntityConfigT.ByReference activeComp, short pendingOp) {
		super();
		this.entityRef = entityRef;
		this.haState = haState;
		this.tdescriptor = tdescriptor;
		this.rank = rank;
		this.activeComp = activeComp;
		this.pendingOp = pendingOp;
	}
	public ClAmsCompCSIRefT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsCompCSIRefT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsCompCSIRefT implements Structure.ByValue {
		
	};
}
