package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsCSIStandbyDescriptorT extends Structure {
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	/** C type : int */
	public int standbyRank;
	public ClAmsCSIStandbyDescriptorT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("standbyRank");
	}
	/** @param standbyRank C type : int */
	public ClAmsCSIStandbyDescriptorT(int standbyRank) {
		super();
		this.standbyRank = standbyRank;
	}
	public ClAmsCSIStandbyDescriptorT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsCSIStandbyDescriptorT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsCSIStandbyDescriptorT implements Structure.ByValue {
		
	};
}
