package clAmsMgmtClientApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class clAmsMgmtEntityFindByNameResponseT extends Structure {
	/** C type : ClAmsEntityRefT */
	public ClAmsEntityRefT entityRef;
	public clAmsMgmtEntityFindByNameResponseT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entityRef");
	}
	/** @param entityRef C type : ClAmsEntityRefT */
	public clAmsMgmtEntityFindByNameResponseT(ClAmsEntityRefT entityRef) {
		super();
		this.entityRef = entityRef;
	}
	public clAmsMgmtEntityFindByNameResponseT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends clAmsMgmtEntityFindByNameResponseT implements Structure.ByReference {
		
	};
	public static class ByValue extends clAmsMgmtEntityFindByNameResponseT implements Structure.ByValue {
		
	};
}
