package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsCSIDescriptorT extends Structure {
	/** C type : ClAmsCSIFlagsT */
	public int csiFlags;
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	/** C type : ClAmsCSIStateDescriptorT */
	public ClAmsCSIStateDescriptorT csiStateDescriptor;
	/** C type : ClAmsCSIAttributeListT */
	public ClAmsCSIAttributeListT csiAttributeList;
	public ClAmsCSIDescriptorT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("csiFlags", "csiStateDescriptor", "csiAttributeList");
	}
	/**
	 * @param csiFlags C type : ClAmsCSIFlagsT<br>
	 * @param csiStateDescriptor C type : ClAmsCSIStateDescriptorT<br>
	 * @param csiAttributeList C type : ClAmsCSIAttributeListT
	 */
	public ClAmsCSIDescriptorT(int csiFlags, ClAmsCSIStateDescriptorT csiStateDescriptor, ClAmsCSIAttributeListT csiAttributeList) {
		super();
		this.csiFlags = csiFlags;
		this.csiStateDescriptor = csiStateDescriptor;
		this.csiAttributeList = csiAttributeList;
	}
	public ClAmsCSIDescriptorT(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsCSIDescriptorT implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsCSIDescriptorT implements Structure.ByValue {
		
	};
}
