package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsPGNotificationT extends Structure {
	/** C type : ClAmsPGMemberT */
	public ClAmsPGMemberT member;
	/**
	 * @see ClAmsPGChangeT<br>
	 * C type : ClAmsPGChangeT
	 */
	public int change;
	public ClAmsPGNotificationT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("member", "change");
	}
	/**
	 * @param member C type : ClAmsPGMemberT<br>
	 * @param change @see ClAmsPGChangeT<br>
	 * C type : ClAmsPGChangeT
	 */
	public ClAmsPGNotificationT(ClAmsPGMemberT member, int change) {
		super();
		this.member = member;
		this.change = change;
	}
	public ClAmsPGNotificationT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsPGNotificationT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsPGNotificationT implements Structure.ByValue {
		
	};
}
