package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSISURefT extends Structure {
	/**
	 * < base reference to SU<br>
	 * C type : ClAmsEntityRefT
	 */
	public ClAmsEntityRefT entityRef;
	/**
	 * < rank associated with SU<br>
	 * C type : int
	 */
	public int rank;
	/**
	 * @see ClAmsHAStateT<br>
	 * < hastate assigned to SU<br>
	 * C type : ClAmsHAStateT
	 */
	public int haState;
	public ClAmsSISURefT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entityRef", "rank", "haState");
	}
	/**
	 * @param entityRef < base reference to SU<br>
	 * C type : ClAmsEntityRefT<br>
	 * @param rank < rank associated with SU<br>
	 * C type : int<br>
	 * @param haState @see ClAmsHAStateT<br>
	 * < hastate assigned to SU<br>
	 * C type : ClAmsHAStateT
	 */
	public ClAmsSISURefT(ClAmsEntityRefT entityRef, int rank, int haState) {
		super();
		this.entityRef = entityRef;
		this.rank = rank;
		this.haState = haState;
	}
	public ClAmsSISURefT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSISURefT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSISURefT implements Structure.ByValue {
		
	};
}
