package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSUSIExtendedRefBufferT extends Structure {
	/** C type : int */
	public int count;
	/** C type : ClAmsSUSIExtendedRefT* */
	public clAmsMgmtClientApi.ClAmsSUSIExtendedRefT.ByReference entityRef;
	public ClAmsSUSIExtendedRefBufferT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("count", "entityRef");
	}
	/**
	 * @param count C type : int<br>
	 * @param entityRef C type : ClAmsSUSIExtendedRefT*
	 */
	public ClAmsSUSIExtendedRefBufferT(int count, clAmsMgmtClientApi.ClAmsSUSIExtendedRefT.ByReference entityRef) {
		super();
		this.count = count;
		this.entityRef = entityRef;
	}
	public ClAmsSUSIExtendedRefBufferT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSUSIExtendedRefBufferT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSUSIExtendedRefBufferT implements Structure.ByValue {
		
	};
}
