package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsSGFailoverHistory extends Structure {
	/**
	 * Conversion Error : struct ClListHead {<br>
	 * 	ClListHead* pNext;<br>
	 * 	ClListHead* pPrev;<br>
	 * }
	 */
	/** C type : ClAmsEntityT */
	public ClAmsEntityConfigT entity;
	/** C type : int */
	public int index;
	/** C type : ClTimerHandleT */
	public Pointer timer;
	/** C type : int */
	public int numFailovers;
	public ClAmsSGFailoverHistory() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity", "index", "timer", "numFailovers");
	}
	/**
	 * @param entity C type : ClAmsEntityT<br>
	 * @param index C type : int<br>
	 * @param timer C type : ClTimerHandleT<br>
	 * @param numFailovers C type : int
	 */
	public ClAmsSGFailoverHistory(ClAmsEntityConfigT entity, int index, Pointer timer, int numFailovers) {
		super();
		this.entity = entity;
		this.index = index;
		this.timer = timer;
		this.numFailovers = numFailovers;
	}
	public ClAmsSGFailoverHistory(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsSGFailoverHistory implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsSGFailoverHistory implements Structure.ByValue {
		
	};
}
