package clAmsMgmtClientApi;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsMgmtCommon.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class ClAmsMgmtMigrateRequest extends Structure {
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	/**
	 * Conversion Error : struct ClNameT {<br>
	 * 	unsigned short length;<br>
	 * 	char[256] value;<br>
	 * }
	 */
	/** C type : int */
	public int activeSUs;
	/** C type : int */
	public int standbySUs;
	public ClAmsMgmtMigrateRequest() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("activeSUs", "standbySUs");
	}
	/**
	 * @param activeSUs C type : int<br>
	 * @param standbySUs C type : int
	 */
	public ClAmsMgmtMigrateRequest(int activeSUs, int standbySUs) {
		super();
		this.activeSUs = activeSUs;
		this.standbySUs = standbySUs;
	}
	public ClAmsMgmtMigrateRequest(Pointer peer) {
		super(peer);
	}
	public static  class ByReference extends ClAmsMgmtMigrateRequest implements Structure.ByReference {
		
	};
	public static  class ByValue extends ClAmsMgmtMigrateRequest implements Structure.ByValue {
		
	};
}
