package clAmsMgmtClientApi;


import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : clAmsEntities.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClAmsSIConfigT extends Structure {
	/**
	 * < base class<br>
	 * C type : ClAmsEntityConfigT
	 */
	public ClAmsEntityConfigT entity;
	/**
	 * @see ClAmsAdminStateT<br>
	 * < can AMS use entity?<br>
	 * C type : ClAmsAdminStateT
	 */
	public int adminState;
	/**
	 * < preference for this SI<br>
	 * C type : int
	 */
	public int rank;
	/**
	 * < number of CSIs in this SI<br>
	 * C type : int
	 */
	public int numCSIs;
	/**
	 * < n-way model only<br>
	 * C type : int
	 */
	public int numStandbyAssignments;
	/**
	 * standby assignment order for CSI dep.<br>
	 * C type : int
	 */
	public int standbyAssignmentOrder;
	/**
	 * < SI is part of this SG<br>
	 * C type : ClAmsEntityRefT
	 */
	public ClAmsEntityRefT parentSG;
	/**
	 * < ordered SUs for this SI<br>
	 * C type : ClAmsEntityListT
	 */
	public ClAmsEntityListT suList;
	/**
	 * < clusterwide dependents<br>
	 * C type : ClAmsEntityListT
	 */
	public ClAmsEntityListT siDependentsList;
	/**
	 * < clusterwide dependencies<br>
	 * C type : ClAmsEntityListT
	 */
	public ClAmsEntityListT siDependenciesList;
	/**
	 * < CSIs part of this SI<br>
	 * C type : ClAmsEntityListT
	 */
	public ClAmsEntityListT csiList;
	public ClAmsSIConfigT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("entity", "adminState", "rank", "numCSIs", "numStandbyAssignments", "standbyAssignmentOrder", "parentSG", "suList", "siDependentsList", "siDependenciesList", "csiList");
	}
	public ClAmsSIConfigT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClAmsSIConfigT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClAmsSIConfigT implements Structure.ByValue {
		
	};
}
