package clLogApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClLogStreamAttributesT extends Structure {
	/**
	 * Its the prefix name of file units that are going to be created.<br>
	 * C type : ClCharT*
	 */
	public String fileName;
	/**
	 * Its the path where the log file unit(s) will be created.<br>
	 * C type : ClCharT*
	 */
	public String fileLocation;
	/**
	 * Size of the file unit. It will be truncated to multiples of recordSize.<br>
	 * C type : ClUint32T
	 */
	public int fileUnitSize;
	/**
	 * Size of the log record.<br>
	 * C type : ClUint32T
	 */
	public int recordSize;
	/**
	 * Log file replication property. Currently is not supported.<br>
	 * C type : ClBoolT
	 */
	public short haProperty;
	/**
	 * Action that log service has to take, when the log file unit becomes full.<br>
	 * @see ClLogFileFullActionT<br>
	 * C type : ClLogFileFullActionT
	 */
	public int fileFullAction;
	/**
	 * If fileAction is CL_LOG_FILE_FULL_ACTION_ROTATE, the maximum num of log<br>
	 * file units that will be created by logService.Otherwise ignored.<br>
	 * C type : ClUint32T
	 */
	public int maxFilesRotated;
	/**
	 * Num of log records after which the log stream records must be flushed.<br>
	 * C type : ClUint32T
	 */
	public int flushFreq;
	/**
	 * Time after which the log stream records must be flushed.<br>
	 * C type : ClTimeT
	 */
	public long flushInterval;
	
	public ClWaterMarkT waterMark;
	
	/** C type : ClBoolT */
	public short syslog;
	public ClLogStreamAttributesT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("fileName", "fileLocation", "fileUnitSize", "recordSize", "haProperty", "fileFullAction", "maxFilesRotated", "flushFreq", "flushInterval", "waterMark", "syslog");
	}
	public ClLogStreamAttributesT(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends ClLogStreamAttributesT implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends ClLogStreamAttributesT implements Structure.ByValue {
		
	};
}
