package clLogApi;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/log/include/clLogApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClWaterMarkT extends Structure {
	public long lowLimit;
	public long highLimit;
	
	public ClWaterMarkT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("lowLimit", "highLimit");
	}
	public ClWaterMarkT(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends ClWaterMarkT implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends ClWaterMarkT implements Structure.ByValue {
		
	};
}
