package saEvt;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.LongByReference;
import java.nio.ByteBuffer;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>ClEventClient</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SaEventClientLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ClEventClient";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SaEventClientLibrary.JNA_LIBRARY_NAME);
	public static final SaEventClientLibrary INSTANCE = (SaEventClientLibrary)Native.load(SaEventClientLibrary.JNA_LIBRARY_NAME, SaEventClientLibrary.class);
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i><br>
	 * enum values
	 */
	public static interface SaEvtEventFilterTypeT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:95</i> */
		public static final int SA_EVT_PREFIX_FILTER = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:96</i> */
		public static final int SA_EVT_SUFFIX_FILTER = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:97</i> */
		public static final int SA_EVT_EXACT_FILTER = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:98</i> */
		public static final int SA_EVT_PASS_ALL_FILTER = 4;
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_CHANNEL_PUBLISHER = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_CHANNEL_SUBSCRIBER = (int)0x2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_CHANNEL_CREATE = (int)0x4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_HIGHEST_PRIORITY = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_LOWEST_PRIORITY = (int)3;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_EVENTID_NONE = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final int SA_EVT_EVENTID_LOST = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public static final String SA_EVT_LOST_EVENT = (String)"SA_EVT_LOST_EVENT_PATTERN";
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public interface SaEvtChannelOpenCallbackT extends Callback {
		void apply(long invocation, long channelHandle, int error);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i> */
	public interface SaEvtEventDeliverCallbackT extends Callback {
		void apply(int subscriptionId, long eventHandle, long eventDataSize);
	};
	/**
	 * Original signature : <code>SaAisErrorT saEvtInitialize(SaEvtHandleT*, const SaEvtCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:113</i><br>
	 * use the safer methods {@link #saEvtInitialize(java.nio.LongBuffer, saEvt.SaEvtCallbacksT, com.sun.jna.Pointer)} and {@link #saEvtInitialize(com.sun.jna.ptr.LongByReference, saEvt.SaEvtCallbacksT, com.sun.jna.Pointer)} instead
	 */
	//@Deprecated 
	int saEvtInitialize(LongByReference evtHandle, SaEvtCallbacksT callbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saEvtInitialize(SaEvtHandleT*, const SaEvtCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:113</i>
	 */
	//int saEvtInitialize(LongBuffer evtHandle, SaEvtCallbacksT callbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saEvtSelectionObjectGet(SaEvtHandleT, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:116</i><br>
	 * use the safer methods {@link #saEvtSelectionObjectGet(long, java.nio.LongBuffer)} and {@link #saEvtSelectionObjectGet(long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saEvtSelectionObjectGet(long evtHandle, LongByReference selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saEvtSelectionObjectGet(SaEvtHandleT, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:116</i>
	 */
	//int saEvtSelectionObjectGet(long evtHandle, LongBuffer selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saEvtDispatch(SaEvtHandleT, SaDispatchFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:119</i>
	 */
	int saEvtDispatch(long evtHandle, int dispatchFlags);
	/**
	 * Original signature : <code>SaAisErrorT saEvtFinalize(SaEvtHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:121</i>
	 */
	int saEvtFinalize(long evtHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtChannelOpen(SaEvtHandleT, const SaNameT*, SaEvtChannelOpenFlagsT, SaTimeT, SaEvtChannelHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:122</i><br>
	 * use the safer methods {@link #saEvtChannelOpen(long, com.sun.jna.Pointer, byte, long, java.nio.LongBuffer)} and {@link #saEvtChannelOpen(long, com.sun.jna.Pointer, byte, long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saEvtChannelOpen(long evtHandle, saAis.SaAisLibrary.SaNameT channelName, int channelOpenFlags, long timeout, LongByReference channelHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtChannelOpen(SaEvtHandleT, const SaNameT*, SaEvtChannelOpenFlagsT, SaTimeT, SaEvtChannelHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:122</i>
	 */
	//int saEvtChannelOpen(long evtHandle, Pointer channelName, byte channelOpenFlags, long timeout, LongBuffer channelHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtChannelOpenAsync(SaEvtHandleT, SaInvocationT, const SaNameT*, SaEvtChannelOpenFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:127</i>
	 */
	int saEvtChannelOpenAsync(long evtHandle, long invocation, saAis.SaAisLibrary.SaNameT channelName, byte channelOpenFlags);
	/**
	 * Original signature : <code>SaAisErrorT saEvtChannelClose(SaEvtChannelHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:132</i>
	 */
	int saEvtChannelClose(long channelHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtChannelUnlink(SaEvtHandleT, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:133</i>
	 */
	int saEvtChannelUnlink(long evtHandle, saAis.SaAisLibrary.SaNameT channelName);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventAllocate(SaEvtChannelHandleT, SaEvtEventHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:135</i><br>
	 * use the safer methods {@link #saEvtEventAllocate(long, java.nio.LongBuffer)} and {@link #saEvtEventAllocate(long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saEvtEventAllocate(long channelHandle, LongByReference eventHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventAllocate(SaEvtChannelHandleT, SaEvtEventHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:135</i>
	 */
	//int saEvtEventAllocate(long channelHandle, LongBuffer eventHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventFree(SaEvtEventHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:137</i>
	 */
	int saEvtEventFree(long eventHandle);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventAttributesSet(SaEvtEventHandleT, const SaEvtEventPatternArrayT*, SaUint8T, SaTimeT, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:138</i>
	 */
	int saEvtEventAttributesSet(long eventHandle, SaEvtEventPatternArrayT patternArray, int priority, long retentionTime, saAis.SaAisLibrary.SaNameT publisherName);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventAttributesGet(SaEvtEventHandleT, SaEvtEventPatternArrayT*, SaUint8T*, SaTimeT*, SaNameT*, SaTimeT*, SaEvtEventIdT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:143</i><br>
	 * use the safer methods {@link #saEvtEventAttributesGet(long, saEvt.SaEvtEventPatternArrayT, java.nio.ByteBuffer, java.nio.LongBuffer, com.sun.jna.Pointer, java.nio.LongBuffer, java.nio.LongBuffer)} and {@link #saEvtEventAttributesGet(long, saEvt.SaEvtEventPatternArrayT, com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saEvtEventAttributesGet(long eventHandle, SaEvtEventPatternArrayT patternArray, Pointer priority, LongByReference retentionTime, Pointer publisherName, LongByReference publishTime, LongByReference eventId);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventAttributesGet(SaEvtEventHandleT, SaEvtEventPatternArrayT*, SaUint8T*, SaTimeT*, SaNameT*, SaTimeT*, SaEvtEventIdT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:143</i>
	 */
	//int saEvtEventAttributesGet(long eventHandle, SaEvtEventPatternArrayT patternArray, ByteBuffer priority, LongBuffer retentionTime, Pointer publisherName, LongBuffer publishTime, LongBuffer eventId);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventDataGet(SaEvtEventHandleT, void*, SaSizeT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:151</i><br>
	 * use the safer methods {@link #saEvtEventDataGet(long, com.sun.jna.Pointer, java.nio.LongBuffer)} and {@link #saEvtEventDataGet(long, com.sun.jna.Pointer, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saEvtEventDataGet(long eventHandle, Pointer eventData, LongByReference eventDataSize);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventDataGet(SaEvtEventHandleT, void*, SaSizeT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:151</i>
	 */
	//int saEvtEventDataGet(long eventHandle, Pointer eventData, LongBuffer eventDataSize);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventPublish(SaEvtEventHandleT, const void*, SaSizeT, SaEvtEventIdT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:154</i><br>
	 * use the safer methods {@link #saEvtEventPublish(long, com.sun.jna.Pointer, long, java.nio.LongBuffer)} and {@link #saEvtEventPublish(long, com.sun.jna.Pointer, long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saEvtEventPublish(long eventHandle, Pointer eventData, long eventDataSize, LongByReference eventId);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventPublish(SaEvtEventHandleT, const void*, SaSizeT, SaEvtEventIdT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:154</i>
	 */
	//int saEvtEventPublish(long eventHandle, Pointer eventData, long eventDataSize, LongBuffer eventId);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventSubscribe(SaEvtChannelHandleT, const SaEvtEventFilterArrayT*, SaEvtSubscriptionIdT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:158</i>
	 */
	int saEvtEventSubscribe(long channelHandle, SaEvtEventFilterArrayT filters, int subscriptionId);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventUnsubscribe(SaEvtChannelHandleT, SaEvtSubscriptionIdT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:162</i>
	 */
	int saEvtEventUnsubscribe(long channelHandle, int subscriptionId);
	/**
	 * Original signature : <code>SaAisErrorT saEvtEventRetentionTimeClear(SaEvtChannelHandleT, SaEvtEventIdT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h:165</i>
	 */
	int saEvtEventRetentionTimeClear(long channelHandle, long eventId);
}
