package saEvt;
import saEvt.SaEventClientLibrary.SaEvtChannelOpenCallbackT;
import saEvt.SaEventClientLibrary.SaEvtEventDeliverCallbackT;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaEvtCallbacksT extends Structure {
	/** C type : SaEvtChannelOpenCallbackT */
	public SaEvtChannelOpenCallbackT saEvtChannelOpenCallback;
	/** C type : SaEvtEventDeliverCallbackT */
	public SaEvtEventDeliverCallbackT saEvtEventDeliverCallback;
	public SaEvtCallbacksT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("saEvtChannelOpenCallback", "saEvtEventDeliverCallback");
	}
	/**
	 * @param saEvtChannelOpenCallback C type : SaEvtChannelOpenCallbackT<br>
	 * @param saEvtEventDeliverCallback C type : SaEvtEventDeliverCallbackT
	 */
	public SaEvtCallbacksT(SaEvtChannelOpenCallbackT saEvtChannelOpenCallback, SaEvtEventDeliverCallbackT saEvtEventDeliverCallback) {
		super();
		this.saEvtChannelOpenCallback = saEvtChannelOpenCallback;
		this.saEvtEventDeliverCallback = saEvtEventDeliverCallback;
	}
	public SaEvtCallbacksT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaEvtCallbacksT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaEvtCallbacksT implements Structure.ByValue {
		
	};
}
