package saEvt;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/event/include/saEvt.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaEvtEventFilterArrayT extends Structure {
	/** C type : SaSizeT */
	public long filtersNumber;
	/** C type : SaEvtEventFilterT* */
	public saEvt.SaEvtEventFilterT.ByReference filters;
	public SaEvtEventFilterArrayT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("filtersNumber", "filters");
	}
	/**
	 * @param filtersNumber C type : SaSizeT<br>
	 * @param filters C type : SaEvtEventFilterT*
	 */
	public SaEvtEventFilterArrayT(long filtersNumber, saEvt.SaEvtEventFilterT.ByReference filters) {
		super();
		this.filtersNumber = filtersNumber;
		this.filters = filters;
	}
	public SaEvtEventFilterArrayT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaEvtEventFilterArrayT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaEvtEventFilterArrayT implements Structure.ByValue {
		
	};
}
