package cliocapi;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
/**
 * JNA Wrapper for library <b>clIocApi</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ClIocApiLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "clIocApi";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(ClIocApiLibrary.JNA_LIBRARY_NAME);
	public static final ClIocApiLibrary INSTANCE = (ClIocApiLibrary)Native.loadLibrary(ClIocApiLibrary.JNA_LIBRARY_NAME, ClIocApiLibrary.class);
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
	 * enum values
	 */
	public static interface ClIocPriorityT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:131</i> */
		public static final int CL_IOC_DEFAULT_PRIORITY = 0;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:136</i> */
		public static final int CL_IOC_HIGH_PRIORITY = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:141</i> */
		public static final int CL_IOC_LOW_PRIORITY = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:147</i> */
		public static final int CL_IOC_ORDERED_PRIORITY = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:152</i> */
		public static final int CL_IOC_NOTIFICATION_PRIORITY = 4;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:157</i> */
		public static final int CL_IOC_RESERVED_PRIORITY = 5;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:159</i> */
		public static final int CL_IOC_RESERVED_PRIORITY_USER = 6;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:161</i> */
		public static final int CL_IOC_RESERVED_PRIORITY_USER_END = 16;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:166</i> */
		public static final int CL_IOC_MAX_PRIORITIES = (int)ClIocApiLibrary.ClIocPriorityT.CL_IOC_RESERVED_PRIORITY_USER_END + 1;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
	 * enum values
	 */
	public static interface ClIocNotificationActionT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:178</i> */
		public static final int CL_IOC_NOTIFICATION_DISABLE = 0;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:183</i> */
		public static final int CL_IOC_NOTIFICATION_ENABLE = 1;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
	 * enum values
	 */
	public static interface ClIocMessageOption {
		/**
		 * The message is persistent in nature and is not consumed by IOC<br>
		 * on send.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:343</i>
		 */
		public static final int CL_IOC_PERSISTENT_MSG = 0;
		/**
		 * The message is non persistent in nature and is consumed by IOC<br>
		 * on send. This message cannot be reused.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:349</i>
		 */
		public static final int CL_IOC_NON_PERSISTENT_MSG = 1;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
	 * enum values
	 */
	public static interface ClIocQueueId {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:436</i> */
		public static final int CL_IOC_SENDQ = 0;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:437</i> */
		public static final int CL_IOC_RECVQ = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:438</i> */
		public static final int CL_IOC_QUEUE_MAX = 2;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
	 * enum values
	 */
	public static interface ClIocTLContext {
		/**
		 * The context for Global scope entries.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:516</i>
		 */
		public static final int CL_IOC_TL_GLOBAL_SCOPE = 0;
		/**
		 * The context for local scope entries.<br>
		 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h:521</i>
		 */
		public static final int CL_IOC_TL_LOCAL_SCOPE = 1;
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_HEADER_VERSION = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_NOTIFICATION_VERSION = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_TIMEOUT_FOREVER = (int)(~0);
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_RECEIVE_TIMEOUT = (int)1500;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_UNRELIABLE_MESSAGING = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_RELIABLE_MESSAGING = (int)(1 << 0);
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_NODE_UP = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_NODE_DOWN = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_LINK_UP = (int)2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_LINK_DOWN = (int)3;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final long CL_IOC_BROADCAST_ADDRESS = (long)0xffffffffL;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_RESERVED_ADDRESS = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_GEO_ADDR_MAX_LENGTH = (int)128;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_PHYSICAL_ADDRESS_TYPE = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_LOGICAL_ADDRESS_TYPE = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_MULTICAST_ADDRESS_TYPE = (int)2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_MASTER_ADDRESS_TYPE = (int)3;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_INTRANODE_ADDRESS_TYPE = (int)4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_USER_ADDRESS_TYPE = (int)10;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_BROADCAST_ADDRESS_TYPE = (int)0xff;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_ADDRESS_TYPE_BITS = (int)(0x8);
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_ADDRESS_TYPE_MASK = (int)((1 << (0x8)) - 1);
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_NODE_MASK = (int)(~0 >> (0x8));
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_ADDRESS_TYPE_SHIFT_WORD = (int)(32 - (0x8));
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_ADDRESS_TYPE_SHIFT_DWORD = (int)(64 - (0x8));
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_TL_ACTIVE = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_TL_STDBY = (int)1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i> */
	public static final int CL_IOC_TL_NO_REPLICATION = (int)0;
	public static class ClIocNodeAddressT extends PointerType {
		public ClIocNodeAddressT(Pointer address) {
			super(address);
		}
		public ClIocNodeAddressT() {
			super();
		}
	};
	public static class ClBoolT extends PointerType {
		public ClBoolT(Pointer address) {
			super(address);
		}
		public ClBoolT() {
			super();
		}
	};
	public static class ClIocPortT extends PointerType {
		public ClIocPortT(Pointer address) {
			super(address);
		}
		public ClIocPortT() {
			super();
		}
	};
	public static class ClIocLogicalAddressT extends PointerType {
		public ClIocLogicalAddressT(Pointer address) {
			super(address);
		}
		public ClIocLogicalAddressT() {
			super();
		}
	};
	public static class ClWaterMarkT extends PointerType {
		public ClWaterMarkT(Pointer address) {
			super(address);
		}
		public ClWaterMarkT() {
			super();
		}
	};
	public static class ClUint8T extends PointerType {
		public ClUint8T(Pointer address) {
			super(address);
		}
		public ClUint8T() {
			super();
		}
	};
	public static class ClUint32T extends PointerType {
		public ClUint32T(Pointer address) {
			super(address);
		}
		public ClUint32T() {
			super();
		}
	};
	public static class ClCharT extends PointerType {
		public ClCharT(Pointer address) {
			super(address);
		}
		public ClCharT() {
			super();
		}
	};
	public static class ClWordT extends PointerType {
		public ClWordT(Pointer address) {
			super(address);
		}
		public ClWordT() {
			super();
		}
	};
	public static class ClIocMulticastAddressT extends PointerType {
		public ClIocMulticastAddressT(Pointer address) {
			super(address);
		}
		public ClIocMulticastAddressT() {
			super();
		}
	};
}
