package cliocapi;
import cliocapi.ClIocApiLibrary.ClIocNodeAddressT;
import cliocapi.ClIocApiLibrary.ClIocPortT;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClIocPhysicalAddress extends Structure {
	/**
	 * The IOC Node address.<br>
	 * C type : ClIocNodeAddressT
	 */
	public ClIocNodeAddressT nodeAddress;
	/**
	 * The IOC communication end point identification on a node.<br>
	 * C type : ClIocPortT
	 */
	public ClIocPortT portId;
	public ClIocPhysicalAddress() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("nodeAddress", "portId");
	}
	/**
	 * @param nodeAddress The IOC Node address.<br>
	 * C type : ClIocNodeAddressT<br>
	 * @param portId The IOC communication end point identification on a node.<br>
	 * C type : ClIocPortT
	 */
	public ClIocPhysicalAddress(ClIocNodeAddressT nodeAddress, ClIocPortT portId) {
		super();
		this.nodeAddress = nodeAddress;
		this.portId = portId;
	}
	public ClIocPhysicalAddress(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClIocPhysicalAddress implements Structure.ByReference {
		
	};
	public static class ByValue extends ClIocPhysicalAddress implements Structure.ByValue {
		
	};
}
