package cliocapi;
import cliocapi.ClIocApiLibrary.ClIocLogicalAddressT;
import cliocapi.ClIocApiLibrary.ClUint32T;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClIocTlInfo extends Structure {
	/**
	 * Logical address of the service.<br>
	 * C type : ClIocLogicalAddressT
	 */
	public ClIocLogicalAddressT logicalAddr;
	/**
	 * Id of the component providing the service.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T compId;
	/**
	 * Context, it can be either \c GLOBAL or \c LOCAL.<br>
	 * C type : ClIocTLContextT
	 */
	public int contextType;
	/**
	 * Replication Semantics.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T unused;
	/**
	 * Active or Standby mode.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T haState;
	/**
	 * Physical address of the component.<br>
	 * C type : ClIocPhysicalAddressT
	 */
	public ClIocPhysicalAddress physicalAddr;
	public ClIocTlInfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("logicalAddr", "compId", "contextType", "unused", "haState", "physicalAddr");
	}
	/**
	 * @param logicalAddr Logical address of the service.<br>
	 * C type : ClIocLogicalAddressT<br>
	 * @param compId Id of the component providing the service.<br>
	 * C type : ClUint32T<br>
	 * @param contextType Context, it can be either \c GLOBAL or \c LOCAL.<br>
	 * C type : ClIocTLContextT<br>
	 * @param unused Replication Semantics.<br>
	 * C type : ClUint32T<br>
	 * @param haState Active or Standby mode.<br>
	 * C type : ClUint32T<br>
	 * @param physicalAddr Physical address of the component.<br>
	 * C type : ClIocPhysicalAddressT
	 */
	public ClIocTlInfo(ClIocLogicalAddressT logicalAddr, ClUint32T compId, int contextType, ClUint32T unused, ClUint32T haState, ClIocPhysicalAddress physicalAddr) {
		super();
		this.logicalAddr = logicalAddr;
		this.compId = compId;
		this.contextType = contextType;
		this.unused = unused;
		this.haState = haState;
		this.physicalAddr = physicalAddr;
	}
	public ClIocTlInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClIocTlInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends ClIocTlInfo implements Structure.ByValue {
		
	};
}
