package cliocapi;
import cliocapi.ClIocApiLibrary.ClUint32T;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClIocTLMappingT extends Structure {
	/**
	 * State of the component corresponding to the physicalAddr.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T haState;
	/**
	 * Physical address of the component.<br>
	 * C type : ClIocPhysicalAddressT
	 */
	public ClIocPhysicalAddress physicalAddr;
	public ClIocTLMappingT() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("haState", "physicalAddr");
	}
	/**
	 * @param haState State of the component corresponding to the physicalAddr.<br>
	 * C type : ClUint32T<br>
	 * @param physicalAddr Physical address of the component.<br>
	 * C type : ClIocPhysicalAddressT
	 */
	public ClIocTLMappingT(ClUint32T haState, ClIocPhysicalAddress physicalAddr) {
		super();
		this.haState = haState;
		this.physicalAddr = physicalAddr;
	}
	public ClIocTLMappingT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClIocTLMappingT implements Structure.ByReference {
		
	};
	public static class ByValue extends ClIocTLMappingT implements Structure.ByValue {
		
	};
}
