package cliocapi;
import cliocapi.ClIocApiLibrary.ClBoolT;
import cliocapi.ClIocApiLibrary.ClCharT;
import cliocapi.ClIocApiLibrary.ClIocNodeAddressT;
import cliocapi.ClIocApiLibrary.ClIocPortT;
import cliocapi.ClIocApiLibrary.ClUint32T;
import cliocapi.ClIocApiLibrary.ClUint8T;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/ioc/include/clIocApi.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ClIocLibConfig extends Structure {
	/**
	 * Version of IOC.<br>
	 * C type : ClUint8T
	 */
	public ClUint8T version;
	/**
	 * The IOC address of the node.<br>
	 * C type : ClIocNodeAddressT
	 */
	public ClIocNodeAddressT nodeAddress;
	/**
	 * The Geographical address.<br>
	 * C type : ClCharT[128 + 1]
	 */
	public ClCharT[] iocGeoGraphicalAddress = new ClCharT[128 + 1];
	/**
	 * Maximum Number of priority.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T iocMaxNumOfPriorities;
	/**
	 * The reassembly timeout.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T iocReassemblyTimeOut;
	/**
	 * Maximum number of transport.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T iocMaxNumOfXports;
	/**
	 * IOC node level heartbeating time interval.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T iocHeartbeatTimeInterval;
	/**
	 * Maximum number of entries for the Transparency Layer.<br>
	 * C type : ClUint32T
	 */
	public ClUint32T iocTLMaxEntries;
	/** C type : ClIocQueueInfoT */
	public ClIocQueueInfo iocSendQInfo;
	/** C type : ClIocQueueInfoT */
	public ClIocQueueInfo iocRecvQInfo;
	/** C type : ClIocPortT */
	public ClIocPortT iocNodeRepresentative;
	/** C type : ClBoolT */
	public ClBoolT isNodeRepresentative;
	public ClIocLibConfig() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("version", "nodeAddress", "iocGeoGraphicalAddress", "iocMaxNumOfPriorities", "iocReassemblyTimeOut", "iocMaxNumOfXports", "iocHeartbeatTimeInterval", "iocTLMaxEntries", "iocSendQInfo", "iocRecvQInfo", "iocNodeRepresentative", "isNodeRepresentative");
	}
	public ClIocLibConfig(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends ClIocLibConfig implements Structure.ByReference {
		
	};
	public static class ByValue extends ClIocLibConfig implements Structure.ByValue {
		
	};
}
