package saAis;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * JNA Wrapper for library <b>saAis</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SaAisLibrary {//extends Library {
	/*public static final String JNA_LIBRARY_NAME = "saAis";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SaAisLibrary.JNA_LIBRARY_NAME);
	public static final SaAisLibrary INSTANCE = (SaAisLibrary)Native.loadLibrary(SaAisLibrary.JNA_LIBRARY_NAME, SaAisLibrary.class);*/
	/**
	 * <i>native declaration : saAis.h</i><br>
	 * enum values
	 */
	public static interface SaBoolT {
		/** <i>native declaration : saAis.h:44</i> */
		public static final int SA_FALSE = 0;
		/** <i>native declaration : saAis.h:45</i> */
		public static final int SA_TRUE = 1;
	};
	/**
	 * <i>native declaration : saAis.h</i><br>
	 * enum values
	 */
	public static interface SaDispatchFlagsT {
		/** <i>native declaration : saAis.h:95</i> */
		public static final int SA_DISPATCH_ONE = 1;
		/** <i>native declaration : saAis.h:96</i> */
		public static final int SA_DISPATCH_ALL = 2;
		/** <i>native declaration : saAis.h:97</i> */
		public static final int SA_DISPATCH_BLOCKING = 3;
	};
	/**
	 * <i>native declaration : saAis.h</i><br>
	 * enum values
	 */
	public static interface SaAisErrorT {
		/** <i>native declaration : saAis.h:101</i> */
		public static final int SA_AIS_OK = 1;
		/** <i>native declaration : saAis.h:102</i> */
		public static final int SA_AIS_ERR_LIBRARY = 2;
		/** <i>native declaration : saAis.h:103</i> */
		public static final int SA_AIS_ERR_VERSION = 3;
		/** <i>native declaration : saAis.h:104</i> */
		public static final int SA_AIS_ERR_INIT = 4;
		/** <i>native declaration : saAis.h:105</i> */
		public static final int SA_AIS_ERR_TIMEOUT = 5;
		/** <i>native declaration : saAis.h:106</i> */
		public static final int SA_AIS_ERR_TRY_AGAIN = 6;
		/** <i>native declaration : saAis.h:107</i> */
		public static final int SA_AIS_ERR_INVALID_PARAM = 7;
		/** <i>native declaration : saAis.h:108</i> */
		public static final int SA_AIS_ERR_NO_MEMORY = 8;
		/** <i>native declaration : saAis.h:109</i> */
		public static final int SA_AIS_ERR_BAD_HANDLE = 9;
		/** <i>native declaration : saAis.h:110</i> */
		public static final int SA_AIS_ERR_BUSY = 10;
		/** <i>native declaration : saAis.h:111</i> */
		public static final int SA_AIS_ERR_ACCESS = 11;
		/** <i>native declaration : saAis.h:112</i> */
		public static final int SA_AIS_ERR_NOT_EXIST = 12;
		/** <i>native declaration : saAis.h:113</i> */
		public static final int SA_AIS_ERR_NAME_TOO_LONG = 13;
		/** <i>native declaration : saAis.h:114</i> */
		public static final int SA_AIS_ERR_EXIST = 14;
		/** <i>native declaration : saAis.h:115</i> */
		public static final int SA_AIS_ERR_NO_SPACE = 15;
		/** <i>native declaration : saAis.h:116</i> */
		public static final int SA_AIS_ERR_INTERRUPT = 16;
		/** <i>native declaration : saAis.h:117</i> */
		public static final int SA_AIS_ERR_NAME_NOT_FOUND = 17;
		/** <i>native declaration : saAis.h:118</i> */
		public static final int SA_AIS_ERR_NO_RESOURCES = 18;
		/** <i>native declaration : saAis.h:119</i> */
		public static final int SA_AIS_ERR_NOT_SUPPORTED = 19;
		/** <i>native declaration : saAis.h:120</i> */
		public static final int SA_AIS_ERR_BAD_OPERATION = 20;
		/** <i>native declaration : saAis.h:121</i> */
		public static final int SA_AIS_ERR_FAILED_OPERATION = 21;
		/** <i>native declaration : saAis.h:122</i> */
		public static final int SA_AIS_ERR_MESSAGE_ERROR = 22;
		/** <i>native declaration : saAis.h:123</i> */
		public static final int SA_AIS_ERR_QUEUE_FULL = 23;
		/** <i>native declaration : saAis.h:124</i> */
		public static final int SA_AIS_ERR_QUEUE_NOT_AVAILABLE = 24;
		/** <i>native declaration : saAis.h:125</i> */
		public static final int SA_AIS_ERR_BAD_FLAGS = 25;
		/** <i>native declaration : saAis.h:126</i> */
		public static final int SA_AIS_ERR_TOO_BIG = 26;
		/** <i>native declaration : saAis.h:127</i> */
		public static final int SA_AIS_ERR_NO_SECTIONS = 27;
	};
	/** <i>native declaration : saAis.h</i> */
  public static final long SA_TIME_END = (long)0x7FFFFFFFFFFFFFFFL;	
	public static final long SA_TIME_BEGIN = (long)0x0L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_UNKNOWN = (long)0x8000000000000000L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_ONE_MICROSECOND = (long)1000L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_ONE_MILLISECOND = (long)1000000L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_ONE_SECOND = (long)1000000000L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_ONE_MINUTE = (long)60000000000L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_ONE_HOUR = (long)3600000000000L;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_TIME_ONE_DAY = (long)86400000000000L;
	/** <i>native declaration : saAis.h</i> */
	public static final int SA_MAX_NAME_LENGTH = (int)256;
	/** <i>native declaration : saAis.h</i> */
	public static final int SA_TRACK_CURRENT = (int)0x01;
	/** <i>native declaration : saAis.h</i> */
	public static final int SA_TRACK_CHANGES = (int)0x02;
	/** <i>native declaration : saAis.h</i> */
	public static final int SA_TRACK_CHANGES_ONLY = (int)0x04;
	/** <i>native declaration : saAis.h</i> */
	public static final long SA_HANDLE_INVALID = (long)0x0L;
	
	public static class SaNameT extends Structure {
	/** C type : SaUint16T */
	public short length;
	/** C type : SaUint8T[256] */
	public byte[] value = new byte[256];
	public SaNameT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("length", "value");
	}
	/**
	 * @param length C type : SaUint16T<br>
	 * @param value C type : SaUint8T[256]
	 */
	public SaNameT(short length, byte value[]) {
		super();
		this.length = length;
		if ((value.length != this.length) || (this.length > this.value.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.value = value;
	}
	public SaNameT(Pointer peer) {
		super(peer);
	}
	
	public String toNameString()
	{
	  if (length<=0)
	    return "";
	  return new String(value,0,length);
	}
	
	public static class ByReference extends SaNameT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaNameT implements Structure.ByValue {
		
	};
};

public static class SaVersionT extends Structure {
        public byte releaseCode;
        public byte majorVersion;
        public byte minorVersion;

        @Override
        protected List<String> getFieldOrder() {
            return List.of("releaseCode", "majorVersion", "minorVersion");
        }
        public static class ByReference extends SaVersionT implements Structure.ByReference {
		
	      };
};

}
