package saMsg;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaMsgQueueStatusT extends Structure {
	/** C type : SaMsgQueueCreationFlagsT */
	public int creationFlags;
	/** C type : SaTimeT */
	public long retentionTime;
	/** C type : SaTimeT */
	public long closeTime;
	/** C type : SaMsgQueueUsageT[3 + 1] */
	public SaMsgQueueUsageT[] saMsgQueueUsage = new SaMsgQueueUsageT[3 + 1];
	public SaMsgQueueStatusT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("creationFlags", "retentionTime", "closeTime", "saMsgQueueUsage");
	}
	/**
	 * @param creationFlags C type : SaMsgQueueCreationFlagsT<br>
	 * @param retentionTime C type : SaTimeT<br>
	 * @param closeTime C type : SaTimeT<br>
	 * @param saMsgQueueUsage C type : SaMsgQueueUsageT[3 + 1]
	 */
	public SaMsgQueueStatusT(int creationFlags, long retentionTime, long closeTime, SaMsgQueueUsageT saMsgQueueUsage[]) {
		super();
		this.creationFlags = creationFlags;
		this.retentionTime = retentionTime;
		this.closeTime = closeTime;
		if ((saMsgQueueUsage.length != this.saMsgQueueUsage.length)) 
			throw new IllegalArgumentException("Wrong array size !");
		this.saMsgQueueUsage = saMsgQueueUsage;
	}
	public SaMsgQueueStatusT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaMsgQueueStatusT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaMsgQueueStatusT implements Structure.ByValue {
		
	};
}
