package saMsg;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaMsgQueueGroupNotificationBufferT extends Structure {
	/** C type : SaUint32T */
	public int numberOfItems;
	/** C type : SaMsgQueueGroupNotificationT* */
	public saMsg.SaMsgQueueGroupNotificationT.ByReference notification;
	/**
	 * @see SaMsgQueueGroupPolicyT<br>
	 * C type : SaMsgQueueGroupPolicyT
	 */
	public int queueGroupPolicy;
	public SaMsgQueueGroupNotificationBufferT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("numberOfItems", "notification", "queueGroupPolicy");
	}
	/**
	 * @param numberOfItems C type : SaUint32T<br>
	 * @param notification C type : SaMsgQueueGroupNotificationT*<br>
	 * @param queueGroupPolicy @see SaMsgQueueGroupPolicyT<br>
	 * C type : SaMsgQueueGroupPolicyT
	 */
	public SaMsgQueueGroupNotificationBufferT(int numberOfItems, saMsg.SaMsgQueueGroupNotificationT.ByReference notification, int queueGroupPolicy) {
		super();
		this.numberOfItems = numberOfItems;
		this.notification = notification;
		this.queueGroupPolicy = queueGroupPolicy;
	}
	public SaMsgQueueGroupNotificationBufferT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaMsgQueueGroupNotificationBufferT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaMsgQueueGroupNotificationBufferT implements Structure.ByValue {
		
	};
}
