package saMsg;
import saMsg.SaMsgClientLibrary.SaMsgMessageDeliveredCallbackT;
import saMsg.SaMsgClientLibrary.SaMsgMessageReceivedCallbackT;
import saMsg.SaMsgClientLibrary.SaMsgQueueGroupTrackCallbackT;
import saMsg.SaMsgClientLibrary.SaMsgQueueOpenCallbackT;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaMsgCallbacksT extends Structure {
	/** C type : SaMsgQueueOpenCallbackT */
	public SaMsgQueueOpenCallbackT saMsgQueueOpenCallback;
	/** C type : SaMsgQueueGroupTrackCallbackT */
	public SaMsgQueueGroupTrackCallbackT saMsgQueueGroupTrackCallback;
	/** C type : SaMsgMessageDeliveredCallbackT */
	public SaMsgMessageDeliveredCallbackT saMsgMessageDeliveredCallback;
	/** C type : SaMsgMessageReceivedCallbackT */
	public SaMsgMessageReceivedCallbackT saMsgMessageReceivedCallback;
	public SaMsgCallbacksT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("saMsgQueueOpenCallback", "saMsgQueueGroupTrackCallback", "saMsgMessageDeliveredCallback", "saMsgMessageReceivedCallback");
	}
	/**
	 * @param saMsgQueueOpenCallback C type : SaMsgQueueOpenCallbackT<br>
	 * @param saMsgQueueGroupTrackCallback C type : SaMsgQueueGroupTrackCallbackT<br>
	 * @param saMsgMessageDeliveredCallback C type : SaMsgMessageDeliveredCallbackT<br>
	 * @param saMsgMessageReceivedCallback C type : SaMsgMessageReceivedCallbackT
	 */
	public SaMsgCallbacksT(SaMsgQueueOpenCallbackT saMsgQueueOpenCallback, SaMsgQueueGroupTrackCallbackT saMsgQueueGroupTrackCallback, SaMsgMessageDeliveredCallbackT saMsgMessageDeliveredCallback, SaMsgMessageReceivedCallbackT saMsgMessageReceivedCallback) {
		super();
		this.saMsgQueueOpenCallback = saMsgQueueOpenCallback;
		this.saMsgQueueGroupTrackCallback = saMsgQueueGroupTrackCallback;
		this.saMsgMessageDeliveredCallback = saMsgMessageDeliveredCallback;
		this.saMsgMessageReceivedCallback = saMsgMessageReceivedCallback;
	}
	public SaMsgCallbacksT(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends SaMsgCallbacksT implements Structure.ByReference {
		
	};
	public static class ByValue extends SaMsgCallbacksT implements Structure.ByValue {
		
	};
}
