package saMsg;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import saAis.SaAisLibrary.SaVersionT;
/**
 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SaMsgMessageT extends Structure {
	/** C type : SaUint32T */
	public int type;
	public saAis.SaAisLibrary.SaVersionT version;
	/** C type : SaSizeT */
	public long size;
	/** C type : SaNameT* */
	public Pointer senderName;
	/** C type : void* */
	public Pointer data;
	/** C type : SaUint8T */
	public byte priority;
	public SaMsgMessageT() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("type", "version", "size", "senderName", "data", "priority");
	}
	/**
	 * @param type C type : SaUint32T<br>
	 * @param size C type : SaSizeT<br>
	 * @param senderName C type : SaNameT*<br>
	 * @param data C type : void*<br>
	 * @param priority C type : SaUint8T
	 */
	public SaMsgMessageT(int type, saAis.SaAisLibrary.SaVersionT version, long size, Pointer senderName, Pointer data, byte priority) {
		super();
		this.type = type;
		this.version = version;
		this.size = size;
		this.senderName = senderName;
		this.data = data;
		this.priority = priority;
	}
	public SaMsgMessageT(Pointer peer) {
		super(peer);
	}
	public static abstract class ByReference extends SaMsgMessageT implements Structure.ByReference {
		
	};
	public static abstract class ByValue extends SaMsgMessageT implements Structure.ByValue {
		
	};
}
