package saMsg;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.LongByReference;
import java.nio.LongBuffer;
/**
 * JNA Wrapper for library <b>ClMsgClient</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface SaMsgClientLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ClMsgClient";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(SaMsgClientLibrary.JNA_LIBRARY_NAME);
	public static final SaMsgClientLibrary INSTANCE = (SaMsgClientLibrary)Native.load(SaMsgClientLibrary.JNA_LIBRARY_NAME, SaMsgClientLibrary.class);
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i><br>
	 * enum values
	 */
	public static interface SaMsgQueueGroupPolicyT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:68</i> */
		public static final int SA_MSG_QUEUE_GROUP_ROUND_ROBIN = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:69</i> */
		public static final int SA_MSG_QUEUE_GROUP_LOCAL_ROUND_ROBIN = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:70</i> */
		public static final int SA_MSG_QUEUE_GROUP_LOCAL_BEST_QUEUE = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:71</i> */
		public static final int SA_MSG_QUEUE_GROUP_BROADCAST = 4;
	};
	/**
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i><br>
	 * enum values
	 */
	public static interface SaMsgQueueGroupChangesT {
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:96</i> */
		public static final int SA_MSG_QUEUE_GROUP_NO_CHANGE = 1;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:97</i> */
		public static final int SA_MSG_QUEUE_GROUP_ADDED = 2;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:98</i> */
		public static final int SA_MSG_QUEUE_GROUP_REMOVED = 3;
		/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:99</i> */
		public static final int SA_MSG_QUEUE_GROUP_STATE_CHANGED = 4;
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_MESSAGE_DELIVERED_ACK = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_QUEUE_PERSISTENT = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_MESSAGE_HIGHEST_PRIORITY = (int)0;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_MESSAGE_LOWEST_PRIORITY = (int)3;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_QUEUE_CREATE = (int)0x1;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_QUEUE_RECEIVE_CALLBACK = (int)0x2;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public static final int SA_MSG_QUEUE_EMPTY = (int)0x4;
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public interface SaMsgQueueOpenCallbackT extends Callback {
		void apply(long invocation, long queueHandle, int error);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public interface SaMsgQueueGroupTrackCallbackT extends Callback {
		void apply(Pointer queueGroupName, SaMsgQueueGroupNotificationBufferT notificationBuffer, int numberOfMembers, int error);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public interface SaMsgMessageDeliveredCallbackT extends Callback {
		void apply(long invocation, int error);
	};
	/** <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h</i> */
	public interface SaMsgMessageReceivedCallbackT extends Callback {
		void apply(long queueHandle);
	};
	/**
	 * Original signature : <code>SaAisErrorT saMsgInitialize(SaMsgHandleT*, const SaMsgCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:151</i><br>
	 * deprecated use the safer methods {@link #saMsgInitialize(java.nio.LongBuffer, clMsgClient.SaMsgCallbacksT, com.sun.jna.Pointer)} and {link #saMsgInitialize(com.sun.jna.ptr.LongByReference, clMsgClient.SaMsgCallbacksT, com.sun.jna.Pointer)} instead
	 */
	//@Deprecated 
	int saMsgInitialize(LongByReference msgHandle, SaMsgCallbacksT msgCallbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saMsgInitialize(SaMsgHandleT*, const SaMsgCallbacksT*, SaVersionT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:151</i>
	 */
	//int saMsgInitialize(LongBuffer msgHandle, SaMsgCallbacksT msgCallbacks, Pointer version);
	/**
	 * Original signature : <code>SaAisErrorT saMsgSelectionObjectGet(SaMsgHandleT, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:157</i><br>
	 * deprecated use the safer methods {@link #saMsgSelectionObjectGet(long, java.nio.LongBuffer)} and {@link #saMsgSelectionObjectGet(long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saMsgSelectionObjectGet(long msgHandle, LongByReference selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saMsgSelectionObjectGet(SaMsgHandleT, SaSelectionObjectT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:157</i>
	 */
	//int saMsgSelectionObjectGet(long msgHandle, LongBuffer selectionObject);
	/**
	 * Original signature : <code>SaAisErrorT saMsgDispatch(SaMsgHandleT, SaDispatchFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:161</i>
	 */
	int saMsgDispatch(long msgHandle, int dispatchFlags);
	/**
	 * Original signature : <code>SaAisErrorT saMsgFinalize(SaMsgHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:166</i>
	 */
	int saMsgFinalize(long msgHandle);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueOpen(SaMsgHandleT, const SaNameT*, const SaMsgQueueCreationAttributesT*, SaMsgQueueOpenFlagsT, SaTimeT, SaMsgQueueHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:170</i><br>
	 * deprecated use the safer methods {@link #saMsgQueueOpen(long, com.sun.jna.Pointer, clMsgClient.SaMsgQueueCreationAttributesT, int, long, java.nio.LongBuffer)} and {@link #saMsgQueueOpen(long, com.sun.jna.Pointer, clMsgClient.SaMsgQueueCreationAttributesT, int, long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saMsgQueueOpen(long msgHandle, Pointer queueName, SaMsgQueueCreationAttributesT creationAttributes, int openFlags, long timeout, LongByReference queueHandle);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueOpen(SaMsgHandleT, const SaNameT*, const SaMsgQueueCreationAttributesT*, SaMsgQueueOpenFlagsT, SaTimeT, SaMsgQueueHandleT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:170</i>
	 */
	//int saMsgQueueOpen(long msgHandle, Pointer queueName, SaMsgQueueCreationAttributesT creationAttributes, int openFlags, long timeout, LongBuffer queueHandle);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueOpenAsync(SaMsgHandleT, SaInvocationT, const SaNameT*, const SaMsgQueueCreationAttributesT*, SaMsgQueueOpenFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:179</i>
	 */
	int saMsgQueueOpenAsync(long msgHandle, long invocation, Pointer queueName, SaMsgQueueCreationAttributesT creationAttributes, int openFlags);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueClose(SaMsgQueueHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:187</i>
	 */
	int saMsgQueueClose(long queueHandle);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueStatusGet(SaMsgQueueHandleT, const SaNameT*, SaMsgQueueStatusT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:191</i>
	 */
	int saMsgQueueStatusGet(long msgHandle, Pointer queueName, SaMsgQueueStatusT queueStatus);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueRetentionTimeSet(SaMsgQueueHandleT, SaTimeT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:197</i><br>
	 * deprecated use the safer methods {@link #saMsgQueueRetentionTimeSet(long, java.nio.LongBuffer)} and {@link #saMsgQueueRetentionTimeSet(long, com.sun.jna.ptr.LongByReference)} instead
	 */
	//@Deprecated 
	int saMsgQueueRetentionTimeSet(long queueHandle, LongByReference retentionTime);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueRetentionTimeSet(SaMsgQueueHandleT, SaTimeT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:197</i>
	 */
	//int saMsgQueueRetentionTimeSet(long queueHandle, LongBuffer retentionTime);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueUnlink(SaMsgQueueHandleT, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:202</i>
	 */
	int saMsgQueueUnlink(long msgHandle, Pointer queueName);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupCreate(SaMsgHandleT, const SaNameT*, SaMsgQueueGroupPolicyT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:207</i>
	 */
	int saMsgQueueGroupCreate(long msgHandle, Pointer queueGroupName, int queueGroupPolicy);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupInsert(SaMsgHandleT, const SaNameT*, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:213</i>
	 */
	int saMsgQueueGroupInsert(long msgHandle, Pointer queueGroupName, Pointer queueName);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupRemove(SaMsgHandleT, const SaNameT*, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:219</i>
	 */
	int saMsgQueueGroupRemove(long msgHandle, Pointer queueGroupName, Pointer queueName);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupDelete(SaMsgHandleT, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:225</i>
	 */
	int saMsgQueueGroupDelete(long msgHandle, Pointer queueGroupName);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupTrack(SaMsgHandleT, const SaNameT*, SaUint8T, SaMsgQueueGroupNotificationBufferT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:230</i>
	 */
	int saMsgQueueGroupTrack(long msgHandle, Pointer queueGroupName, byte trackFlags, SaMsgQueueGroupNotificationBufferT notificationBuffer);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupTrackStop(SaMsgHandleT, const SaNameT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:237</i>
	 */
	int saMsgQueueGroupTrackStop(long msgHandle, Pointer queueGroupName);
	/**
	 * Original signature : <code>SaAisErrorT saMsgQueueGroupNotificationFree(SaMsgHandleT, SaMsgQueueGroupNotificationT*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:242</i>
	 */
	int saMsgQueueGroupNotificationFree(long msgHandle, SaMsgQueueGroupNotificationT notification);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageSend(SaMsgHandleT, const SaNameT*, const SaMsgMessageT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:247</i>
	 */
	int saMsgMessageSend(long msgHandle, Pointer destination, SaMsgMessageT message, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageSendAsync(SaMsgHandleT, SaInvocationT, const SaNameT*, const SaMsgMessageT*, SaMsgAckFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:254</i>
	 */
	int saMsgMessageSendAsync(long msgHandle, long invocation, Pointer destination, SaMsgMessageT message, int ackFlags);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageGet(SaMsgQueueHandleT, SaMsgMessageT*, SaTimeT*, SaMsgSenderIdT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:262</i><br>
	 * deprecated use the safer methods {@link #saMsgMessageGet(long, clMsgClient.SaMsgMessageT, java.nio.LongBuffer, java.nio.LongBuffer, long)} and {@link #saMsgMessageGet(long, clMsgClient.SaMsgMessageT, com.sun.jna.ptr.LongByReference, com.sun.jna.ptr.LongByReference, long)} instead
	 */
	//@Deprecated 
	int saMsgMessageGet(long queueHandle, SaMsgMessageT message, LongByReference sendTime, LongByReference senderId, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageGet(SaMsgQueueHandleT, SaMsgMessageT*, SaTimeT*, SaMsgSenderIdT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:262</i>
	 */
	//int saMsgMessageGet(long queueHandle, SaMsgMessageT message, LongBuffer sendTime, LongBuffer senderId, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageDataFree(SaMsgHandleT, void*)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:270</i>
	 */
	int saMsgMessageDataFree(long msgHandle, Pointer pData);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageCancel(SaMsgQueueHandleT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:275</i>
	 */
	int saMsgMessageCancel(long queueHandle);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageSendReceive(SaMsgHandleT, const SaNameT*, const SaMsgMessageT*, SaMsgMessageT*, SaTimeT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:279</i><br>
	 * deprecated use the safer methods {@link #saMsgMessageSendReceive(long, com.sun.jna.Pointer, clMsgClient.SaMsgMessageT, clMsgClient.SaMsgMessageT, java.nio.LongBuffer, long)} and {@link #saMsgMessageSendReceive(long, com.sun.jna.Pointer, clMsgClient.SaMsgMessageT, clMsgClient.SaMsgMessageT, com.sun.jna.ptr.LongByReference, long)} instead
	 */
	//@Deprecated 
	int saMsgMessageSendReceive(long msgHandle, Pointer destination, SaMsgMessageT sendMessage, SaMsgMessageT receiveMessage, LongByReference replySendTime, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageSendReceive(SaMsgHandleT, const SaNameT*, const SaMsgMessageT*, SaMsgMessageT*, SaTimeT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:279</i>
	 */
	//int saMsgMessageSendReceive(long msgHandle, Pointer destination, SaMsgMessageT sendMessage, SaMsgMessageT receiveMessage, LongBuffer replySendTime, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageReply(SaMsgHandleT, const SaMsgMessageT*, const SaMsgSenderIdT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:288</i><br>
	 * deprecated use the safer methods {@link #saMsgMessageReply(long, clMsgClient.SaMsgMessageT, java.nio.LongBuffer, long)} and {@link #saMsgMessageReply(long, clMsgClient.SaMsgMessageT, com.sun.jna.ptr.LongByReference, long)} instead
	 */
	//@Deprecated 
	int saMsgMessageReply(long msgHandle, SaMsgMessageT replyMessage, LongByReference senderId, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageReply(SaMsgHandleT, const SaMsgMessageT*, const SaMsgSenderIdT*, SaTimeT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:288</i>
	 */
	//int saMsgMessageReply(long msgHandle, SaMsgMessageT replyMessage, LongBuffer senderId, long timeout);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageReplyAsync(SaMsgHandleT, SaInvocationT, const SaMsgMessageT*, const SaMsgSenderIdT*, SaMsgAckFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:295</i><br>
	 * deprecated use the safer methods {@link #saMsgMessageReplyAsync(long, long, clMsgClient.SaMsgMessageT, java.nio.LongBuffer, int)} and {@link #saMsgMessageReplyAsync(long, long, clMsgClient.SaMsgMessageT, com.sun.jna.ptr.LongByReference, int)} instead
	 */
	//@Deprecated 
	int saMsgMessageReplyAsync(long msgHandle, long invocation, SaMsgMessageT replyMessage, LongByReference senderId, int ackFlags);
	/**
	 * Original signature : <code>SaAisErrorT saMsgMessageReplyAsync(SaMsgHandleT, SaInvocationT, const SaMsgMessageT*, const SaMsgSenderIdT*, SaMsgAckFlagsT)</code><br>
	 * <i>native declaration : /home/clovis/opt/sdk-6.1/src/SAFplus/components/msg/include/saMsg.h:295</i>
	 */
	//int saMsgMessageReplyAsync(long msgHandle, long invocation, SaMsgMessageT replyMessage, LongBuffer senderId, int ackFlags);
}
