package clEoLib;
import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import com.sun.jna.PointerType;
import com.sun.jna.ptr.PointerByReference;
import com.sun.jna.ptr.IntByReference;
//import clEoLib.ClEoExecutionObj.ByReference;
import java.nio.ByteBuffer;
/**
 * JNA Wrapper for library <b>/home/clovis/opt/sdk-6.1/target/x86_64/linux-6.14.6/lib/libClEo.so</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface ClEoLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "ClEo";
	//public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(JNA_LIBRARY_NAME);
	//public static final ClEoLibrary INSTANCE = (ClEoLibrary)Native.loadLibrary(JNA_LIBRARY_NAME, ClEoLibrary.class);	
	//LibC INSTANCE = Native.load("c", LibC.class);
	public static final ClEoLibrary INSTANCE = Native.load(JNA_LIBRARY_NAME, ClEoLibrary.class);
	/**
	 * <i>native declaration : clEoConfigApi.h</i><br>
	 * enum values
	 */
	public static interface ClEoStateT {
		/**
		 * This indicates the initial state of the EO.<br>
		 * <i>native declaration : clEoConfigApi.h:47</i>
		 */
		public static final int CL_EO_STATE_INIT = 0x1;
		/**
		 * This indicates that the EO is in active state.<br>
		 * <i>native declaration : clEoConfigApi.h:52</i>
		 */
		public static final int CL_EO_STATE_ACTIVE = 0x2;
		/**
		 * This indicates that the EO is in standby state.<br>
		 * <i>native declaration : clEoConfigApi.h:57</i>
		 */
		public static final int CL_EO_STATE_STDBY = 0x4;
		/**
		 * This indicates that the EO is in suspended state.<br>
		 * <i>native declaration : clEoConfigApi.h:62</i>
		 */
		public static final int CL_EO_STATE_SUSPEND = 0x8;
		/**
		 * This indicates that the EO is in stopped state.<br>
		 * <i>native declaration : clEoConfigApi.h:67</i>
		 */
		public static final int CL_EO_STATE_STOP = 0x10;
		/**
		 * This indicates that the EO is in killed state.<br>
		 * <i>native declaration : clEoConfigApi.h:72</i>
		 */
		public static final int CL_EO_STATE_KILL = 0x20;
		/**
		 * This indicates that the state of the EO is resumed from the standby state.<br>
		 * <i>native declaration : clEoConfigApi.h:77</i>
		 */
		public static final int CL_EO_STATE_RESUME = 0x40;
		/**
		 * This indicates that the EO is in failed state.<br>
		 * <i>native declaration : clEoConfigApi.h:82</i>
		 */
		public static final int CL_EO_STATE_FAILED = 0x80;
		/**
		 * This indicates that the EO is thread safe.<br>
		 * <i>native declaration : clEoConfigApi.h:87</i>
		 */
		public static final int CL_EO_STATE_THREAD_SAFE = 0x100;
		/**
		 * All states<br>
		 * <i>native declaration : clEoConfigApi.h:92</i>
		 */
		public static final int CL_EO_STATE_BITS = 9;
	};
	/**
	 * <i>native declaration : clEoConfigApi.h</i><br>
	 * enum values
	 */
	public static interface ClEoApplicationTypeT {
		/**
		 * Use main thread for RMD message receive. If you select this, the main<br>
		 * thread must not be blocked in the \e ClEoAppCreateCallbackT and must return<br>
		 * immediately. Later, the main thread will be used for RMD message receive.<br>
		 * <i>native declaration : clEoConfigApi.h:104</i>
		 */
		public static final int CL_EO_USE_THREAD_FOR_RECV = 1;
		/**
		 * Give main thread to user application. If you select this, the main<br>
		 * thread must be blocked in the \e ClEoAppCreateCallbackT or used by the<br>
		 * application and must return only when the finalize \e ClEoAppDeleteCallbackT<br>
		 * is called.<br>
		 * <i>native declaration : clEoConfigApi.h:112</i>
		 */
		public static final int CL_EO_USE_THREAD_FOR_APP = 0;
	};
	/**
	 * <i>native declaration : clEoConfigApi.h</i><br>
	 * enum values
	 */
	public static interface ClEoPollingTypeT {
		/**
		 * This indicated that the Component Manager will stop heartbeat of an EO<br>
		 * if \c CL_CPM_DONT_POLL is received in the heartbeat response.<br>
		 * <i>native declaration : clEoConfigApi.h:122</i>
		 */
		public static final int CL_EO_DONT_POLL = 0;
		/**
		 * This indicated that the Component Manager will increase heartbeat<br>
		 * timeout to maximum polling timeout.<br>
		 * <i>native declaration : clEoConfigApi.h:128</i>
		 */
		public static final int CL_EO_BUSY_POLL = 1;
		/**
		 * This indicated that the Component Manager will continue with<br>
		 * default heartbeat timeout.<br>
		 * <i>native declaration : clEoConfigApi.h:134</i>
		 */
		public static final int CL_EO_DEFAULT_POLL = 2;
	};
	/**
	 * <i>native declaration : clEoApi.h</i><br>
	 * enum values
	 */
	public static interface ClEOServiceInstallOrderT {
		/**
		 * Adds to the front of the list.<br>
		 * <i>native declaration : clEoApi.h:163</i>
		 */
		public static final int CL_EO_ADD_TO_FRONT = 0;
		/**
		 * Adds to back of the list. It is used with \e clEoServiceValidate.<br>
		 * <i>native declaration : clEoApi.h:168</i>
		 */
		public static final int CL_EO_ADD_TO_BACK = 1;
	};
	/**
	 * <i>native declaration : clEoApi.h</i><br>
	 * enum values
	 */
	public static interface ClEoClientIdT {
		/**
		 * This is the service provided by Host EO.<br>
		 * <i>native declaration : clEoApi.h:208</i>
		 */
		public static final int CL_EO_NATIVE_COMPONENT_TABLE_ID = 0;
		/**
		 * This value is native EO specific.<br>
		 * <i>native declaration : clEoApi.h:213</i>
		 */
		public static final int CL_EO_DEFAULT_SERVICE_TABLE_ID = 1;
		/**
		 * This value is EO Manager specific.<br>
		 * <i>native declaration : clEoApi.h:218</i>
		 */
		public static final int CL_EO_EO_MGR_CLIENT_TABLE_ID = 2;
		/**
		 * This value is COR specific.<br>
		 * <i>native declaration : clEoApi.h:223</i>
		 */
		public static final int CL_EO_COR_CLIENT_TABLE_ID = 3;
		/**
		 * This value is Event Manager specific.<br>
		 * <i>native declaration : clEoApi.h:228</i>
		 */
		public static final int CL_EO_EVT_CLIENT_TABLE_ID = 4;
		/**
		 * This value is CPM specific.<br>
		 * <i>native declaration : clEoApi.h:233</i>
		 */
		public static final int CL_CPM_MGR_CLIENT_TABLE_ID = 5;
		/**
		 * This value is Alarm Manager specific.<br>
		 * <i>native declaration : clEoApi.h:238</i>
		 */
		public static final int CL_ALARM_CLIENT_TABLE_ID = 6;
		/**
		 * This value is Debug specific.<br>
		 * <i>native declaration : clEoApi.h:243</i>
		 */
		public static final int CL_DEBUG_CLIENT_TABLE_ID = 7;
		/**
		 * This value is Transaction Agent-specific.<br>
		 * <i>native declaration : clEoApi.h:248</i>
		 */
		public static final int CL_TXN_CLIENT_TABLE_ID = 8;
		/**
		 * This value is GMS specific.<br>
		 * <i>native declaration : clEoApi.h:253</i>
		 */
		public static final int CL_GMS_CLIENT_TABLE_ID = 9;
		/**
		 * This value AMS Mgmt Server-specific<br>
		 * <i>native declaration : clEoApi.h:258</i>
		 */
		public static final int CL_AMS_MGMT_SERVER_TABLE_ID = 10;
		/**
		 * This value AMS Mgmt Client-specific<br>
		 * <i>native declaration : clEoApi.h:263</i>
		 */
		public static final int CL_AMS_MGMT_CLIENT_TABLE_ID = 11;
		/**
		 * This value is specific to Log Client<br>
		 * <i>native declaration : clEoApi.h:268</i>
		 */
		public static final int CL_LOG_CLIENT_TABLE_ID = 12;
		/**
		 * This value is specific to Ckpt Client<br>
		 * <i>native declaration : clEoApi.h:272</i>
		 */
		public static final int CL_EO_CKPT_CLIENT_TABLE_ID = 13;
		/**
		 * This value is specific to RMD Client<br>
		 * <i>native declaration : clEoApi.h:277</i>
		 */
		public static final int CL_EO_RMD_CLIENT_TABLE_ID = 14;
		/**
		 * This value is specific to AMS metric trigger client.<br>
		 * <i>native declaration : clEoApi.h:282</i>
		 */
		public static final int CL_AMS_ENTITY_TRIGGER_TABLE_ID = 15;
		/**
		 * This value is specific to CPM mgmt. clients.<br>
		 * <i>native declaration : clEoApi.h:287</i>
		 */
		public static final int CL_CPM_MGMT_CLIENT_TABLE_ID = 16;
		/**
		 * This value is specific to MSG clients.<br>
		 * <i>native declaration : clEoApi.h:291</i>
		 */
		public static final int CL_MSG_CLIENT_TABLE_ID = 17;
		/**
		 * This value is specific to MSG clients & servers.<br>
		 * <i>native declaration : clEoApi.h:296</i>
		 */
		public static final int CL_MSG_CLIENT_SERVER_TABLE_ID = 18;
		/**
		 * Extended AMS mgmt server tables.<br>
		 * <i>native declaration : clEoApi.h:300</i>
		 */
		public static final int CL_AMS_MGMT_SERVER_TABLE2_ID = 19;
		/**
		 * CLIENT IDs till this value are reserved by Clovis.<br>
		 * <i>native declaration : clEoApi.h:305</i>
		 */
		public static final int CL_EO_CLOVIS_RESERVED_CLIENTID_END = 20;
	};
	/**
	 * <i>native declaration : clEoApi.h</i><br>
	 * enum values
	 */
	public static interface ClEoServerIdT {
		/** <i>native declaration : clEoApi.h:357</i> */
		public static final int CL_EO_NATIVE_COMPONENT_COOKIE_BASE = (((int)ClEoClientIdT.CL_EO_NATIVE_COMPONENT_TABLE_ID) << (8));
		/** <i>native declaration : clEoApi.h:359</i> */
		public static final int CL_EO_EO_MGR_SERVER_COOKIE_ID = (((int)ClEoClientIdT.CL_EO_EO_MGR_CLIENT_TABLE_ID) << (8));
		/** <i>native declaration : clEoApi.h:361</i> */
		public static final int CL_EO_COR_SERVER_COOKIE_ID = (((int)ClEoClientIdT.CL_EO_COR_CLIENT_TABLE_ID) << (8));
		/** <i>native declaration : clEoApi.h:363</i> */
		public static final int CL_EO_EVT_EVENT_DELIVERY_COOKIE_ID = (((int)ClEoClientIdT.CL_EO_EVT_CLIENT_TABLE_ID) << (8));
		/** <i>native declaration : clEoApi.h:365</i> */
		public static final int CL_EO_DEBUG_OBJECT_COOKIE_ID = (((int)ClEoClientIdT.CL_DEBUG_CLIENT_TABLE_ID) << (8));
		/** <i>native declaration : clEoApi.h:367</i> */
		public static final int CL_EO_RMD_CLIENT_COOKIE_ID = (((int)ClEoClientIdT.CL_EO_RMD_CLIENT_TABLE_ID) << (8));
	};
	/**
	 * <i>native declaration : clEoApi.h</i><br>
	 * enum values
	 */
	public static interface ClEoCrashReasonT {
		/** <i>native declaration : clEoApi.h:1342</i> */
		public static final int CL_EO_CRASH_DEADLOCK = 0;
		/** <i>native declaration : clEoApi.h:1343</i> */
		public static final int CL_EO_CRASH_HUNG_SYSCALL = 1;
	};
	/** <i>native declaration : clEoConfigApi.h</i> */
	public static final int CL_EO_MAX_NAME_LEN = (int)32;
	/** <i>native declaration : clEoConfigApi.h</i> */
	public static final int CL_EO_DEFAULT_THREADS = (int)1;
	/** <i>native declaration : clEoConfigApi.h</i> */
	public static final String CL_EO_DEFAULT_NAME = (String)"3RD_PARTY_COMP";
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_EO_SUSPENDED = (int)0x101;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_FUNC_NOT_REGISTERED = (int)0x102;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_INVALID_CLIENTID = (int)0x103;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_INVALID_SERVICEID = (int)0x104;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_LIB_ID_INVALID = (int)0x105;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_WATER_MARK_ID_INVALID = (int)0x106;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_IMPROPER_STATE = (int)0x107;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_QUEUE_OVERFLOW = (int)0x108;
	/** <i>native declaration : clEoErrors.h</i> */
	public static final int CL_EO_ERR_ENQUEUE_MSG = (int)0x109;
	/** <i>native declaration : clEoApi.h</i> */
	public static final int CL_EO_MAX_NO_FUNC = (int)64;
	/** <i>native declaration : clEoApi.h</i> */
	public static final int CL_EO_CLIENT_BIT_SHIFT = (int)6;
	/** <i>native declaration : clEoApi.h</i> */
	public static final int CL_EO_FN_MASK = (int)(0x3F);
	/** <i>native declaration : clEoApi.h</i> */
	public static final int CL_EO_SERVER_COOKIE_BIT_SIZE = (int)8;
	/** <i>native declaration : clEoApi.h</i> */
	public static final String CL_EO_EVENT_CHANNEL_NAME = (String)"CL_EO_EVENT_CHANNEL_NAME";
	/** <i>native declaration : clEoApi.h</i> */
	public static final int _TASK_SND_MASK = (int)(1);
	/** <i>native declaration : clEoApi.h</i> */
	public static final int _TASK_RCV_MASK = (int)(2);
	
	int clEoMyEoIocPortGet(IntByReference pIocPort);	
}
